/**
 * Fresh-checkout guard: the checks must not fail as if the code were broken
 * when what is actually missing is an install or a generated, gitignored file.
 *
 *   node scripts/ensure-deps.mjs      exit 0 = the checks can run for real
 *
 * `node_modules` is gitignored, so a `git worktree` — how every work order is
 * built — starts without one. The checks then fail three ways that each read
 * like a defect in the diff rather than a missing install:
 *
 *   npx tsc --noEmit  ->  "To get access to the TypeScript compiler, tsc, from
 *                          the command line ... use npm install typescript"
 *                         (npx fetched the `tsc` DECOY package from the
 *                          registry; the real compiler is a devDependency)
 *   npm test          ->  "'vitest' is not recognized as an internal or
 *                          external command"
 *   npm run lint      ->  a bare `Module.require` stack out of eslint
 *
 * WO-005 lost repeated attempts to exactly this, and telling people about it
 * did not work: HANDOVER §5, client/CLAUDE.md, AGENTS.md and
 * docs/ERROR_MONITORING.md §4 all say "npm ci first" and the same three
 * messages came back on the very next run. So the fix is a mechanism rather
 * than a sentence — the pre* hooks in package.json run this, and npm runs them
 * whoever typed the command.
 *
 * `npx tsc` / `npx expo lint` remain UNGUARDABLE — npx has no pre-hook — which
 * is why the command lists now name `npm run typecheck` / `npm run lint`.
 *
 * Costs an installed checkout two `existsSync` calls and prints nothing.
 */

import { spawnSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const client = join(dirname(fileURLToPath(import.meta.url)), '..');

// `expo-env.d.ts` is gitignored and generated by `expo start` — NOT by
// `expo export` — so a fresh checkout has none and `tsc` goes red on the
// `@/global.css` side-effect import alone. client.yml hit this as its very
// first CI failure and writes the same one static line before its Typecheck
// step; a worktree needs it for exactly the same reason. (Full typed-route
// fidelity also wants `.expo/types/`, which only an export generates — §5 and
// CI both export before tsc. This shim is the part that turns a hard error
// into a pass.)
const envShim = join(client, 'expo-env.d.ts');
if (!existsSync(envShim)) {
  writeFileSync(envShim, '/// <reference types="expo/types" />\n');
}

// npm writes .package-lock.json only after an install completes, so it — not
// the presence of node_modules/ — is what distinguishes "installed" from a
// half-written or hand-created directory. The repo root carries a node_modules
// holding nothing but .vite, which is precisely that trap.
const installed = existsSync(join(client, 'node_modules', '.package-lock.json'));
if (installed) process.exit(0);

const locked = existsSync(join(client, 'package-lock.json'));
const command = locked ? 'ci' : 'install';
console.log(`ensure-deps: client/node_modules is missing — running npm ${command}`);

const result = spawnSync(
  'npm',
  [command, '--include=dev', '--no-audit', '--no-fund'],
  {
    cwd: client,
    stdio: 'inherit',
    shell: true, // Windows needs the .cmd shim resolved
    env: {
      ...process.env,
      // Both would drop devDependencies, and typescript, vitest and eslint are
      // all devDependencies — the install would "succeed" and leave the checks
      // failing with the identical three messages.
      NODE_ENV: 'development',
      npm_config_omit: '',
    },
  },
);

if (result.error || result.status !== 0) {
  // Loud and specific: the whole point of this file is that a dependency
  // problem must never again be read as a defect in the diff.
  console.error(
    `ensure-deps: npm ${command} FAILED (${result.error?.message ?? `exit ${result.status}`}).`,
  );
  console.error(
    'ensure-deps: the check that follows cannot run — treat its output as ' +
      'meaningless, not as a code failure. Fix the install first.',
  );
  process.exit(result.status || 1);
}

console.log('ensure-deps: install complete — running the check now.');
