/**
 * Cross-language parity: the TS domain port must reproduce every golden case
 * in contracts/fixtures/ EXACTLY. The fixtures were generated by
 * tools/gen_fixtures.py from the live Python domain/ -- they are the arbiter
 * of correctness, not readability preferences (MIGRATION_PLAN note #4).
 *
 * Exact equality, floats included: both sides are IEEE-754 doubles and JSON
 * round-trips them shortest-exact. A tolerance would let a wrong formula pass.
 *
 * CI runs this beside `python tools/gen_fixtures.py --check`; together they
 * detect Python drift AND port drift from the same goldens.
 */

import { describe, expect, it } from 'vitest';

import avatarJson from '../../../../contracts/fixtures/avatar.json';
import bodyfatJson from '../../../../contracts/fixtures/bodyfat.json';
import catalogsJson from '../../../../contracts/fixtures/catalogs.json';
import helpersJson from '../../../../contracts/fixtures/helpers.json';
import xpCurveJson from '../../../../contracts/fixtures/xp_curve.json';
import xpProgressJson from '../../../../contracts/fixtures/xp_progress.json';
import xpResolveJson from '../../../../contracts/fixtures/xp_resolve.json';

import {
  avatarRarity,
  branchDisplayName,
  determineAvatarBranch,
  evolutionName,
  getAvatarStage,
  getBranchStage,
  raritySlug,
  type BranchScores,
} from '../avatar-stats';
import { bodyfatOutputs, navyBodyFatMale, safeKg } from '../bodyfat';
import { ACHIEVEMENTS, EXERCISE_LIBRARY, MUSCLE_MAP, RANK_TIERS, ROUTINE } from '../catalogs';
import { cardioEventAmount } from '../cardio';
import { nextEvolutionInfo } from '../next-evolution';
import { safeNum, score0100 } from '../physique-ratings';
import { calculateStartingLevel, rankLadder, rankName } from '../profile';
import { estimated1rm, inferMuscleGroup } from '../workouts';
import {
  FIRST_LEVEL_COST,
  LEVEL_COST_STEP,
  MAX_LEVEL,
  MIN_LEVEL,
  XP_PER_CARDIO_MINUTE,
  XP_PER_SET,
  activityXp,
  cumulativeXp,
  levelAndProgress,
  levelFromLedger,
  progressPercent,
  resolveXp,
  xpForLevel,
  xpToNextLevel,
} from '../xp';
import { avatarStageRows } from '../xp-leveling';

interface Case<I = unknown, E = unknown> {
  input: I;
  expected: E;
}

const FIXTURES: Record<string, unknown> = {
  'avatar.json': avatarJson,
  'bodyfat.json': bodyfatJson,
  'catalogs.json': catalogsJson,
  'helpers.json': helpersJson,
  'xp_curve.json': xpCurveJson,
  'xp_progress.json': xpProgressJson,
  'xp_resolve.json': xpResolveJson,
};

function fixture<T>(name: string): T {
  const fx = FIXTURES[name];
  if (!fx) {
    throw new Error(`unknown fixture ${name}`);
  }
  return fx as T;
}

/** The generator writes NaN/Infinity as marker strings (no JSON literal exists). */
function unmarker(value: unknown): unknown {
  if (value === 'NaN') return NaN;
  if (value === 'Infinity') return Infinity;
  if (value === '-Infinity') return -Infinity;
  return value;
}

/** Assert a fixture list is non-empty before iterating: any([]) is False. */
function eachCase<I, E>(cases: Case<I, E>[], run: (c: Case<I, E>) => void) {
  expect(cases.length).toBeGreaterThan(0);
  for (const c of cases) run(c);
}

// ---------------------------------------------------------------- xp_curve

describe('xp_curve.json', () => {
  const fx = fixture<{
    constants: Record<string, number>;
    xp_for_level: Case<number>[];
    xp_to_next_level: Case<number>[];
    cumulative_xp: Case<{ from_level: number; to_level: number }>[];
    activity_xp: Case<{ total_sets: unknown; cardio_minutes: unknown }>[];
  }>('xp_curve.json');

  it('constants', () => {
    expect(XP_PER_SET).toBe(fx.constants.XP_PER_SET);
    expect(XP_PER_CARDIO_MINUTE).toBe(fx.constants.XP_PER_CARDIO_MINUTE);
    expect(FIRST_LEVEL_COST).toBe(fx.constants.FIRST_LEVEL_COST);
    expect(LEVEL_COST_STEP).toBe(fx.constants.LEVEL_COST_STEP);
    expect(MIN_LEVEL).toBe(fx.constants.MIN_LEVEL);
    expect(MAX_LEVEL).toBe(fx.constants.MAX_LEVEL);
  });

  it('xp_for_level', () => {
    eachCase(fx.xp_for_level, (c) => expect(xpForLevel(c.input), `level=${c.input}`).toBe(c.expected));
  });

  it('xp_to_next_level re-export agrees', () => {
    eachCase(fx.xp_to_next_level, (c) => expect(xpToNextLevel(c.input)).toBe(c.expected));
  });

  it('cumulative_xp', () => {
    eachCase(fx.cumulative_xp, (c) =>
      expect(cumulativeXp(c.input.from_level, c.input.to_level), JSON.stringify(c.input)).toBe(c.expected)
    );
  });

  it('activity_xp', () => {
    eachCase(fx.activity_xp, (c) =>
      expect(activityXp(c.input.total_sets, c.input.cardio_minutes), JSON.stringify(c.input)).toBe(c.expected)
    );
  });
});

// ------------------------------------------------------------- xp_progress

describe('xp_progress.json', () => {
  type ProgressCase = Case<
    { base_level: unknown; total_xp?: unknown; ledger_sum?: unknown },
    { level: number; xp_into_level: number; xp_needed: number }
  >;
  const fx = fixture<{
    level_and_progress: ProgressCase[];
    level_and_progress_exact_boundaries: ProgressCase[];
    level_from_ledger: ProgressCase[];
  }>('xp_progress.json');

  const check = (got: { level: number; xpIntoLevel: number; xpNeeded: number }, c: ProgressCase) => {
    expect(
      { level: got.level, xp_into_level: got.xpIntoLevel, xp_needed: got.xpNeeded },
      JSON.stringify(c.input)
    ).toEqual(c.expected);
  };

  it('level_and_progress', () => {
    eachCase(fx.level_and_progress, (c) => check(levelAndProgress(c.input.base_level, c.input.total_xp), c));
  });

  it('the bar lands exactly on each level boundary', () => {
    eachCase(fx.level_and_progress_exact_boundaries, (c) =>
      check(levelAndProgress(c.input.base_level, c.input.total_xp), c)
    );
  });

  it('level_from_ledger', () => {
    eachCase(fx.level_from_ledger, (c) => check(levelFromLedger(c.input.base_level, c.input.ledger_sum), c));
  });
});

// -------------------------------------------------------------- xp_resolve

describe('xp_resolve.json', () => {
  const fx = fixture<{
    resolve_xp: Case<{ derived_xp: unknown; ledger_xp: unknown }, { xp: number; source: string; drift: number }>[];
    progress_percent: Case<{ xp_into_level: unknown; xp_needed: unknown }, number>[];
  }>('xp_resolve.json');

  it('resolve_xp', () => {
    eachCase(fx.resolve_xp, (c) => {
      const got = resolveXp(c.input.derived_xp, c.input.ledger_xp);
      expect({ xp: got.xp, source: got.source, drift: got.drift }, JSON.stringify(c.input)).toEqual(c.expected);
    });
  });

  it('progress_percent', () => {
    eachCase(fx.progress_percent, (c) =>
      expect(progressPercent(c.input.xp_into_level, c.input.xp_needed), JSON.stringify(c.input)).toBe(c.expected)
    );
  });
});

// ------------------------------------------------------------------ avatar

describe('avatar.json', () => {
  const fx = fixture<{
    avatar_rarity: Case<number, { name: string; icon: string; colour: string }>[];
    rarity_slug: Case<unknown, string>[];
    get_avatar_stage: Case<number, number>[];
    get_branch_stage: Case<{ branch: string; level: number }, number>[];
    determine_avatar_branch: Case<BranchScores, string>[];
    branch_display_name: Case<string, string>[];
    evolution_name: Case<{ branch: string; level: number }, string>[];
    avatar_stage_rows: Case<
      { branch: string; current_level: number },
      { level: number; name: string; stage: number; unlocked: boolean; current: boolean }[]
    >[];
    rank_tiers: [number, string][];
    rank_name: Case<number, string>[];
    rank_ladder: [number, number, string][];
    calculate_starting_level: Case<
      {
        bench_e1rm: number;
        squat_e1rm: number;
        training_years: number;
        physique_score: number;
        leanness_score: number;
      },
      number
    >[];
    next_evolution_info: Case<
      {
        branch: string;
        level: number;
        bench_e1rm: number;
        bf_mid: number | null;
        total_sets: number;
        cardio_minutes: number;
      },
      {
        target_name: string;
        target_level: number;
        requirements: { label: string; current: number; target: number; met: boolean }[];
      }
    >[];
  }>('avatar.json');

  it('avatar_rarity', () => {
    eachCase(fx.avatar_rarity, (c) => expect(avatarRarity(c.input), `level=${c.input}`).toEqual(c.expected));
  });

  it('rarity_slug never throws', () => {
    eachCase(fx.rarity_slug, (c) => expect(raritySlug(c.input), `level=${c.input}`).toBe(c.expected));
  });

  it('get_avatar_stage', () => {
    eachCase(fx.get_avatar_stage, (c) => expect(getAvatarStage(c.input)).toBe(c.expected));
  });

  it('get_branch_stage', () => {
    eachCase(fx.get_branch_stage, (c) =>
      expect(getBranchStage(c.input.branch, c.input.level), JSON.stringify(c.input)).toBe(c.expected)
    );
  });

  it('determine_avatar_branch', () => {
    eachCase(fx.determine_avatar_branch, (c) =>
      expect(determineAvatarBranch(c.input), JSON.stringify(c.input)).toBe(c.expected)
    );
  });

  it('branch_display_name', () => {
    eachCase(fx.branch_display_name, (c) => expect(branchDisplayName(c.input)).toBe(c.expected));
  });

  it('evolution_name (True Adam at 100, both ladders agree)', () => {
    eachCase(fx.evolution_name, (c) =>
      expect(evolutionName(c.input.branch, c.input.level), JSON.stringify(c.input)).toBe(c.expected)
    );
  });

  it('avatar_stage_rows', () => {
    eachCase(fx.avatar_stage_rows, (c) =>
      expect(avatarStageRows(c.input.branch, c.input.current_level), JSON.stringify(c.input)).toEqual(c.expected)
    );
  });

  it('rank ladder', () => {
    expect(fx.rank_tiers.length).toBeGreaterThan(0);
    expect(RANK_TIERS.map((t) => [...t])).toEqual(fx.rank_tiers);
    eachCase(fx.rank_name, (c) => expect(rankName(c.input), `level=${c.input}`).toBe(c.expected));
    expect(fx.rank_ladder.length).toBeGreaterThan(0);
    expect(rankLadder()).toEqual(fx.rank_ladder);
  });

  it('next_evolution_info (evolution requirements per branch)', () => {
    eachCase(fx.next_evolution_info, (c) => {
      const got = nextEvolutionInfo(c.input.branch as never, {
        level: c.input.level,
        benchE1rm: c.input.bench_e1rm,
        bfMid: c.input.bf_mid,
        totalSets: c.input.total_sets,
        cardioMinutes: c.input.cardio_minutes,
      });
      expect(
        {
          target_name: got.targetName,
          target_level: got.targetLevel,
          requirements: got.requirements.map((r) => ({
            label: r.label,
            current: r.current,
            target: r.target,
            met: r.met,
          })),
        },
        JSON.stringify(c.input)
      ).toEqual(c.expected);
    });
  });

  it('calculate_starting_level (onboarding placement)', () => {
    eachCase(fx.calculate_starting_level, (c) =>
      expect(
        calculateStartingLevel(
          c.input.bench_e1rm,
          c.input.squat_e1rm,
          c.input.training_years,
          c.input.physique_score,
          c.input.leanness_score
        ),
        JSON.stringify(c.input)
      ).toBe(c.expected)
    );
  });
});

// ----------------------------------------------------------------- bodyfat

describe('bodyfat.json', () => {
  const fx = fixture<{
    navy_body_fat_male: Case<{ height_cm: unknown; waist_cm: unknown; neck_cm: unknown }, number | null>[];
    bodyfat_outputs: Case<
      { weight_kg: unknown; bf_percent: unknown; target_bf: unknown },
      { fat_mass: number | null; lean_mass: number | null; target_weight: number | null; fat_to_lose: number | null }
    >[];
    bodyfat_outputs_default_target: Case<{ weight_kg: number; bf_percent: number }, (number | null)[]>[];
    safe_kg: Case<unknown, string>[];
  }>('bodyfat.json');

  it('navy_body_fat_male, exact doubles', () => {
    eachCase(fx.navy_body_fat_male, (c) =>
      expect(
        navyBodyFatMale(c.input.height_cm, c.input.waist_cm, c.input.neck_cm),
        JSON.stringify(c.input)
      ).toBe(c.expected)
    );
  });

  it('bodyfat_outputs', () => {
    eachCase(fx.bodyfat_outputs, (c) => {
      const [fatMass, leanMass, targetWeight, fatToLose] = bodyfatOutputs(
        c.input.weight_kg,
        c.input.bf_percent,
        c.input.target_bf
      );
      expect(
        { fat_mass: fatMass, lean_mass: leanMass, target_weight: targetWeight, fat_to_lose: fatToLose },
        JSON.stringify(c.input)
      ).toEqual(c.expected);
    });
  });

  it('default target_bf is 10', () => {
    eachCase(fx.bodyfat_outputs_default_target, (c) =>
      expect([...bodyfatOutputs(c.input.weight_kg, c.input.bf_percent)]).toEqual(c.expected)
    );
  });

  it('safe_kg formatting', () => {
    eachCase(fx.safe_kg, (c) => expect(safeKg(c.input), `value=${c.input}`).toBe(c.expected));
  });
});

// ----------------------------------------------------------------- helpers

describe('helpers.json', () => {
  const fx = fixture<{
    estimated_1rm: Case<{ weight: number; reps: number }, number>[];
    score_0_100: Case<{ value: unknown; low: number; high: number }, number>[];
    safe_num: Case<{ value: unknown; default: number }, number>[];
    safe_num_specials: Case<{ value: string; default: number }, number>[];
    infer_muscle_group: Case<string, string>[];
    cardio_event_amount: Case<unknown, number>[];
  }>('helpers.json');

  it('estimated_1rm', () => {
    eachCase(fx.estimated_1rm, (c) =>
      expect(estimated1rm(c.input.weight, c.input.reps), JSON.stringify(c.input)).toBe(c.expected)
    );
  });

  it('score_0_100', () => {
    eachCase(fx.score_0_100, (c) =>
      expect(score0100(c.input.value, c.input.low, c.input.high), JSON.stringify(c.input)).toBe(c.expected)
    );
  });

  it('safe_num', () => {
    eachCase(fx.safe_num, (c) =>
      expect(safeNum(c.input.value, c.input.default), JSON.stringify(c.input)).toBe(c.expected)
    );
  });

  it('safe_num guards NaN and infinities', () => {
    eachCase(fx.safe_num_specials, (c) =>
      expect(safeNum(unmarker(c.input.value), c.input.default), c.input.value).toBe(c.expected)
    );
  });

  it('infer_muscle_group over the whole exercise library', () => {
    eachCase(fx.infer_muscle_group, (c) => expect(inferMuscleGroup(c.input), c.input).toBe(c.expected));
  });

  it('cardio_event_amount matches the migration 002 STEP 3 literal', () => {
    eachCase(fx.cardio_event_amount, (c) =>
      expect(cardioEventAmount(c.input), `minutes=${c.input}`).toBe(c.expected)
    );
  });
});

// ---------------------------------------------------------------- catalogs

describe('catalogs.json', () => {
  const fx = fixture<{
    achievements_count: number;
    achievements: Record<string, [string, string]>;
    routine: Record<string, string[]>;
    exercise_library: Record<string, string[]>;
    muscle_map_count: number;
    muscle_map: Record<string, string>;
  }>('catalogs.json');

  it('64 achievements, byte-identical strings', () => {
    expect(fx.achievements_count).toBe(64);
    expect(Object.keys(ACHIEVEMENTS).length).toBe(fx.achievements_count);
    expect(
      Object.fromEntries(Object.entries(ACHIEVEMENTS).map(([k, v]) => [k, [...v]]))
    ).toEqual(fx.achievements);
  });

  it('routine and exercise library', () => {
    expect(Object.fromEntries(Object.entries(ROUTINE).map(([k, v]) => [k, [...v]]))).toEqual(fx.routine);
    expect(
      Object.fromEntries(Object.entries(EXERCISE_LIBRARY).map(([k, v]) => [k, [...v]]))
    ).toEqual(fx.exercise_library);
  });

  it('muscle map', () => {
    expect(fx.muscle_map_count).toBe(71);
    expect(MUSCLE_MAP).toEqual(fx.muscle_map);
  });
});
