/**
 * GENERATED — do not hand-edit. Regenerate: node scripts/gen-exercise-ids.mjs
 * (from client/). Emitted alongside src/domain/exercise-ids.generated.ts in
 * the SAME run and from the SAME parse, so the edge function and the client
 * can never disagree about which exercise ids exist.
 *
 * EvoForge owns exercise identity; the model owns programming. This file is
 * how that rule reaches ai-plan.
 */

export interface CatalogueExercise {
  id: string;
  name: string;
  muscle: string;
}

/** The curated core — what the model is offered to choose from. */
export const PLAN_EXERCISES: readonly CatalogueExercise[] = [
  { id: 'ab_wheel_rollout', name: 'Ab Wheel Rollout', muscle: 'Abs' },
  { id: 'arnold_press', name: 'Arnold Press', muscle: 'Front Delts' },
  { id: 'assisted_pull_up', name: 'Assisted Pull-Up', muscle: 'Back Width' },
  { id: 'b_stance_hip_thrust', name: 'B-Stance Hip Thrust', muscle: 'Glutes' },
  { id: 'banded_glute_kickback', name: 'Banded Glute Kickback', muscle: 'Glutes' },
  { id: 'barbell_back_squat', name: 'Barbell Back Squat', muscle: 'Quads' },
  { id: 'barbell_bench_press', name: 'Barbell Bench Press', muscle: 'Chest' },
  { id: 'barbell_bent_over_row', name: 'Barbell Bent-Over Row', muscle: 'Back Thickness' },
  { id: 'barbell_curl', name: 'Barbell Curl', muscle: 'Biceps' },
  { id: 'barbell_deadlift', name: 'Barbell Deadlift', muscle: 'Erectors' },
  { id: 'barbell_floor_press', name: 'Barbell Floor Press', muscle: 'Chest' },
  { id: 'barbell_front_raise', name: 'Barbell Front Raise', muscle: 'Front Delts' },
  { id: 'barbell_hip_thrust', name: 'Barbell Hip Thrust', muscle: 'Glutes' },
  { id: 'barbell_landmine_row', name: 'Barbell Landmine Row', muscle: 'Back Thickness' },
  { id: 'barbell_shrug', name: 'Barbell Shrug', muscle: 'Traps' },
  { id: 'barbell_upright_row', name: 'Barbell Upright Row', muscle: 'Side Delts' },
  { id: 'barbell_wrist_curl', name: 'Barbell Wrist Curl', muscle: 'Forearms' },
  { id: 'behind_the_back_barbell_wrist_curl', name: 'Behind-the-Back Barbell Wrist Curl', muscle: 'Forearms' },
  { id: 'behind_the_back_cable_lateral_raise', name: 'Behind-the-Back Cable Lateral Raise', muscle: 'Side Delts' },
  { id: 'behind_the_neck_lat_pulldown', name: 'Behind-the-Neck Lat Pulldown', muscle: 'Back Width' },
  { id: 'bench_dip', name: 'Bench Dip', muscle: 'Triceps' },
  { id: 'bent_over_rear_delt_fly', name: 'Bent-Over Rear Delt Fly', muscle: 'Rear Delts' },
  { id: 'bulgarian_split_squat', name: 'Bulgarian Split Squat', muscle: 'Quads' },
  { id: 'cable_biceps_curl', name: 'Cable Biceps Curl', muscle: 'Biceps' },
  { id: 'cable_chest_fly', name: 'Cable Chest Fly', muscle: 'Chest' },
  { id: 'cable_crunch', name: 'Cable Crunch', muscle: 'Abs' },
  { id: 'cable_glute_kickback', name: 'Cable Glute Kickback', muscle: 'Glutes' },
  { id: 'cable_lat_pullover_straight_arm_pulldown', name: 'Cable Lat Pullover (Straight-Arm Pulldown)', muscle: 'Back Width' },
  { id: 'cable_lateral_raise', name: 'Cable Lateral Raise', muscle: 'Side Delts' },
  { id: 'cable_pallof_press', name: 'Cable Pallof Press', muscle: 'Abs' },
  { id: 'cable_rear_delt_fly', name: 'Cable Rear Delt Fly', muscle: 'Rear Delts' },
  { id: 'cable_rope_hammer_curl', name: 'Cable Rope Hammer Curl', muscle: 'Biceps' },
  { id: 'cable_shrug', name: 'Cable Shrug', muscle: 'Traps' },
  { id: 'cable_triceps_kickback', name: 'Cable Triceps Kickback', muscle: 'Triceps' },
  { id: 'cable_triceps_pushdown', name: 'Cable Triceps Pushdown', muscle: 'Triceps' },
  { id: 'cable_upright_row', name: 'Cable Upright Row', muscle: 'Side Delts' },
  { id: 'captains_chair_leg_raise', name: 'Captain\'s Chair Leg Raise', muscle: 'Abs' },
  { id: 'chest_supported_dumbbell_row', name: 'Chest-Supported Dumbbell Row', muscle: 'Back Thickness' },
  { id: 'chest_supported_machine_row', name: 'Chest-Supported Machine Row', muscle: 'Back Thickness' },
  { id: 'chest_supported_t_bar_row', name: 'Chest-Supported T-Bar Row', muscle: 'Back Thickness' },
  { id: 'close_grip_barbell_curl', name: 'Close-Grip Barbell Curl', muscle: 'Biceps' },
  { id: 'close_grip_bench_press', name: 'Close-Grip Bench Press', muscle: 'Triceps' },
  { id: 'close_grip_dumbbell_bench_press', name: 'Close-Grip Dumbbell Bench Press', muscle: 'Chest' },
  { id: 'close_grip_lat_pulldown', name: 'Close-Grip Lat Pulldown', muscle: 'Back Width' },
  { id: 'cross_body_cable_triceps_extension', name: 'Cross-Body Cable Triceps Extension', muscle: 'Triceps' },
  { id: 'cross_body_hammer_curl', name: 'Cross-Body Hammer Curl', muscle: 'Biceps' },
  { id: 'curtsy_lunge', name: 'Curtsy Lunge', muscle: 'Glutes' },
  { id: 'decline_barbell_bench_press', name: 'Decline Barbell Bench Press', muscle: 'Chest' },
  { id: 'decline_push_up', name: 'Decline Push-Up', muscle: 'Chest' },
  { id: 'decline_sit_up', name: 'Decline Sit-Up', muscle: 'Abs' },
  { id: 'deficit_push_up', name: 'Deficit Push-Up', muscle: 'Chest' },
  { id: 'donkey_calf_raise', name: 'Donkey Calf Raise', muscle: 'Calves' },
  { id: 'dumbbell_biceps_curl', name: 'Dumbbell Biceps Curl', muscle: 'Biceps' },
  { id: 'dumbbell_chest_fly', name: 'Dumbbell Chest Fly', muscle: 'Chest' },
  { id: 'dumbbell_flat_bench_press', name: 'Dumbbell Flat Bench Press', muscle: 'Chest' },
  { id: 'dumbbell_front_raise', name: 'Dumbbell Front Raise', muscle: 'Front Delts' },
  { id: 'dumbbell_hip_thrust', name: 'Dumbbell Hip Thrust', muscle: 'Glutes' },
  { id: 'dumbbell_lateral_raise', name: 'Dumbbell Lateral Raise', muscle: 'Side Delts' },
  { id: 'dumbbell_overhead_triceps_extension', name: 'Dumbbell Overhead Triceps Extension', muscle: 'Triceps' },
  { id: 'dumbbell_preacher_curl', name: 'Dumbbell Preacher Curl', muscle: 'Biceps' },
  { id: 'dumbbell_romanian_deadlift', name: 'Dumbbell Romanian Deadlift', muscle: 'Hamstrings' },
  { id: 'dumbbell_shrug', name: 'Dumbbell Shrug', muscle: 'Traps' },
  { id: 'dumbbell_skull_crusher', name: 'Dumbbell Skull Crusher', muscle: 'Triceps' },
  { id: 'dumbbell_standing_calf_raise', name: 'Dumbbell Standing Calf Raise', muscle: 'Calves' },
  { id: 'dumbbell_step_up', name: 'Dumbbell Step-Up', muscle: 'Quads' },
  { id: 'dumbbell_triceps_kickback', name: 'Dumbbell Triceps Kickback', muscle: 'Triceps' },
  { id: 'dumbbell_upright_row', name: 'Dumbbell Upright Row', muscle: 'Side Delts' },
  { id: 'dumbbell_wrist_curl', name: 'Dumbbell Wrist Curl', muscle: 'Forearms' },
  { id: 'ez_bar_curl', name: 'EZ-Bar Curl', muscle: 'Biceps' },
  { id: 'ez_bar_overhead_triceps_extension', name: 'EZ-Bar Overhead Triceps Extension', muscle: 'Triceps' },
  { id: 'face_pull', name: 'Face Pull', muscle: 'Rear Delts' },
  { id: 'farmer_carry', name: 'Farmer Carry', muscle: 'Forearms' },
  { id: 'front_squat', name: 'Front Squat', muscle: 'Quads' },
  { id: 'glute_bridge', name: 'Glute Bridge', muscle: 'Glutes' },
  { id: 'glute_ham_raise', name: 'Glute-Ham Raise', muscle: 'Hamstrings' },
  { id: 'goblet_squat', name: 'Goblet Squat', muscle: 'Quads' },
  { id: 'good_morning', name: 'Good Morning', muscle: 'Hamstrings' },
  { id: 'hack_squat_machine', name: 'Hack Squat Machine', muscle: 'Quads' },
  { id: 'hammer_curl', name: 'Hammer Curl', muscle: 'Biceps' },
  { id: 'hanging_knee_raise', name: 'Hanging Knee Raise', muscle: 'Abs' },
  { id: 'hanging_leg_raise', name: 'Hanging Leg Raise', muscle: 'Abs' },
  { id: 'high_to_low_cable_chest_fly', name: 'High-to-Low Cable Chest Fly', muscle: 'Chest' },
  { id: 'hip_abduction_machine', name: 'Hip Abduction Machine', muscle: 'Abductors' },
  { id: 'hip_adduction_machine', name: 'Hip Adduction Machine', muscle: 'Adductors' },
  { id: 'incline_barbell_bench_press', name: 'Incline Barbell Bench Press', muscle: 'Upper Chest' },
  { id: 'incline_cable_press', name: 'Incline Cable Press', muscle: 'Upper Chest' },
  { id: 'incline_dumbbell_bench_press', name: 'Incline Dumbbell Bench Press', muscle: 'Upper Chest' },
  { id: 'incline_dumbbell_curl', name: 'Incline Dumbbell Curl', muscle: 'Biceps' },
  { id: 'incline_machine_chest_press', name: 'Incline Machine Chest Press', muscle: 'Upper Chest' },
  { id: 'incline_smith_machine_bench_press', name: 'Incline Smith Machine Bench Press', muscle: 'Upper Chest' },
  { id: 'kneeling_cable_pulldown', name: 'Kneeling Cable Pulldown', muscle: 'Back Width' },
  { id: 'lat_pulldown', name: 'Lat Pulldown', muscle: 'Back Width' },
  { id: 'leaning_cable_lateral_raise', name: 'Leaning Cable Lateral Raise', muscle: 'Side Delts' },
  { id: 'leg_extension', name: 'Leg Extension', muscle: 'Quads' },
  { id: 'leg_press', name: 'Leg Press', muscle: 'Quads' },
  { id: 'leg_press_calf_raise', name: 'Leg Press Calf Raise', muscle: 'Calves' },
  { id: 'low_incline_dumbbell_bench_press', name: 'Low-Incline Dumbbell Bench Press', muscle: 'Upper Chest' },
  { id: 'low_to_high_incline_cable_fly', name: 'Low-to-High Incline Cable Fly', muscle: 'Upper Chest' },
  { id: 'lying_dumbbell_lateral_raise', name: 'Lying Dumbbell Lateral Raise', muscle: 'Side Delts' },
  { id: 'lying_leg_curl', name: 'Lying Leg Curl', muscle: 'Hamstrings' },
  { id: 'lying_leg_raise', name: 'Lying Leg Raise', muscle: 'Abs' },
  { id: 'machine_ab_crunch', name: 'Machine Ab Crunch', muscle: 'Abs' },
  { id: 'machine_assisted_chin_up', name: 'Machine-Assisted Chin-Up', muscle: 'Back Width' },
  { id: 'machine_biceps_curl', name: 'Machine Biceps Curl', muscle: 'Biceps' },
  { id: 'machine_chest_press', name: 'Machine Chest Press', muscle: 'Chest' },
  { id: 'machine_glute_kickback', name: 'Machine Glute Kickback', muscle: 'Glutes' },
  { id: 'machine_high_row', name: 'Machine High Row', muscle: 'Back Thickness' },
  { id: 'machine_hip_thrust', name: 'Machine Hip Thrust', muscle: 'Glutes' },
  { id: 'machine_lat_pulldown', name: 'Machine Lat Pulldown', muscle: 'Back Width' },
  { id: 'machine_lateral_raise', name: 'Machine Lateral Raise', muscle: 'Side Delts' },
  { id: 'machine_preacher_curl', name: 'Machine Preacher Curl', muscle: 'Biceps' },
  { id: 'machine_shoulder_press', name: 'Machine Shoulder Press', muscle: 'Front Delts' },
  { id: 'machine_triceps_extension', name: 'Machine Triceps Extension', muscle: 'Triceps' },
  { id: 'meadows_style_landmine_row', name: 'Meadows-Style Landmine Row', muscle: 'Back Thickness' },
  { id: 'neutral_grip_dumbbell_bench_press', name: 'Neutral-Grip Dumbbell Bench Press', muscle: 'Chest' },
  { id: 'neutral_grip_pulldown', name: 'Neutral-Grip Pulldown', muscle: 'Back Width' },
  { id: 'nordic_ham_curl', name: 'Nordic Ham Curl', muscle: 'Hamstrings' },
  { id: 'overhead_barbell_press', name: 'Overhead Barbell Press', muscle: 'Front Delts' },
  { id: 'overhead_cable_triceps_extension', name: 'Overhead Cable Triceps Extension', muscle: 'Triceps' },
  { id: 'pause_back_squat', name: 'Pause Back Squat', muscle: 'Quads' },
  { id: 'paused_barbell_bench_press', name: 'Paused Barbell Bench Press', muscle: 'Chest' },
  { id: 'pec_deck_machine_fly', name: 'Pec Deck Machine Fly', muscle: 'Chest' },
  { id: 'pendlay_row', name: 'Pendlay Row', muscle: 'Back Thickness' },
  { id: 'pendulum_squat', name: 'Pendulum Squat', muscle: 'Quads' },
  { id: 'plate_front_raise', name: 'Plate Front Raise', muscle: 'Front Delts' },
  { id: 'preacher_curl', name: 'Preacher Curl', muscle: 'Biceps' },
  { id: 'prone_incline_dumbbell_rear_delt_raise', name: 'Prone Incline Dumbbell Rear Delt Raise', muscle: 'Rear Delts' },
  { id: 'rack_pull', name: 'Rack Pull', muscle: 'Back Thickness' },
  { id: 'reverse_barbell_wrist_curl', name: 'Reverse Barbell Wrist Curl', muscle: 'Forearms' },
  { id: 'reverse_curl', name: 'Reverse Curl', muscle: 'Forearms' },
  { id: 'reverse_ez_bar_curl', name: 'Reverse EZ-Bar Curl', muscle: 'Forearms' },
  { id: 'reverse_grip_barbell_bench_press', name: 'Reverse-Grip Barbell Bench Press', muscle: 'Upper Chest' },
  { id: 'reverse_grip_cable_triceps_pushdown', name: 'Reverse-Grip Cable Triceps Pushdown', muscle: 'Triceps' },
  { id: 'reverse_grip_lat_pulldown', name: 'Reverse-Grip Lat Pulldown', muscle: 'Back Width' },
  { id: 'reverse_lunge', name: 'Reverse Lunge', muscle: 'Quads' },
  { id: 'reverse_pec_deck_rear_delt_fly', name: 'Reverse Pec Deck (Rear Delt Fly)', muscle: 'Rear Delts' },
  { id: 'romanian_deadlift', name: 'Romanian Deadlift', muscle: 'Hamstrings' },
  { id: 'rope_overhead_cable_triceps_extension', name: 'Rope Overhead Cable Triceps Extension', muscle: 'Triceps' },
  { id: 'rope_triceps_pushdown', name: 'Rope Triceps Pushdown', muscle: 'Triceps' },
  { id: 'seal_row', name: 'Seal Row', muscle: 'Back Thickness' },
  { id: 'seated_barbell_overhead_press', name: 'Seated Barbell Overhead Press', muscle: 'Front Delts' },
  { id: 'seated_bent_over_dumbbell_rear_delt_fly', name: 'Seated Bent-Over Dumbbell Rear Delt Fly', muscle: 'Rear Delts' },
  { id: 'seated_cable_row', name: 'Seated Cable Row', muscle: 'Back Thickness' },
  { id: 'seated_calf_raise', name: 'Seated Calf Raise', muscle: 'Calves' },
  { id: 'seated_dumbbell_concentration_curl', name: 'Seated Dumbbell Concentration Curl', muscle: 'Biceps' },
  { id: 'seated_dumbbell_hammer_curl', name: 'Seated Dumbbell Hammer Curl', muscle: 'Biceps' },
  { id: 'seated_dumbbell_lateral_raise', name: 'Seated Dumbbell Lateral Raise', muscle: 'Side Delts' },
  { id: 'seated_dumbbell_shoulder_press', name: 'Seated Dumbbell Shoulder Press', muscle: 'Front Delts' },
  { id: 'seated_leg_curl', name: 'Seated Leg Curl', muscle: 'Hamstrings' },
  { id: 'seated_lying_leg_curl', name: 'Seated/Lying Leg Curl', muscle: 'Hamstrings' },
  { id: 'single_arm_cable_biceps_curl', name: 'Single-Arm Cable Biceps Curl', muscle: 'Biceps' },
  { id: 'single_arm_cable_chest_fly', name: 'Single-Arm Cable Chest Fly', muscle: 'Chest' },
  { id: 'single_arm_cable_rear_delt_fly', name: 'Single-Arm Cable Rear Delt Fly', muscle: 'Rear Delts' },
  { id: 'single_arm_cable_row', name: 'Single-Arm Cable Row', muscle: 'Back Thickness' },
  { id: 'single_arm_cable_triceps_pushdown', name: 'Single-Arm Cable Triceps Pushdown', muscle: 'Triceps' },
  { id: 'single_arm_dumbbell_lateral_raise', name: 'Single-Arm Dumbbell Lateral Raise', muscle: 'Side Delts' },
  { id: 'single_arm_dumbbell_overhead_triceps_extension', name: 'Single-Arm Dumbbell Overhead Triceps Extension', muscle: 'Triceps' },
  { id: 'single_arm_dumbbell_row', name: 'Single-Arm Dumbbell Row', muscle: 'Back Thickness' },
  { id: 'single_arm_dumbbell_shoulder_press', name: 'Single-Arm Dumbbell Shoulder Press', muscle: 'Front Delts' },
  { id: 'single_arm_landmine_press', name: 'Single-Arm Landmine Press', muscle: 'Front Delts' },
  { id: 'single_arm_lat_pulldown', name: 'Single-Arm Lat Pulldown', muscle: 'Back Width' },
  { id: 'single_leg_hip_thrust', name: 'Single-Leg Hip Thrust', muscle: 'Glutes' },
  { id: 'single_leg_leg_press', name: 'Single-Leg Leg Press', muscle: 'Quads' },
  { id: 'single_leg_lying_leg_curl', name: 'Single-Leg Lying Leg Curl', muscle: 'Hamstrings' },
  { id: 'single_leg_romanian_deadlift', name: 'Single-Leg Romanian Deadlift', muscle: 'Hamstrings' },
  { id: 'single_leg_standing_calf_raise', name: 'Single-Leg Standing Calf Raise', muscle: 'Calves' },
  { id: 'sissy_squat', name: 'Sissy Squat', muscle: 'Quads' },
  { id: 'skull_crusher_lying_triceps_extension', name: 'Skull Crusher (Lying Triceps Extension)', muscle: 'Triceps' },
  { id: 'smith_machine_bench_press', name: 'Smith Machine Bench Press', muscle: 'Chest' },
  { id: 'smith_machine_calf_raise', name: 'Smith Machine Calf Raise', muscle: 'Calves' },
  { id: 'smith_machine_shoulder_press', name: 'Smith Machine Shoulder Press', muscle: 'Front Delts' },
  { id: 'smith_machine_shrug', name: 'Smith Machine Shrug', muscle: 'Traps' },
  { id: 'smith_machine_squat', name: 'Smith Machine Squat', muscle: 'Quads' },
  { id: 'snatch_grip_barbell_shrug', name: 'Snatch-Grip Barbell Shrug', muscle: 'Traps' },
  { id: 'spider_curl', name: 'Spider Curl', muscle: 'Biceps' },
  { id: 'standing_calf_raise', name: 'Standing Calf Raise', muscle: 'Calves' },
  { id: 'standing_dumbbell_shoulder_press', name: 'Standing Dumbbell Shoulder Press', muscle: 'Front Delts' },
  { id: 'standing_low_to_high_cable_chest_fly', name: 'Standing Low-to-High Cable Chest Fly', muscle: 'Chest' },
  { id: 'stiff_leg_deadlift', name: 'Stiff-Leg Deadlift', muscle: 'Hamstrings' },
  { id: 'straight_bar_cable_triceps_pushdown', name: 'Straight-Bar Cable Triceps Pushdown', muscle: 'Triceps' },
  { id: 't_bar_row', name: 'T-Bar Row', muscle: 'Back Thickness' },
  { id: 'toes_to_bar', name: 'Toes-to-Bar', muscle: 'Abs' },
  { id: 'trap_bar_shrug', name: 'Trap Bar Shrug', muscle: 'Traps' },
  { id: 'v_bar_cable_triceps_pushdown', name: 'V-Bar Cable Triceps Pushdown', muscle: 'Triceps' },
  { id: 'walking_lunge', name: 'Walking Lunge', muscle: 'Quads' },
  { id: 'weighted_bicycle_crunch', name: 'Weighted Bicycle Crunch', muscle: 'Abs' },
  { id: 'weighted_chest_dip', name: 'Weighted Chest Dip', muscle: 'Chest' },
  { id: 'weighted_decline_crunch', name: 'Weighted Decline Crunch', muscle: 'Abs' },
  { id: 'weighted_plank', name: 'Weighted Plank', muscle: 'Abs' },
  { id: 'weighted_pull_up', name: 'Weighted Pull-Up', muscle: 'Back Width' },
  { id: 'weighted_sit_up', name: 'Weighted Sit-Up', muscle: 'Abs' },
  { id: 'weighted_triceps_dip', name: 'Weighted Triceps Dip', muscle: 'Triceps' },
  { id: 'wide_grip_barbell_curl', name: 'Wide-Grip Barbell Curl', muscle: 'Biceps' },
  { id: 'yates_row', name: 'Yates Row', muscle: 'Back Thickness' },
  { id: 'zercher_squat', name: 'Zercher Squat', muscle: 'Quads' },
];

/** Every id in the full library, for validating an out-of-core choice. */
export const EXERCISE_IDS: ReadonlySet<string> = new Set([
  '3_4_sit_up',
  '90_90_hamstring',
  'ab_crunch_machine',
  'ab_roller',
  'ab_wheel_rollout',
  'adductor',
  'adductor_groin',
  'advanced_kettlebell_windmill',
  'air_bike',
  'all_fours_quad_stretch',
  'alternate_hammer_curl',
  'alternate_heel_touchers',
  'alternate_incline_dumbbell_curl',
  'alternate_leg_diagonal_bound',
  'alternating_cable_shoulder_press',
  'alternating_deltoid_raise',
  'alternating_floor_press',
  'alternating_hang_clean',
  'alternating_kettlebell_press',
  'alternating_kettlebell_row',
  'alternating_renegade_row',
  'ankle_circles',
  'ankle_on_the_knee',
  'anterior_tibialis_smr',
  'anti_gravity_press',
  'archer_pull_up',
  'arm_circles',
  'arnold_dumbbell_press',
  'arnold_press',
  'around_the_worlds',
  'assisted_pull_up',
  'atlas_stone_trainer',
  'atlas_stones',
  'axle_deadlift',
  'b_stance_hip_thrust',
  'back_flyes_with_bands',
  'backward_drag',
  'backward_medicine_ball_throw',
  'balance_board',
  'ball_leg_curl',
  'band_assisted_pull_up',
  'band_good_morning',
  'band_good_morning_pull_through',
  'band_hip_adductions',
  'band_pull_apart',
  'band_skull_crusher',
  'banded_glute_kickback',
  'banded_lateral_walk',
  'banded_push_up',
  'barbell_ab_rollout',
  'barbell_ab_rollout_on_knees',
  'barbell_back_squat',
  'barbell_bench_press',
  'barbell_bench_press_medium_grip',
  'barbell_bent_over_row',
  'barbell_curl',
  'barbell_curls_lying_against_an_incline',
  'barbell_deadlift',
  'barbell_floor_press',
  'barbell_front_raise',
  'barbell_full_squat',
  'barbell_glute_bridge',
  'barbell_guillotine_bench_press',
  'barbell_hack_squat',
  'barbell_hip_thrust',
  'barbell_incline_bench_press_medium_grip',
  'barbell_incline_shoulder_raise',
  'barbell_landmine_row',
  'barbell_lunge',
  'barbell_rear_delt_row',
  'barbell_rollout_from_bench',
  'barbell_seated_calf_raise',
  'barbell_shoulder_press',
  'barbell_shrug',
  'barbell_shrug_behind_the_back',
  'barbell_side_bend',
  'barbell_side_split_squat',
  'barbell_squat',
  'barbell_squat_to_a_bench',
  'barbell_step_ups',
  'barbell_upright_row',
  'barbell_walking_lunge',
  'barbell_wrist_curl',
  'battling_ropes',
  'bayesian_cable_curl',
  'bear_crawl',
  'bear_crawl_sled_drags',
  'behind_head_chest_stretch',
  'behind_the_back_barbell_wrist_curl',
  'behind_the_back_cable_lateral_raise',
  'behind_the_neck_lat_pulldown',
  'belt_squat',
  'bench_dip',
  'bench_dips',
  'bench_jump',
  'bench_press_powerlifting',
  'bench_press_with_bands',
  'bench_press_with_chains',
  'bench_sprint',
  'bent_arm_barbell_pullover',
  'bent_arm_dumbbell_pullover',
  'bent_knee_hip_raise',
  'bent_over_barbell_row',
  'bent_over_dumbbell_rear_delt_raise_with_head_on_bench',
  'bent_over_low_pulley_side_lateral',
  'bent_over_one_arm_long_bar_row',
  'bent_over_rear_delt_fly',
  'bent_over_two_arm_long_bar_row',
  'bent_over_two_dumbbell_row',
  'bent_over_two_dumbbell_row_with_palms_in',
  'bent_press',
  'bicycling',
  'bicycling_stationary',
  'board_press',
  'body_tricep_press',
  'body_up',
  'bodyweight_flyes',
  'bodyweight_mid_row',
  'bodyweight_squat',
  'bodyweight_walking_lunge',
  'bosu_ball_cable_crunch_with_side_bends',
  'bottoms_up',
  'bottoms_up_clean_from_the_hang_position',
  'box_jump',
  'box_jump_multiple_response',
  'box_skip',
  'box_squat',
  'box_squat_with_bands',
  'box_squat_with_chains',
  'brachialis_smr',
  'bradford_rocky_presses',
  'broad_jump',
  'bulgarian_split_squat',
  'butt_lift_bridge',
  'butt_ups',
  'butterfly',
  'cable_biceps_curl',
  'cable_chest_fly',
  'cable_chest_press',
  'cable_crossover',
  'cable_crunch',
  'cable_deadlifts',
  'cable_front_raise',
  'cable_glute_kickback',
  'cable_hammer_curls_rope_attachment',
  'cable_hip_adduction',
  'cable_incline_pushdown',
  'cable_incline_triceps_extension',
  'cable_internal_rotation',
  'cable_iron_cross',
  'cable_judo_flip',
  'cable_lat_pullover_straight_arm_pulldown',
  'cable_lateral_raise',
  'cable_lying_triceps_extension',
  'cable_one_arm_tricep_extension',
  'cable_overhead_triceps_extension',
  'cable_pallof_press',
  'cable_preacher_curl',
  'cable_pull_through',
  'cable_rear_delt_fly',
  'cable_reverse_crunch',
  'cable_rope_hammer_curl',
  'cable_rope_overhead_triceps_extension',
  'cable_rope_rear_delt_rows',
  'cable_russian_twists',
  'cable_seated_crunch',
  'cable_seated_lateral_raise',
  'cable_shoulder_press',
  'cable_shrug',
  'cable_shrugs',
  'cable_triceps_kickback',
  'cable_triceps_pushdown',
  'cable_upright_row',
  'cable_woodchopper',
  'cable_wrist_curl',
  'cable_y_raise',
  'calf_machine_shoulder_shrug',
  'calf_press',
  'calf_press_on_the_leg_press_machine',
  'calf_raise_on_a_dumbbell',
  'calf_raises_with_bands',
  'calf_stretch_elbows_against_wall',
  'calf_stretch_hands_against_wall',
  'calves_smr',
  'captains_chair_leg_raise',
  'car_deadlift',
  'car_drivers',
  'carioca_quick_step',
  'cat_stretch',
  'catch_and_overhead_throw',
  'chain_handle_extension',
  'chain_press',
  'chair_leg_extended_stretch',
  'chair_lower_back_stretch',
  'chair_squat',
  'chair_upper_body_stretch',
  'chest_and_front_of_shoulder_stretch',
  'chest_push_from_3_point_stance',
  'chest_push_multiple_response',
  'chest_push_single_response',
  'chest_push_with_run_release',
  'chest_stretch_on_stability_ball',
  'chest_supported_dumbbell_row',
  'chest_supported_machine_row',
  'chest_supported_t_bar_row',
  'childs_pose',
  'chin_to_chest_stretch',
  'chin_up',
  'circus_bell',
  'clean',
  'clean_and_jerk',
  'clean_and_press',
  'clean_deadlift',
  'clean_from_blocks',
  'clean_pull',
  'clean_shrug',
  'clock_push_up',
  'close_grip_barbell_bench_press',
  'close_grip_barbell_curl',
  'close_grip_bench_press',
  'close_grip_dumbbell_bench_press',
  'close_grip_dumbbell_press',
  'close_grip_ez_bar_curl',
  'close_grip_ez_bar_curl_with_band',
  'close_grip_ez_bar_press',
  'close_grip_front_lat_pulldown',
  'close_grip_lat_pulldown',
  'close_grip_push_up_off_of_a_dumbbell',
  'close_grip_standing_barbell_curl',
  'cocoons',
  'conans_wheel',
  'concentration_curls',
  'copenhagen_plank',
  'cross_body_cable_triceps_extension',
  'cross_body_crunch',
  'cross_body_hammer_curl',
  'cross_over_with_bands',
  'crossover_reverse_lunge',
  'crucifix',
  'crunch_hands_overhead',
  'crunch_legs_on_exercise_ball',
  'crunches',
  'cuban_press',
  'curtsy_lunge',
  'cyclist_squat',
  'dancers_stretch',
  'dead_bug',
  'deadlift_with_bands',
  'deadlift_with_chains',
  'decline_barbell_bench_press',
  'decline_close_grip_bench_to_skull_crusher',
  'decline_crunch',
  'decline_dumbbell_bench_press',
  'decline_dumbbell_flyes',
  'decline_dumbbell_press',
  'decline_dumbbell_triceps_extension',
  'decline_ez_bar_triceps_extension',
  'decline_oblique_crunch',
  'decline_push_up',
  'decline_reverse_crunch',
  'decline_sit_up',
  'decline_smith_press',
  'deficit_deadlift',
  'deficit_push_up',
  'depth_jump_leap',
  'diamond_push_up',
  'dip_machine',
  'dips_chest_version',
  'dips_triceps_version',
  'donkey_calf_raise',
  'donkey_calf_raises',
  'double_kettlebell_alternating_hang_clean',
  'double_kettlebell_jerk',
  'double_kettlebell_push_press',
  'double_kettlebell_snatch',
  'double_kettlebell_windmill',
  'double_leg_butt_kick',
  'downward_facing_balance',
  'drag_curl',
  'dragon_flag',
  'drop_push',
  'dumbbell_alternate_bicep_curl',
  'dumbbell_bench_press',
  'dumbbell_bench_press_with_neutral_grip',
  'dumbbell_bicep_curl',
  'dumbbell_biceps_curl',
  'dumbbell_chest_fly',
  'dumbbell_clean',
  'dumbbell_flat_bench_press',
  'dumbbell_floor_press',
  'dumbbell_flyes',
  'dumbbell_front_raise',
  'dumbbell_hip_thrust',
  'dumbbell_incline_row',
  'dumbbell_incline_shoulder_raise',
  'dumbbell_lateral_raise',
  'dumbbell_lunges',
  'dumbbell_lying_one_arm_rear_lateral_raise',
  'dumbbell_lying_pronation',
  'dumbbell_lying_rear_lateral_raise',
  'dumbbell_lying_supination',
  'dumbbell_one_arm_shoulder_press',
  'dumbbell_one_arm_triceps_extension',
  'dumbbell_one_arm_upright_row',
  'dumbbell_overhead_triceps_extension',
  'dumbbell_preacher_curl',
  'dumbbell_prone_incline_curl',
  'dumbbell_raise',
  'dumbbell_rear_lunge',
  'dumbbell_romanian_deadlift',
  'dumbbell_scaption',
  'dumbbell_seated_box_jump',
  'dumbbell_seated_one_leg_calf_raise',
  'dumbbell_shoulder_press',
  'dumbbell_shrug',
  'dumbbell_side_bend',
  'dumbbell_skull_crusher',
  'dumbbell_squat',
  'dumbbell_squat_to_a_bench',
  'dumbbell_standing_calf_raise',
  'dumbbell_step_up',
  'dumbbell_step_ups',
  'dumbbell_tricep_extension_pronated_grip',
  'dumbbell_triceps_kickback',
  'dumbbell_upright_row',
  'dumbbell_wrist_curl',
  'dynamic_back_stretch',
  'dynamic_chest_stretch',
  'elbow_circles',
  'elbow_to_knee',
  'elbows_back',
  'elevated_back_lunge',
  'elevated_cable_rows',
  'elliptical_trainer',
  'exercise_ball_crunch',
  'exercise_ball_pull_in',
  'extended_range_one_arm_kettlebell_floor_press',
  'external_rotation',
  'external_rotation_with_band',
  'external_rotation_with_cable',
  'ez_bar_curl',
  'ez_bar_overhead_triceps_extension',
  'ez_bar_skullcrusher',
  'face_pull',
  'farmer_carry',
  'farmers_walk',
  'fast_skipping',
  'finger_curls',
  'flat_bench_cable_flyes',
  'flat_bench_leg_pull_in',
  'flat_bench_lying_leg_raise',
  'flexor_incline_dumbbell_curls',
  'floor_glute_ham_raise',
  'floor_press',
  'floor_press_with_chains',
  'flutter_kicks',
  'foot_smr',
  'forward_drag_with_press',
  'frankenstein_squat',
  'freehand_jump_squat',
  'frog_hops',
  'frog_pump',
  'frog_sit_ups',
  'front_barbell_squat',
  'front_barbell_squat_to_a_bench',
  'front_box_jump',
  'front_cable_raise',
  'front_cone_hops_or_hurdle_hops',
  'front_dumbbell_raise',
  'front_incline_dumbbell_raise',
  'front_leg_raises',
  'front_plate_raise',
  'front_raise_and_pullover',
  'front_squat',
  'front_squat_clean_grip',
  'front_squats_with_two_kettlebells',
  'front_two_dumbbell_raise',
  'full_range_of_motion_lat_pulldown',
  'gironda_sternum_chins',
  'glute_bridge',
  'glute_ham_raise',
  'glute_kickback',
  'goblet_squat',
  'good_morning',
  'good_morning_off_pins',
  'gorilla_chin_crunch',
  'groin_and_back_stretch',
  'groiners',
  'hack_squat',
  'hack_squat_machine',
  'hammer_curl',
  'hammer_curls',
  'hammer_grip_incline_db_bench_press',
  'hamstring_smr',
  'hamstring_stretch',
  'handstand_push_up',
  'handstand_push_ups',
  'hang_clean',
  'hang_clean_below_the_knees',
  'hang_snatch',
  'hang_snatch_below_knees',
  'hanging_bar_good_morning',
  'hanging_knee_raise',
  'hanging_leg_raise',
  'hanging_pike',
  'heaving_snatch_balance',
  'heavy_bag_thrust',
  'high_cable_curls',
  'high_to_low_cable_chest_fly',
  'hip_abduction_machine',
  'hip_adduction_machine',
  'hip_circles_prone',
  'hip_extension_with_bands',
  'hip_flexion_with_band',
  'hip_lift_with_band',
  'hug_a_ball',
  'hug_knees_to_chest',
  'hurdle_hops',
  'hyperextensions_back_extensions',
  'hyperextensions_with_no_hyperextension_bench',
  'iliotibial_tract_smr',
  'inchworm',
  'incline_barbell_bench_press',
  'incline_barbell_triceps_extension',
  'incline_bench_pull',
  'incline_cable_chest_press',
  'incline_cable_flye',
  'incline_cable_press',
  'incline_dumbbell_bench_press',
  'incline_dumbbell_bench_with_palms_facing_in',
  'incline_dumbbell_curl',
  'incline_dumbbell_flyes',
  'incline_dumbbell_flyes_with_a_twist',
  'incline_dumbbell_press',
  'incline_hammer_curls',
  'incline_inner_biceps_curl',
  'incline_machine_chest_press',
  'incline_push_up',
  'incline_push_up_close_grip',
  'incline_push_up_depth_jump',
  'incline_push_up_medium',
  'incline_push_up_reverse_grip',
  'incline_push_up_wide',
  'incline_smith_machine_bench_press',
  'intermediate_groin_stretch',
  'intermediate_hip_flexor_and_quad_stretch',
  'internal_rotation_with_band',
  'inverted_row',
  'inverted_row_with_straps',
  'iron_cross',
  'iron_crosses_stretch',
  'isometric_chest_squeezes',
  'isometric_neck_exercise_front_and_back',
  'isometric_neck_exercise_sides',
  'isometric_wipers',
  'it_band_and_glute_stretch',
  'jackknife_sit_up',
  'janda_sit_up',
  'jefferson_curl',
  'jefferson_squats',
  'jerk_balance',
  'jerk_dip_squat',
  'jm_press',
  'jogging_treadmill',
  'keg_load',
  'kettlebell_arnold_press',
  'kettlebell_clean_and_press',
  'kettlebell_dead_clean',
  'kettlebell_figure_8',
  'kettlebell_goblet_lunge',
  'kettlebell_hang_clean',
  'kettlebell_high_pull',
  'kettlebell_one_legged_deadlift',
  'kettlebell_overhead_press',
  'kettlebell_pass_between_the_legs',
  'kettlebell_pirate_ships',
  'kettlebell_pistol_squat',
  'kettlebell_row',
  'kettlebell_seated_press',
  'kettlebell_seesaw_press',
  'kettlebell_single_leg_rdl',
  'kettlebell_sumo_high_pull',
  'kettlebell_swing',
  'kettlebell_thruster',
  'kettlebell_turkish_get_up',
  'kettlebell_turkish_get_up_lunge_style',
  'kettlebell_turkish_get_up_squat_style',
  'kettlebell_windmill',
  'kipping_muscle_up',
  'knee_across_the_body',
  'knee_circles',
  'knee_hip_raise_on_parallel_bars',
  'knee_tuck_jump',
  'kneeling_arm_drill',
  'kneeling_cable_crunch_with_alternating_oblique_twists',
  'kneeling_cable_pulldown',
  'kneeling_cable_triceps_extension',
  'kneeling_forearm_stretch',
  'kneeling_high_pulley_row',
  'kneeling_hip_flexor',
  'kneeling_jump_squat',
  'kneeling_single_arm_high_pulley_row',
  'kneeling_squat',
  'landmine_180s',
  'landmine_linear_jammer',
  'landmine_press',
  'landmine_rotation',
  'landmine_row',
  'landmine_squat',
  'lat_pulldown',
  'lateral_bound',
  'lateral_box_jump',
  'lateral_cone_hops',
  'lateral_raise_with_bands',
  'latissimus_dorsi_smr',
  'leaning_cable_lateral_raise',
  'leg_extension',
  'leg_extensions',
  'leg_lift',
  'leg_over_floor_press',
  'leg_press',
  'leg_press_calf_raise',
  'leg_pull_in',
  'leg_up_hamstring_stretch',
  'leverage_chest_press',
  'leverage_deadlift',
  'leverage_decline_chest_press',
  'leverage_high_row',
  'leverage_incline_chest_press',
  'leverage_iso_row',
  'leverage_shoulder_press',
  'leverage_shrug',
  'linear_3_part_start_technique',
  'linear_acceleration_wall_drill',
  'linear_depth_jump',
  'log_lift',
  'london_bridges',
  'looking_at_ceiling',
  'low_cable_crossover',
  'low_cable_triceps_extension',
  'low_incline_dumbbell_bench_press',
  'low_pulley_row_to_neck',
  'low_to_high_incline_cable_fly',
  'lower_back_curl',
  'lower_back_smr',
  'lunge_pass_through',
  'lunge_sprint',
  'lying_bent_leg_groin',
  'lying_cable_curl',
  'lying_cambered_barbell_row',
  'lying_close_grip_bar_curl_on_high_pulley',
  'lying_close_grip_barbell_triceps_extension_behind_the_head',
  'lying_close_grip_barbell_triceps_press_to_chin',
  'lying_crossover',
  'lying_dumbbell_lateral_raise',
  'lying_dumbbell_tricep_extension',
  'lying_face_down_plate_neck_resistance',
  'lying_face_up_plate_neck_resistance',
  'lying_glute',
  'lying_hamstring',
  'lying_high_bench_barbell_curl',
  'lying_leg_curl',
  'lying_leg_curls',
  'lying_leg_raise',
  'lying_machine_squat',
  'lying_one_arm_lateral_raise',
  'lying_prone_quadriceps',
  'lying_rear_delt_raise',
  'lying_supine_dumbbell_curl',
  'lying_t_bar_row',
  'lying_triceps_press',
  'machine_ab_crunch',
  'machine_assisted_chin_up',
  'machine_bench_press',
  'machine_bicep_curl',
  'machine_biceps_curl',
  'machine_chest_press',
  'machine_glute_kickback',
  'machine_high_row',
  'machine_hip_thrust',
  'machine_lat_pulldown',
  'machine_lateral_raise',
  'machine_preacher_curl',
  'machine_preacher_curls',
  'machine_pullover',
  'machine_rear_delt_row',
  'machine_shoulder_military_press',
  'machine_shoulder_press',
  'machine_standing_calf_raise',
  'machine_triceps_extension',
  'meadows_row',
  'meadows_style_landmine_row',
  'medicine_ball_chest_pass',
  'medicine_ball_full_twist',
  'medicine_ball_scoop_throw',
  'middle_back_shrug',
  'middle_back_stretch',
  'mixed_grip_chin',
  'monster_walk',
  'mountain_climbers',
  'moving_claw_series',
  'muscle_snatch',
  'muscle_up',
  'narrow_stance_hack_squats',
  'narrow_stance_leg_press',
  'narrow_stance_squats',
  'natural_glute_ham_raise',
  'neck_press',
  'neck_smr',
  'neutral_grip_dumbbell_bench_press',
  'neutral_grip_pulldown',
  'nordic_ham_curl',
  'nordic_hamstring_curl',
  'oblique_crunches',
  'oblique_crunches_on_the_floor',
  'olympic_squat',
  'on_your_back_quad_stretch',
  'on_your_side_quad_stretch',
  'one_arm_against_wall',
  'one_arm_chin_up',
  'one_arm_dumbbell_bench_press',
  'one_arm_dumbbell_preacher_curl',
  'one_arm_dumbbell_row',
  'one_arm_flat_bench_dumbbell_flye',
  'one_arm_floor_press',
  'one_arm_high_pulley_cable_side_bends',
  'one_arm_incline_lateral_raise',
  'one_arm_kettlebell_clean',
  'one_arm_kettlebell_clean_and_jerk',
  'one_arm_kettlebell_floor_press',
  'one_arm_kettlebell_jerk',
  'one_arm_kettlebell_military_press_to_the_side',
  'one_arm_kettlebell_para_press',
  'one_arm_kettlebell_push_press',
  'one_arm_kettlebell_row',
  'one_arm_kettlebell_snatch',
  'one_arm_kettlebell_split_jerk',
  'one_arm_kettlebell_split_snatch',
  'one_arm_kettlebell_swings',
  'one_arm_lat_pulldown',
  'one_arm_long_bar_row',
  'one_arm_medicine_ball_slam',
  'one_arm_open_palm_kettlebell_clean',
  'one_arm_overhead_kettlebell_squats',
  'one_arm_pronated_dumbbell_triceps_extension',
  'one_arm_side_deadlift',
  'one_arm_side_laterals',
  'one_arm_supinated_dumbbell_triceps_extension',
  'one_half_locust',
  'one_handed_hang',
  'one_knee_to_chest',
  'one_leg_barbell_squat',
  'one_legged_cable_kickback',
  'open_palm_kettlebell_clean',
  'otis_up',
  'overhead_barbell_press',
  'overhead_cable_curl',
  'overhead_cable_triceps_extension',
  'overhead_lat',
  'overhead_slam',
  'overhead_squat',
  'overhead_stretch',
  'overhead_triceps',
  'pallof_press',
  'pallof_press_with_rotation',
  'palms_down_dumbbell_wrist_curl_over_a_bench',
  'palms_down_wrist_curl_over_a_bench',
  'palms_up_barbell_wrist_curl_over_a_bench',
  'palms_up_dumbbell_wrist_curl_over_a_bench',
  'parallel_bar_dip',
  'pause_back_squat',
  'paused_barbell_bench_press',
  'pec_deck_machine_fly',
  'pelvic_tilt_into_bridge',
  'pendlay_row',
  'pendulum_squat',
  'peroneals_smr',
  'peroneals_stretch',
  'physioball_hip_bridge',
  'pin_presses',
  'piriformis_smr',
  'plank',
  'plate_front_raise',
  'plate_pinch',
  'plate_pinch_hold',
  'plate_squeeze_press',
  'plate_twist',
  'platform_hamstring_slides',
  'plie_dumbbell_squat',
  'plyo_kettlebell_pushups',
  'plyo_push_up',
  'posterior_tibialis_stretch',
  'power_clean',
  'power_clean_from_blocks',
  'power_jerk',
  'power_partials',
  'power_snatch',
  'power_snatch_from_blocks',
  'power_stairs',
  'preacher_curl',
  'preacher_hammer_dumbbell_curl',
  'press_sit_up',
  'prone_incline_dumbbell_rear_delt_raise',
  'prone_manual_hamstring',
  'prowler_sprint',
  'pull_through',
  'pullups',
  'push_press',
  'push_press_behind_the_neck',
  'push_up_to_side_plank',
  'push_up_wide',
  'push_ups_close_triceps_position',
  'push_ups_with_feet_elevated',
  'push_ups_with_feet_on_an_exercise_ball',
  'pushups',
  'pushups_close_and_wide_hand_positions',
  'pyramid',
  'quad_stretch',
  'quadriceps_smr',
  'quick_leap',
  'rack_delivery',
  'rack_pull',
  'rack_pull_with_bands',
  'rack_pulls',
  'rear_leg_raises',
  'recumbent_bike',
  'return_push_from_stance',
  'reverse_band_bench_press',
  'reverse_band_box_squat',
  'reverse_band_deadlift',
  'reverse_band_power_squat',
  'reverse_band_sumo_deadlift',
  'reverse_barbell_curl',
  'reverse_barbell_preacher_curls',
  'reverse_barbell_wrist_curl',
  'reverse_cable_curl',
  'reverse_crunch',
  'reverse_curl',
  'reverse_ez_bar_curl',
  'reverse_flyes',
  'reverse_flyes_with_external_rotation',
  'reverse_grip_barbell_bench_press',
  'reverse_grip_bent_over_rows',
  'reverse_grip_cable_curl',
  'reverse_grip_cable_triceps_pushdown',
  'reverse_grip_lat_pulldown',
  'reverse_grip_triceps_pushdown',
  'reverse_hyperextension',
  'reverse_lunge',
  'reverse_machine_flyes',
  'reverse_pec_deck_rear_delt_fly',
  'reverse_plate_curls',
  'reverse_triceps_bench_press',
  'rhomboids_smr',
  'rickshaw_carry',
  'rickshaw_deadlift',
  'ring_dips',
  'ring_push_up',
  'rocket_jump',
  'rocking_standing_calf_raise',
  'rocky_pull_ups_pulldowns',
  'romanian_deadlift',
  'romanian_deadlift_from_deficit',
  'rope_climb',
  'rope_crunch',
  'rope_jumping',
  'rope_overhead_cable_triceps_extension',
  'rope_straight_arm_pulldown',
  'rope_triceps_pushdown',
  'round_the_world_shoulder_stretch',
  'rowing_stationary',
  'runners_stretch',
  'running_treadmill',
  'russian_twist',
  'sandbag_load',
  'scapular_pull_up',
  'scissor_kick',
  'scissors_jump',
  'seal_row',
  'seated_band_hamstring_curl',
  'seated_barbell_military_press',
  'seated_barbell_overhead_press',
  'seated_barbell_twist',
  'seated_bent_over_dumbbell_rear_delt_fly',
  'seated_bent_over_one_arm_dumbbell_triceps_extension',
  'seated_bent_over_rear_delt_raise',
  'seated_bent_over_two_arm_dumbbell_triceps_extension',
  'seated_biceps',
  'seated_cable_row',
  'seated_cable_rows',
  'seated_cable_shoulder_press',
  'seated_calf_raise',
  'seated_calf_stretch',
  'seated_close_grip_concentration_barbell_curl',
  'seated_dumbbell_concentration_curl',
  'seated_dumbbell_curl',
  'seated_dumbbell_hammer_curl',
  'seated_dumbbell_inner_biceps_curl',
  'seated_dumbbell_lateral_raise',
  'seated_dumbbell_palms_down_wrist_curl',
  'seated_dumbbell_palms_up_wrist_curl',
  'seated_dumbbell_press',
  'seated_dumbbell_shoulder_press',
  'seated_flat_bench_leg_pull_in',
  'seated_floor_hamstring_stretch',
  'seated_front_deltoid',
  'seated_glute',
  'seated_good_mornings',
  'seated_hamstring',
  'seated_hamstring_and_calf_stretch',
  'seated_head_harness_neck_resistance',
  'seated_leg_curl',
  'seated_leg_tucks',
  'seated_lying_leg_curl',
  'seated_one_arm_cable_pulley_rows',
  'seated_one_arm_dumbbell_palms_down_wrist_curl',
  'seated_one_arm_dumbbell_palms_up_wrist_curl',
  'seated_overhead_stretch',
  'seated_palm_up_barbell_wrist_curl',
  'seated_palms_down_barbell_wrist_curl',
  'seated_side_lateral_raise',
  'seated_triceps_press',
  'seated_two_arm_palms_up_low_pulley_wrist_curl',
  'see_saw_press_alternating_side_press',
  'shotgun_row',
  'shoulder_circles',
  'shoulder_press_with_bands',
  'shoulder_raise',
  'shoulder_stretch',
  'side_bridge',
  'side_hop_sprint',
  'side_jackknife',
  'side_lateral_raise',
  'side_laterals_to_front_raise',
  'side_leg_raises',
  'side_lying_floor_stretch',
  'side_lying_groin_stretch',
  'side_neck_stretch',
  'side_standing_long_jump',
  'side_to_side_box_shuffle',
  'side_to_side_chins',
  'side_wrist_pull',
  'single_arm_cable_biceps_curl',
  'single_arm_cable_chest_fly',
  'single_arm_cable_crossover',
  'single_arm_cable_fly',
  'single_arm_cable_rear_delt_fly',
  'single_arm_cable_row',
  'single_arm_cable_triceps_pushdown',
  'single_arm_dumbbell_lateral_raise',
  'single_arm_dumbbell_overhead_triceps_extension',
  'single_arm_dumbbell_row',
  'single_arm_dumbbell_shoulder_press',
  'single_arm_landmine_press',
  'single_arm_lat_pulldown',
  'single_arm_linear_jammer',
  'single_arm_push_up',
  'single_cone_sprint_drill',
  'single_dumbbell_raise',
  'single_leg_butt_kick',
  'single_leg_glute_bridge',
  'single_leg_high_box_squat',
  'single_leg_hip_thrust',
  'single_leg_hop_progression',
  'single_leg_lateral_hop',
  'single_leg_leg_extension',
  'single_leg_leg_press',
  'single_leg_lying_leg_curl',
  'single_leg_push_off',
  'single_leg_romanian_deadlift',
  'single_leg_seated_calf_raise',
  'single_leg_standing_calf_raise',
  'single_leg_stride_jump',
  'sissy_squat',
  'sit_squats',
  'sit_up',
  'skating',
  'skull_crusher_lying_triceps_extension',
  'sled_drag_harness',
  'sled_overhead_backward_walk',
  'sled_overhead_triceps_extension',
  'sled_pull',
  'sled_push',
  'sled_reverse_flye',
  'sled_row',
  'sledgehammer_swings',
  'smith_incline_shoulder_raise',
  'smith_machine_behind_the_back_shrug',
  'smith_machine_bench_press',
  'smith_machine_bent_over_row',
  'smith_machine_calf_raise',
  'smith_machine_close_grip_bench_press',
  'smith_machine_decline_press',
  'smith_machine_hang_power_clean',
  'smith_machine_hip_raise',
  'smith_machine_hip_thrust',
  'smith_machine_incline_bench_press',
  'smith_machine_incline_press',
  'smith_machine_leg_press',
  'smith_machine_one_arm_upright_row',
  'smith_machine_overhead_shoulder_press',
  'smith_machine_pistol_squat',
  'smith_machine_reverse_calf_raises',
  'smith_machine_row',
  'smith_machine_shoulder_press',
  'smith_machine_shrug',
  'smith_machine_squat',
  'smith_machine_stiff_legged_deadlift',
  'smith_machine_upright_row',
  'smith_single_leg_split_squat',
  'snatch',
  'snatch_balance',
  'snatch_deadlift',
  'snatch_from_blocks',
  'snatch_grip_barbell_shrug',
  'snatch_grip_high_pull',
  'snatch_pull',
  'snatch_shrug',
  'speed_band_overhead_triceps',
  'speed_box_squat',
  'speed_squats',
  'spell_caster',
  'spider_crawl',
  'spider_curl',
  'spinal_stretch',
  'split_clean',
  'split_jerk',
  'split_jump',
  'split_snatch',
  'split_squat_with_dumbbells',
  'split_squats',
  'squat_jerk',
  'squat_with_bands',
  'squat_with_chains',
  'squat_with_plate_movers',
  'squats_with_bands',
  'stairmaster',
  'standing_alternating_dumbbell_press',
  'standing_barbell_calf_raise',
  'standing_barbell_press_behind_neck',
  'standing_bent_over_one_arm_dumbbell_triceps_extension',
  'standing_bent_over_two_arm_dumbbell_triceps_extension',
  'standing_biceps_cable_curl',
  'standing_biceps_stretch',
  'standing_bradford_press',
  'standing_cable_chest_press',
  'standing_cable_lift',
  'standing_cable_wood_chop',
  'standing_calf_raise',
  'standing_calf_raises',
  'standing_concentration_curl',
  'standing_dumbbell_calf_raise',
  'standing_dumbbell_press',
  'standing_dumbbell_reverse_curl',
  'standing_dumbbell_shoulder_press',
  'standing_dumbbell_straight_arm_front_delt_raise_above_head',
  'standing_dumbbell_triceps_extension',
  'standing_dumbbell_upright_row',
  'standing_elevated_quad_stretch',
  'standing_front_barbell_raise_over_head',
  'standing_gastrocnemius_calf_stretch',
  'standing_hamstring_and_calf_stretch',
  'standing_hip_circles',
  'standing_hip_flexors',
  'standing_inner_biceps_curl',
  'standing_lateral_stretch',
  'standing_leg_curl',
  'standing_long_jump',
  'standing_low_pulley_deltoid_raise',
  'standing_low_pulley_one_arm_triceps_extension',
  'standing_low_to_high_cable_chest_fly',
  'standing_military_press',
  'standing_olympic_plate_hand_squeeze',
  'standing_one_arm_cable_curl',
  'standing_one_arm_dumbbell_curl_over_incline_bench',
  'standing_one_arm_dumbbell_triceps_extension',
  'standing_overhead_barbell_triceps_extension',
  'standing_palm_in_one_arm_dumbbell_press',
  'standing_palms_in_dumbbell_press',
  'standing_palms_up_barbell_behind_the_back_wrist_curl',
  'standing_pelvic_tilt',
  'standing_rope_crunch',
  'standing_soleus_and_achilles_stretch',
  'standing_toe_touches',
  'standing_towel_triceps_extension',
  'standing_two_arm_overhead_throw',
  'star_jump',
  'step_mill',
  'step_through_lunge',
  'step_up_with_knee_raise',
  'stiff_leg_barbell_good_morning',
  'stiff_leg_deadlift',
  'stiff_legged_barbell_deadlift',
  'stiff_legged_dumbbell_deadlift',
  'stomach_vacuum',
  'straight_arm_dumbbell_pullover',
  'straight_arm_pulldown',
  'straight_arm_rope_pulldown',
  'straight_bar_bench_mid_rows',
  'straight_bar_cable_triceps_pushdown',
  'straight_raises_on_incline_bench',
  'stride_jump_crossover',
  'suitcase_carry',
  'sumo_deadlift',
  'sumo_deadlift_with_bands',
  'sumo_deadlift_with_chains',
  'superman',
  'supine_chest_throw',
  'supine_one_arm_overhead_throw',
  'supine_two_arm_overhead_throw',
  'suspended_fallout',
  'suspended_push_up',
  'suspended_reverse_crunch',
  'suspended_row',
  'suspended_split_squat',
  'svend_press',
  't_bar_row',
  't_bar_row_with_handle',
  'tate_press',
  'the_straddle',
  'thigh_abductor',
  'thigh_adductor',
  'tibialis_raise',
  'tire_flip',
  'toe_touchers',
  'toes_to_bar',
  'torso_rotation',
  'towel_pull_up_hold',
  'trail_running_walking',
  'trap_bar_deadlift',
  'trap_bar_shrug',
  'tricep_dumbbell_kickback',
  'tricep_side_stretch',
  'triceps_overhead_extension_with_rope',
  'triceps_pushdown',
  'triceps_pushdown_rope_attachment',
  'triceps_pushdown_v_bar_attachment',
  'triceps_stretch',
  'tuck_crunch',
  'two_arm_dumbbell_preacher_curl',
  'two_arm_kettlebell_clean',
  'two_arm_kettlebell_jerk',
  'two_arm_kettlebell_military_press',
  'two_arm_kettlebell_row',
  'underhand_cable_pulldowns',
  'upper_back_leg_grab',
  'upper_back_stretch',
  'upright_barbell_row',
  'upright_cable_row',
  'upright_row_with_bands',
  'upward_stretch',
  'v_bar_cable_triceps_pushdown',
  'v_bar_pulldown',
  'v_bar_pullup',
  'vertical_swing',
  'waiter_curl',
  'walking_lunge',
  'walking_treadmill',
  'wall_sit',
  'weighted_ball_hyperextension',
  'weighted_ball_side_bend',
  'weighted_bench_dip',
  'weighted_bicycle_crunch',
  'weighted_chest_dip',
  'weighted_crunches',
  'weighted_decline_crunch',
  'weighted_jump_squat',
  'weighted_plank',
  'weighted_pull_up',
  'weighted_pull_ups',
  'weighted_sissy_squat',
  'weighted_sit_up',
  'weighted_sit_ups_with_bands',
  'weighted_squat',
  'weighted_triceps_dip',
  'wide_grip_barbell_bench_press',
  'wide_grip_barbell_curl',
  'wide_grip_decline_barbell_bench_press',
  'wide_grip_decline_barbell_pullover',
  'wide_grip_lat_pulldown',
  'wide_grip_pulldown_behind_the_neck',
  'wide_grip_rear_pull_up',
  'wide_grip_seated_cable_row',
  'wide_grip_standing_barbell_curl',
  'wide_stance_barbell_squat',
  'wide_stance_stiff_legs',
  'wind_sprints',
  'windmills',
  'worlds_greatest_stretch',
  'wrist_circles',
  'wrist_roller',
  'wrist_rotations_with_straight_bar',
  'yates_row',
  'yoke_walk',
  'z_press',
  'zercher_squat',
  'zercher_squats',
  'zottman_curl',
  'zottman_preacher_curl',
]);

/** The library's own name for an id, when the id is one of the core lifts. */
export const CORE_NAME_BY_ID: Readonly<Record<string, string>> = {
  'ab_wheel_rollout': 'Ab Wheel Rollout',
  'arnold_press': 'Arnold Press',
  'assisted_pull_up': 'Assisted Pull-Up',
  'b_stance_hip_thrust': 'B-Stance Hip Thrust',
  'banded_glute_kickback': 'Banded Glute Kickback',
  'barbell_back_squat': 'Barbell Back Squat',
  'barbell_bench_press': 'Barbell Bench Press',
  'barbell_bent_over_row': 'Barbell Bent-Over Row',
  'barbell_curl': 'Barbell Curl',
  'barbell_deadlift': 'Barbell Deadlift',
  'barbell_floor_press': 'Barbell Floor Press',
  'barbell_front_raise': 'Barbell Front Raise',
  'barbell_hip_thrust': 'Barbell Hip Thrust',
  'barbell_landmine_row': 'Barbell Landmine Row',
  'barbell_shrug': 'Barbell Shrug',
  'barbell_upright_row': 'Barbell Upright Row',
  'barbell_wrist_curl': 'Barbell Wrist Curl',
  'behind_the_back_barbell_wrist_curl': 'Behind-the-Back Barbell Wrist Curl',
  'behind_the_back_cable_lateral_raise': 'Behind-the-Back Cable Lateral Raise',
  'behind_the_neck_lat_pulldown': 'Behind-the-Neck Lat Pulldown',
  'bench_dip': 'Bench Dip',
  'bent_over_rear_delt_fly': 'Bent-Over Rear Delt Fly',
  'bulgarian_split_squat': 'Bulgarian Split Squat',
  'cable_biceps_curl': 'Cable Biceps Curl',
  'cable_chest_fly': 'Cable Chest Fly',
  'cable_crunch': 'Cable Crunch',
  'cable_glute_kickback': 'Cable Glute Kickback',
  'cable_lat_pullover_straight_arm_pulldown': 'Cable Lat Pullover (Straight-Arm Pulldown)',
  'cable_lateral_raise': 'Cable Lateral Raise',
  'cable_pallof_press': 'Cable Pallof Press',
  'cable_rear_delt_fly': 'Cable Rear Delt Fly',
  'cable_rope_hammer_curl': 'Cable Rope Hammer Curl',
  'cable_shrug': 'Cable Shrug',
  'cable_triceps_kickback': 'Cable Triceps Kickback',
  'cable_triceps_pushdown': 'Cable Triceps Pushdown',
  'cable_upright_row': 'Cable Upright Row',
  'captains_chair_leg_raise': 'Captain\'s Chair Leg Raise',
  'chest_supported_dumbbell_row': 'Chest-Supported Dumbbell Row',
  'chest_supported_machine_row': 'Chest-Supported Machine Row',
  'chest_supported_t_bar_row': 'Chest-Supported T-Bar Row',
  'close_grip_barbell_curl': 'Close-Grip Barbell Curl',
  'close_grip_bench_press': 'Close-Grip Bench Press',
  'close_grip_dumbbell_bench_press': 'Close-Grip Dumbbell Bench Press',
  'close_grip_lat_pulldown': 'Close-Grip Lat Pulldown',
  'cross_body_cable_triceps_extension': 'Cross-Body Cable Triceps Extension',
  'cross_body_hammer_curl': 'Cross-Body Hammer Curl',
  'curtsy_lunge': 'Curtsy Lunge',
  'decline_barbell_bench_press': 'Decline Barbell Bench Press',
  'decline_push_up': 'Decline Push-Up',
  'decline_sit_up': 'Decline Sit-Up',
  'deficit_push_up': 'Deficit Push-Up',
  'donkey_calf_raise': 'Donkey Calf Raise',
  'dumbbell_biceps_curl': 'Dumbbell Biceps Curl',
  'dumbbell_chest_fly': 'Dumbbell Chest Fly',
  'dumbbell_flat_bench_press': 'Dumbbell Flat Bench Press',
  'dumbbell_front_raise': 'Dumbbell Front Raise',
  'dumbbell_hip_thrust': 'Dumbbell Hip Thrust',
  'dumbbell_lateral_raise': 'Dumbbell Lateral Raise',
  'dumbbell_overhead_triceps_extension': 'Dumbbell Overhead Triceps Extension',
  'dumbbell_preacher_curl': 'Dumbbell Preacher Curl',
  'dumbbell_romanian_deadlift': 'Dumbbell Romanian Deadlift',
  'dumbbell_shrug': 'Dumbbell Shrug',
  'dumbbell_skull_crusher': 'Dumbbell Skull Crusher',
  'dumbbell_standing_calf_raise': 'Dumbbell Standing Calf Raise',
  'dumbbell_step_up': 'Dumbbell Step-Up',
  'dumbbell_triceps_kickback': 'Dumbbell Triceps Kickback',
  'dumbbell_upright_row': 'Dumbbell Upright Row',
  'dumbbell_wrist_curl': 'Dumbbell Wrist Curl',
  'ez_bar_curl': 'EZ-Bar Curl',
  'ez_bar_overhead_triceps_extension': 'EZ-Bar Overhead Triceps Extension',
  'face_pull': 'Face Pull',
  'farmer_carry': 'Farmer Carry',
  'front_squat': 'Front Squat',
  'glute_bridge': 'Glute Bridge',
  'glute_ham_raise': 'Glute-Ham Raise',
  'goblet_squat': 'Goblet Squat',
  'good_morning': 'Good Morning',
  'hack_squat_machine': 'Hack Squat Machine',
  'hammer_curl': 'Hammer Curl',
  'hanging_knee_raise': 'Hanging Knee Raise',
  'hanging_leg_raise': 'Hanging Leg Raise',
  'high_to_low_cable_chest_fly': 'High-to-Low Cable Chest Fly',
  'hip_abduction_machine': 'Hip Abduction Machine',
  'hip_adduction_machine': 'Hip Adduction Machine',
  'incline_barbell_bench_press': 'Incline Barbell Bench Press',
  'incline_cable_press': 'Incline Cable Press',
  'incline_dumbbell_bench_press': 'Incline Dumbbell Bench Press',
  'incline_dumbbell_curl': 'Incline Dumbbell Curl',
  'incline_machine_chest_press': 'Incline Machine Chest Press',
  'incline_smith_machine_bench_press': 'Incline Smith Machine Bench Press',
  'kneeling_cable_pulldown': 'Kneeling Cable Pulldown',
  'lat_pulldown': 'Lat Pulldown',
  'leaning_cable_lateral_raise': 'Leaning Cable Lateral Raise',
  'leg_extension': 'Leg Extension',
  'leg_press': 'Leg Press',
  'leg_press_calf_raise': 'Leg Press Calf Raise',
  'low_incline_dumbbell_bench_press': 'Low-Incline Dumbbell Bench Press',
  'low_to_high_incline_cable_fly': 'Low-to-High Incline Cable Fly',
  'lying_dumbbell_lateral_raise': 'Lying Dumbbell Lateral Raise',
  'lying_leg_curl': 'Lying Leg Curl',
  'lying_leg_raise': 'Lying Leg Raise',
  'machine_ab_crunch': 'Machine Ab Crunch',
  'machine_assisted_chin_up': 'Machine-Assisted Chin-Up',
  'machine_biceps_curl': 'Machine Biceps Curl',
  'machine_chest_press': 'Machine Chest Press',
  'machine_glute_kickback': 'Machine Glute Kickback',
  'machine_high_row': 'Machine High Row',
  'machine_hip_thrust': 'Machine Hip Thrust',
  'machine_lat_pulldown': 'Machine Lat Pulldown',
  'machine_lateral_raise': 'Machine Lateral Raise',
  'machine_preacher_curl': 'Machine Preacher Curl',
  'machine_shoulder_press': 'Machine Shoulder Press',
  'machine_triceps_extension': 'Machine Triceps Extension',
  'meadows_style_landmine_row': 'Meadows-Style Landmine Row',
  'neutral_grip_dumbbell_bench_press': 'Neutral-Grip Dumbbell Bench Press',
  'neutral_grip_pulldown': 'Neutral-Grip Pulldown',
  'nordic_ham_curl': 'Nordic Ham Curl',
  'overhead_barbell_press': 'Overhead Barbell Press',
  'overhead_cable_triceps_extension': 'Overhead Cable Triceps Extension',
  'pause_back_squat': 'Pause Back Squat',
  'paused_barbell_bench_press': 'Paused Barbell Bench Press',
  'pec_deck_machine_fly': 'Pec Deck Machine Fly',
  'pendlay_row': 'Pendlay Row',
  'pendulum_squat': 'Pendulum Squat',
  'plate_front_raise': 'Plate Front Raise',
  'preacher_curl': 'Preacher Curl',
  'prone_incline_dumbbell_rear_delt_raise': 'Prone Incline Dumbbell Rear Delt Raise',
  'rack_pull': 'Rack Pull',
  'reverse_barbell_wrist_curl': 'Reverse Barbell Wrist Curl',
  'reverse_curl': 'Reverse Curl',
  'reverse_ez_bar_curl': 'Reverse EZ-Bar Curl',
  'reverse_grip_barbell_bench_press': 'Reverse-Grip Barbell Bench Press',
  'reverse_grip_cable_triceps_pushdown': 'Reverse-Grip Cable Triceps Pushdown',
  'reverse_grip_lat_pulldown': 'Reverse-Grip Lat Pulldown',
  'reverse_lunge': 'Reverse Lunge',
  'reverse_pec_deck_rear_delt_fly': 'Reverse Pec Deck (Rear Delt Fly)',
  'romanian_deadlift': 'Romanian Deadlift',
  'rope_overhead_cable_triceps_extension': 'Rope Overhead Cable Triceps Extension',
  'rope_triceps_pushdown': 'Rope Triceps Pushdown',
  'seal_row': 'Seal Row',
  'seated_barbell_overhead_press': 'Seated Barbell Overhead Press',
  'seated_bent_over_dumbbell_rear_delt_fly': 'Seated Bent-Over Dumbbell Rear Delt Fly',
  'seated_cable_row': 'Seated Cable Row',
  'seated_calf_raise': 'Seated Calf Raise',
  'seated_dumbbell_concentration_curl': 'Seated Dumbbell Concentration Curl',
  'seated_dumbbell_hammer_curl': 'Seated Dumbbell Hammer Curl',
  'seated_dumbbell_lateral_raise': 'Seated Dumbbell Lateral Raise',
  'seated_dumbbell_shoulder_press': 'Seated Dumbbell Shoulder Press',
  'seated_leg_curl': 'Seated Leg Curl',
  'seated_lying_leg_curl': 'Seated/Lying Leg Curl',
  'single_arm_cable_biceps_curl': 'Single-Arm Cable Biceps Curl',
  'single_arm_cable_chest_fly': 'Single-Arm Cable Chest Fly',
  'single_arm_cable_rear_delt_fly': 'Single-Arm Cable Rear Delt Fly',
  'single_arm_cable_row': 'Single-Arm Cable Row',
  'single_arm_cable_triceps_pushdown': 'Single-Arm Cable Triceps Pushdown',
  'single_arm_dumbbell_lateral_raise': 'Single-Arm Dumbbell Lateral Raise',
  'single_arm_dumbbell_overhead_triceps_extension': 'Single-Arm Dumbbell Overhead Triceps Extension',
  'single_arm_dumbbell_row': 'Single-Arm Dumbbell Row',
  'single_arm_dumbbell_shoulder_press': 'Single-Arm Dumbbell Shoulder Press',
  'single_arm_landmine_press': 'Single-Arm Landmine Press',
  'single_arm_lat_pulldown': 'Single-Arm Lat Pulldown',
  'single_leg_hip_thrust': 'Single-Leg Hip Thrust',
  'single_leg_leg_press': 'Single-Leg Leg Press',
  'single_leg_lying_leg_curl': 'Single-Leg Lying Leg Curl',
  'single_leg_romanian_deadlift': 'Single-Leg Romanian Deadlift',
  'single_leg_standing_calf_raise': 'Single-Leg Standing Calf Raise',
  'sissy_squat': 'Sissy Squat',
  'skull_crusher_lying_triceps_extension': 'Skull Crusher (Lying Triceps Extension)',
  'smith_machine_bench_press': 'Smith Machine Bench Press',
  'smith_machine_calf_raise': 'Smith Machine Calf Raise',
  'smith_machine_shoulder_press': 'Smith Machine Shoulder Press',
  'smith_machine_shrug': 'Smith Machine Shrug',
  'smith_machine_squat': 'Smith Machine Squat',
  'snatch_grip_barbell_shrug': 'Snatch-Grip Barbell Shrug',
  'spider_curl': 'Spider Curl',
  'standing_calf_raise': 'Standing Calf Raise',
  'standing_dumbbell_shoulder_press': 'Standing Dumbbell Shoulder Press',
  'standing_low_to_high_cable_chest_fly': 'Standing Low-to-High Cable Chest Fly',
  'stiff_leg_deadlift': 'Stiff-Leg Deadlift',
  'straight_bar_cable_triceps_pushdown': 'Straight-Bar Cable Triceps Pushdown',
  't_bar_row': 'T-Bar Row',
  'toes_to_bar': 'Toes-to-Bar',
  'trap_bar_shrug': 'Trap Bar Shrug',
  'v_bar_cable_triceps_pushdown': 'V-Bar Cable Triceps Pushdown',
  'walking_lunge': 'Walking Lunge',
  'weighted_bicycle_crunch': 'Weighted Bicycle Crunch',
  'weighted_chest_dip': 'Weighted Chest Dip',
  'weighted_decline_crunch': 'Weighted Decline Crunch',
  'weighted_plank': 'Weighted Plank',
  'weighted_pull_up': 'Weighted Pull-Up',
  'weighted_sit_up': 'Weighted Sit-Up',
  'weighted_triceps_dip': 'Weighted Triceps Dip',
  'wide_grip_barbell_curl': 'Wide-Grip Barbell Curl',
  'yates_row': 'Yates Row',
  'zercher_squat': 'Zercher Squat',
};
