-- EvoForge 000 — clone the public schema into a staging project
--
-- Purpose: stand up an empty Supabase project with the same 11 tables, so that
-- migrations/001 and tools/verify_rls.py can be rehearsed without touching your
-- real training data. verify_rls.py needs the SCHEMA, not the rows.
--
-- There is no pg_dump on this machine, so this generates the DDL with a query.
--
-- You never need to point the app at staging. The only reason production needs
-- the app is to create the owner account; in staging you make that account from
-- the dashboard, and verify_rls.py creates its own.
--
-- Naming, because there are two numbering systems and they are easy to confuse:
--   * This file has three queries: PART A, PART B, PART C.
--   * migrations/001 has eight numbered blocks: STEP 0 .. STEP 7.
--   * The procedure below is lettered (a) .. (j) and refers to both.
--
-- ---------------------------------------------------------------------------
-- PROCEDURE
--
-- ON PRODUCTION -- read-only, nothing is changed:
--
--  (a) SQL Editor -> run PART A. It returns 11 rows, each one a complete
--      `create table ...;` statement in the `ddl` column.
--
--  (b) READ WHAT IT PRINTED, then copy all 11 statements into one text buffer.
--      This is generated from pg_catalog, not dumped by pg_dump. Foreign keys
--      and indexes are omitted on purpose -- migrations/001 creates the ones
--      that matter.
--
-- ON STAGING -- a brand new, empty project:
--
--  (c) Create a new free Supabase project. Call it `evoforge-staging`.
--
--  (d) Authentication -> Providers -> Email: turn OFF "Confirm email".
--      Without this, sign_up() returns no session and verify_rls.py cannot sign
--      in. (It says so rather than failing cryptically.)
--
--  (e) SQL Editor -> paste the 11 statements from (b) and run them. This is the
--      whole point of PART A: staging now has production's tables and no rows.
--
--  (f) SQL Editor -> run PART B. Expect 11 tables, and ZERO columns named
--      user_id. Staging must start in the same shape production is in today.
--
--  (g) SQL Editor -> run PART C. It inserts a handful of rows with no owner,
--      plus a DUPLICATE achievement. No UUID needed: the user_id column does
--      not exist yet. This is what makes the rehearsal mean something -- it
--      recreates the two conditions migrations/001 has to survive.
--
--  (h) Authentication -> Users -> "Add user" -> "Create new user". Any email,
--      tick auto-confirm. Copy its UUID. This account stands in for you.
--      (Only now, because 001 STEP 2 is the first thing that needs an owner.)
--
--  (i) Run migrations/001, its STEP 0 through STEP 7, pasting the (h) UUID into
--      its STEP 2. Watch two things:
--          - STEP 2's orphan counts must all reach 0
--          - STEP 4 must report `first_workout | copies = 2`, then build the
--            unique index without error
--
--  (j) Prove it:
--        SUPABASE_URL=https://<staging-ref>.supabase.co \
--        SUPABASE_KEY=<staging publishable key> \
--        python tools/verify_rls.py --i-understand-this-writes-to-the-database
--      It must print `RLS VERIFIED`. (verify_rls.py reads env vars only; it
--      never touches .streamlit/secrets.toml.)
--
-- ON PRODUCTION, only after (j) passes:
--
--      Repeat (h) and (i) -- but (h) becomes "sign up through the live app",
--      and skip (g) entirely, because the real unowned rows are already there.
-- ---------------------------------------------------------------------------


-- ===========================================================================
-- PART A — generate CREATE TABLE statements for the 11 tables
-- ===========================================================================
with target as (
  select unnest(array[
    'workout_log', 'bodyweight_log', 'cardio_log', 'bodyfat_log', 'measurements',
    'physique_ratings', 'custom_workout_plan', 'achievements', 'targets',
    'profile', 'avatar_progression'
  ]) as tbl
),
cols as (
  select
    c.relname as tbl,
    a.attnum,
    '  ' || quote_ident(a.attname) || ' ' ||
    case
      -- Identity columns carry their own default; never emit one.
      when a.attidentity = 'a' then
        format_type(a.atttypid, a.atttypmod) || ' generated always as identity'
      when a.attidentity = 'd' then
        format_type(a.atttypid, a.atttypmod) || ' generated by default as identity'

      -- A `nextval(...)` default names a sequence that does not exist in the
      -- new project. Re-express it as serial so the sequence is created.
      when pg_get_expr(d.adbin, d.adrelid) like 'nextval(%' then
        case format_type(a.atttypid, a.atttypmod)
          when 'smallint' then 'smallserial'
          when 'integer'  then 'serial'
          when 'bigint'   then 'bigserial'
          else format_type(a.atttypid, a.atttypmod)
        end

      else
        format_type(a.atttypid, a.atttypmod) ||
        coalesce(' default ' || pg_get_expr(d.adbin, d.adrelid), '')
    end ||
    case when a.attnotnull then ' not null' else '' end as line
  from pg_attribute a
  join pg_class c      on c.oid = a.attrelid
  join pg_namespace n  on n.oid = c.relnamespace
  join target t        on t.tbl = c.relname
  left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
  where n.nspname = 'public'
    and a.attnum > 0
    and not a.attisdropped
    -- user_id is added by migrations/001. Never clone it: staging must start
    -- from the same pre-migration shape production is in.
    and a.attname <> 'user_id'
),
cons as (
  select
    c.relname as tbl,
    string_agg(
      '  constraint ' || quote_ident(k.conname) || ' ' || pg_get_constraintdef(k.oid),
      ',' || chr(10) order by k.contype, k.conname
    ) as lines
  from pg_constraint k
  join pg_class c     on c.oid = k.conrelid
  join pg_namespace n on n.oid = c.relnamespace
  join target t       on t.tbl = c.relname
  where n.nspname = 'public'
    -- primary, unique, check. Foreign keys are omitted on purpose.
    and k.contype in ('p', 'u', 'c')
  group by c.relname
)
-- chr(10), not E'\n': escape strings depend on standard_conforming_strings.
select
  'create table public.' || quote_ident(cols.tbl) || ' (' || chr(10) ||
  string_agg(cols.line, ',' || chr(10) order by cols.attnum) ||
  coalesce(',' || chr(10) || max(cons.lines), '') ||
  chr(10) || ');' as ddl
from cols
left join cons on cons.tbl = cols.tbl
group by cols.tbl
order by cols.tbl;


-- ===========================================================================
-- PART B — sanity check. Run in STAGING, after pasting the DDL from PART A.
-- ===========================================================================
-- Expect 11 rows.
select table_name, count(*) as columns
from information_schema.columns
where table_schema = 'public'
group by table_name
order by table_name;

-- Expect ZERO rows: staging must start in the same pre-migration shape that
-- production is in. If user_id already exists here, you cloned the wrong thing.
select table_name from information_schema.columns
where table_schema = 'public' and column_name = 'user_id';


-- ===========================================================================
-- PART C — seed STAGING with production's actual shape
--
-- Run in STAGING, before migrations/001. Two properties matter, and both are
-- properties migrations/001 has to survive:
--
--   * rows exist with user_id NULL      -> exercises STEP 2's backfill
--   * `achievements` holds a duplicate  -> exercises STEP 4's dedupe, which
--                                          would otherwise abort the migration
--                                          AFTER the irreversible STEP 3
--
-- Skip this and the rehearsal proves only that valid SQL is valid SQL.
-- ===========================================================================
-- `timestamp` MUST be quoted -- it is a type-name keyword, and an unquoted
-- `timestamp` in a column list is a syntax error. `set` need not be: Postgres
-- classes it UNRESERVED, which is why quote_ident() left it bare in PART A.
insert into public.workout_log (date, workout, exercise, muscle, "set", weight, reps, estimated_1rm, volume, notes, "timestamp")
values (current_date, 'Push 1', 'Barbell Bench Press (Strength)', 'Chest', 1, 80, 5, 93.3, 400, '', now()),
       (current_date, 'Push 1', 'Barbell Bench Press (Strength)', 'Chest', 2, 80, 5, 93.3, 400, '', now());

insert into public.bodyweight_log (date, bodyweight, "timestamp")
values (current_date, 77.0, now());

insert into public.profile (height_cm, bodyweight_kg, bench_e1rm, squat_e1rm, training_years, physique_score, leanness_score, base_level, created_at)
values (183.5, 77.0, 96, 140, 3, 10, 10, 42, now());

-- The important one. Two rows, same achievement_id, different date_unlocked.
-- STEP 4 must delete the older and keep the newer -- matching what
-- domain/achievements.py :: load_achievements() already displays.
--
-- Note `date_unlocked` is a DATE column, not a timestamp: the app writes an ISO
-- datetime string and Postgres truncates the time. So two achievements unlocked
-- on the same day tie on date, and STEP 4 breaks the tie on `id` -- which is a
-- random uuid. That is fine: the tied rows are identical apart from their id.
insert into public.achievements (achievement_id, name, description, date_unlocked)
values ('first_workout', 'First Workout', 'Logged your first set',  '2024-01-01T09:00:00'),
       ('first_workout', 'First Workout', 'Logged your first set',  '2024-06-01T09:00:00'),
       ('ten_workouts',  'Ten Workouts',  'Logged ten sessions',    '2024-03-01T09:00:00');

-- Expect exactly one row: first_workout, copies = 2.
select achievement_id, count(*) as copies
from public.achievements
group by achievement_id
having count(*) > 1;

-- After migrations/001 STEP 4, expect zero rows from the query above, and:
--   select achievement_id, date_unlocked from public.achievements order by 1;
-- must show exactly two rows, with first_workout at 2024-06-01.
