-- EvoForge — staging schema. Paste this whole file into the STAGING project.
--
-- ###########################################################################
-- #  STAGING ONLY. Running this against production does nothing good and     #
-- #  will error on the first statement, because the tables already exist.    #
-- ###########################################################################
--
-- This is step (e) of the procedure in 000_clone_schema_to_staging.sql.
--
-- Generated by that file's PART A against the live database on 2026-07-10, then
-- transcribed verbatim. The only edit: `set` is quoted as `"set"`. Postgres
-- classes SET as an UNRESERVED keyword so quote_ident() left it bare, and bare
-- is legal -- but `"set"` denotes the identical identifier and survives being
-- pasted through tools with a less forgiving parser.
--
-- Deliberately absent:
--   * user_id        -- migrations/001 adds it. Staging must start in the same
--                       pre-migration shape production is in.
--   * indexes        -- migrations/001 STEP 5 creates the ones that matter.
--   * foreign keys   -- none exist between these tables.
--   * RLS            -- migrations/001 STEP 6 enables it. Off is the honest
--                       starting state: it is what production looks like now.
--
-- `gen_random_uuid()` is core Postgres on any Supabase project. No extension.
--
-- After running this, run PART B of 000_clone_schema_to_staging.sql:
-- expect 11 tables and ZERO columns named user_id.


create table public.achievements (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  date_unlocked date,
  description text,
  achievement_id text,
  name text,
  constraint achievements_pkey primary key (id)
);

create table public.avatar_progression (
  id bigint generated by default as identity not null,
  "timestamp" timestamp with time zone default now() not null,
  aesthetic_score numeric,
  ai_summary text,
  build_type text,
  character_class text,
  conditioning_score numeric,
  date date,
  leanness_score numeric,
  level numeric,
  rank text,
  size_score numeric,
  strength_score numeric,
  weak_point_focus text,
  constraint avatar_progression_pkey primary key (id)
);

create table public.bodyfat_log (
  id uuid default gen_random_uuid() not null,
  "timestamp" timestamp with time zone default now() not null,
  date date,
  method text,
  bodyweight numeric,
  height_cm numeric,
  waist_cm numeric,
  neck_cm numeric,
  bf_low numeric,
  bf_high numeric,
  bf_mid numeric,
  confidence text,
  notes text,
  constraint bodyfat_log_pkey primary key (id)
);

create table public.bodyweight_log (
  id uuid default gen_random_uuid() not null,
  "timestamp" timestamp with time zone default now() not null,
  date date,
  bodyweight numeric,
  constraint bodyweight_log_pkey primary key (id)
);

create table public.cardio_log (
  id uuid default gen_random_uuid() not null,
  "timestamp" timestamp with time zone default now() not null,
  date date,
  type text,
  minutes numeric,
  distance_km numeric,
  incline numeric,
  speed numeric,
  calories numeric,
  notes text,
  constraint cardio_log_pkey primary key (id)
);

create table public.custom_workout_plan (
  id uuid default gen_random_uuid() not null,
  "timestamp" timestamp with time zone default now() not null,
  plan_name text,
  workout text,
  exercise text,
  sets smallint,
  reps text,
  muscle text,
  reason text,
  day_goal text,
  constraint custom_workout_plan_pkey primary key (id)
);

create table public.measurements (
  id uuid default gen_random_uuid() not null,
  "timestamp" timestamp with time zone default now() not null,
  date date,
  wrist_cm numeric,
  forearm_cm numeric,
  bicep_cm numeric,
  chest_cm numeric,
  shoulders_cm numeric,
  waist_cm numeric,
  hips_cm numeric,
  thigh_cm numeric,
  calf_cm numeric,
  neck_cm numeric,
  bodyweight numeric,
  notes text,
  constraint measurements_pkey primary key (id)
);

create table public.physique_ratings (
  id uuid default gen_random_uuid() not null,
  "timestamp" timestamp with time zone default now() not null,
  date date,
  physique_score numeric,
  leanness_score numeric,
  symmetry_score numeric,
  muscularity_score numeric,
  confidence text,
  weak_points jsonb,
  improvements jsonb,
  summary text,
  constraint physique_ratings_pkey primary key (id)
);

create table public.profile (
  id uuid default gen_random_uuid() not null,
  "timestamp" timestamp with time zone default now() not null,
  height_cm numeric,
  base_level numeric,
  bench_e1rm numeric,
  bodyweight_kg numeric,
  created_at timestamp with time zone,
  leanness_score numeric,
  physique_score numeric,
  squat_e1rm numeric,
  training_years numeric,
  constraint profile_pkey primary key (id)
);

create table public.targets (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  target_type text,
  name text,
  target_value numeric,
  notes text,
  unit text,
  constraint targets_pkey primary key (id)
);

create table public.workout_log (
  id uuid default gen_random_uuid() not null,
  "timestamp" timestamp with time zone default now() not null,
  date date,
  workout text,
  exercise text,
  muscle text,
  "set" smallint,
  estimated_1rm numeric,
  volume numeric,
  notes text,
  reps smallint,
  weight numeric,
  constraint workout_log_pkey primary key (id)
);
