-- EvoForge 116 — a block is not a vote, and cannot be outvoted.
--
-- THE HOLE
--
--   command_vote_release checked `status in ('open','changes_requested')` and
--   nothing else. It never looked at sentinel_verdict. So a release the Sentinel
--   had BLOCKED could be voted to 'approved' by the founders, and the same
--   function would then queue a deploy dispatch for it.
--
--   The runner refuses to deploy a release whose sentinel_verdict is not
--   'approved', so nothing would actually have shipped — but that is defence in
--   depth catching a governance failure, not the governance working. The
--   council would have recorded an approval that could never be honoured, a
--   deploy job would sit failing, and the system's own claim that the Sentinel
--   gates releases would have been false at the layer where it is decided.
--
-- THE RULE
--
--   The Sentinel is a GATE, not a fourth voter. A gate is cleared by fixing what
--   it caught and re-running it, never by three people disagreeing with it. So:
--
--     approve          refused while blocked, with the block's own reason.
--     reject           allowed. You may always reject something.
--     request_changes  allowed. It is the correct response to a block.
--     abstain          allowed.
--
--   Rejecting a blocked release must stay possible, or a bad change could get
--   stuck in the chamber forever with no way for a human to close it.
--
-- WHY THIS SURFACED
--
--   REL-001 was blocked with "typecheck failed" over code that typechecks
--   perfectly. The worktree was a clean checkout with no node_modules, so npx
--   could not find tsc, and expo-env.d.ts — generated by Expo and gitignored by
--   design — was absent, so a CSS side-effect import had no declaration. Both
--   are environmental. The runner now provisions both before any gate runs and
--   reports "could not run" separately from "failed"; this migration closes the
--   governance side, which was that the block could simply be voted past.
--
-- FALSIFICATION (scripts/_falsify116.mjs):
--   1. approving a blocked release is refused, and says why it is blocked.
--   2. rejecting a blocked release is still allowed.
--   3. requesting changes on a blocked release is still allowed.
--   4. approving is allowed again once the Sentinel passes.
--   5. an approval already recorded before the block cannot carry it to
--      'approved' — the tally re-checks.

/**
 * Rebuilt on the CURRENT definition of command_vote_release, not an older copy.
 * Everything below is unchanged except the two blocks marked SENTINEL GATE.
 */
create or replace function public.command_vote_release(
  p_release uuid, p_choice text, p_rationale text default ''::text
) returns jsonb language plpgsql security definer set search_path = public as $$
declare rel record; t jsonb; v_name text; v_status text; v_halted boolean;
begin
  if not is_founder() then
    raise exception 'command: founders only' using errcode = 'insufficient_privilege';
  end if;
  select * into rel from command_releases where id = p_release for update;
  if rel is null then raise exception 'command: no such release'; end if;
  if rel.status not in ('open','changes_requested') then
    raise exception 'command: % is % — voting is closed', rel.ref, rel.status;
  end if;

  -- ── SENTINEL GATE ───────────────────────────────────────────────────────
  -- A block is not a vote. Rejecting and requesting changes stay open, so a
  -- blocked release can always be closed by a human; approving does not,
  -- because the gate is cleared by fixing and re-running it.
  if rel.sentinel_verdict = 'blocked' and p_choice = 'approve' then
    raise exception
      'command: % is blocked by the Sentinel and a block cannot be outvoted. %  '
      'Clear the gate by fixing what it caught and re-running it — or reject the release.',
      rel.ref, coalesce(nullif(trim(rel.sentinel_note), ''), 'No reason was recorded.');
  end if;

  select name into v_name from command_founders where user_id = auth.uid();
  insert into command_release_votes (release_id, founder_id, choice, rationale, at)
  values (p_release, auth.uid(), p_choice, coalesce(p_rationale,''), now())
  on conflict (release_id, founder_id)
    do update set choice = excluded.choice, rationale = excluded.rationale, at = now();

  perform command_log('release_vote', 'release', p_release, rel.ref,
                      v_name || ' voted ' || p_choice || ' on ' || rel.ref,
                      jsonb_build_object('choice', p_choice, 'rationale', p_rationale));

  t := command_release_tally(p_release);

  -- ── SENTINEL GATE, the other half ───────────────────────────────────────
  --
  -- command_release_tally computes `rejected` as
  --   (founders - reject) < needed  OR  sentinel_verdict = 'blocked'
  --
  -- so on a BLOCKED release the tally reports rejected=true no matter how
  -- anyone voted. Combined with the branch below, that meant any vote at all on
  -- a blocked release — including "request changes", the correct response to a
  -- block — set its status to 'rejected' and closed it permanently. Voting
  -- closes at that point, so the release could no longer be iterated on even
  -- after the block was fixed. A gate that kills the thing it stopped is not a
  -- gate, it is a trapdoor.
  --
  -- Held at changes_requested instead, unless the FOUNDERS actually voted it
  -- down. The tally's own approve/reject counts decide that, not the verdict.
  if rel.sentinel_verdict = 'blocked' and (t->>'reject')::int = 0 then
    update command_releases set status = 'changes_requested', updated_at = now() where id = p_release;
    perform command_log('release_held_by_sentinel', 'release', p_release, rel.ref,
      format('%s held at changes_requested — the Sentinel blocks it and nobody has voted it down. %s',
             rel.ref, coalesce(rel.sentinel_note, '')), t, 'system', 'sentinel');
    return jsonb_build_object('ok', true, 'status', 'changes_requested', 'tally', t,
      'held_by', 'sentinel', 'why', rel.sentinel_note);
  end if;

  if (t->>'approved')::boolean then
    v_status := 'approved';
    update command_releases set status = 'approved', decided_at = now(), updated_at = now() where id = p_release;
    select (value)::text::boolean into v_halted from command_settings where key = 'halted';
    if not coalesce(v_halted, false) then
      insert into command_dispatch (kind, work_order_id, release_id, priority, payload)
      values ('deploy', rel.work_order_id, p_release, 5,
              jsonb_build_object('instruction','Merge the work order branch and push. CI deploys.'));
    end if;
    perform command_log('release_approved', 'release', p_release, rel.ref,
                        rel.ref || ' approved ' || (t->>'approve') || '/' || (t->>'founders') ||
                        ' — deploy queued', t, 'system', 'council');
  elsif (t->>'rejected')::boolean then
    v_status := 'rejected';
    update command_releases set status = 'rejected', decided_at = now(), updated_at = now() where id = p_release;
    perform command_log('release_rejected', 'release', p_release, rel.ref, rel.ref || ' rejected', t, 'system', 'council');
  elsif (t->>'request_changes')::int > 0 then
    v_status := 'changes_requested';
    update command_releases set status = 'changes_requested', updated_at = now() where id = p_release;
  else
    v_status := rel.status;
  end if;
  return jsonb_build_object('ok', true, 'status', v_status, 'tally', t);
end $$;
revoke all on function public.command_vote_release(uuid, text, text) from public, anon;
grant execute on function public.command_vote_release(uuid, text, text) to authenticated;

/**
 * Re-run the Sentinel on a release that was blocked.
 *
 * The counterpart to the rule above: if a block cannot be outvoted, there has
 * to be a way to clear it. This queues the gate again — it does not decide
 * anything itself, and it deliberately cannot set the verdict. Only a real run
 * of the checks can do that.
 */
create or replace function public.command_rerun_sentinel(p_release uuid, p_reason text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare rel record; v_name text;
begin
  if not is_founder() then raise exception 'command: founders only'; end if;
  if coalesce(trim(p_reason),'') = '' then
    raise exception 'command: say what changed. Re-running a gate that caught something real, without changing anything, just spends the time again';
  end if;

  select * into rel from command_releases where id = p_release;
  if rel is null then raise exception 'command: no such release'; end if;
  if rel.status in ('deployed','rolled_back','withdrawn') then
    raise exception 'command: % is % — there is nothing left to gate', rel.ref, rel.status;
  end if;

  select name into v_name from command_founders where user_id = auth.uid();

  insert into command_dispatch (kind, work_order_id, release_id, priority, payload)
  values ('verify', rel.work_order_id, rel.id, 4,
          jsonb_build_object('instruction', 'Re-run every gate on this release.', 'reason', p_reason));

  -- 'pending', not null: sentinel_verdict is NOT NULL and its vocabulary is
  -- exactly pending/approved/blocked. 'pending' already means "the gate has not
  -- decided", which is precisely the state a re-run returns it to.
  update command_releases
     set sentinel_verdict = 'pending',
         sentinel_note = format('Re-run requested by %s: %s', coalesce(v_name,'a founder'), p_reason),
         updated_at = now()
   where id = p_release;

  perform command_log('sentinel_rerun', 'release', rel.id, rel.ref,
    format('%s asked the Sentinel to re-run %s — %s', coalesce(v_name,'a founder'), rel.ref, p_reason),
    jsonb_build_object('reason', p_reason));

  return jsonb_build_object('ok', true, 'ref', rel.ref);
end $$;
revoke all on function public.command_rerun_sentinel(uuid, text) from public, anon;
grant execute on function public.command_rerun_sentinel(uuid, text) to authenticated;
