-- EvoForge 123 — Tier 1: the filter that costs nothing.
--
-- 147 events pending and climbing, with nothing draining them. 117 said that
-- honestly ("events accumulate as a visible backlog") and honest is not the same
-- as fine: an unbounded queue makes the one event that matters impossible to
-- find, and 7 of the P0s were dead-letter tests I ran myself.
--
-- THIS IS NOT LEARNING. It is the deterministic pass the spec's efficiency
-- section calls Tier 1: duplicates, routine metadata, known no-impact events.
-- No model, no cost, no judgement. It decides only what NOT to think about, and
-- everything it cannot rule out stays pending for Professor.
--
-- NOTHING IS DELETED. Events are marked `no_impact` with the reason recorded in
-- `classification`, so the filter's own decisions can be audited and reversed.
-- A filter that quietly dropped rows would be indistinguishable from a bug that
-- lost them.
--
-- WHY FIXTURES ARE THE FIRST RULE
--
--   The falsification scripts exercise real RPCs, so they write real audit rows
--   and emit real events: 18 knowledge_published, 12 knowledge_purged, 6
--   event_replayed, and 7 P0 dead-letters from tests whose entire purpose was
--   to prove dead-lettering works. Left in, Professor would eventually learn
--   organisational lessons from my test fixtures — the exact "one weak event
--   becomes truth" failure the whole design is built to prevent.
--
-- FALSIFICATION (scripts/_falsify123.mjs):
--   1. a fixture event is filtered, and says it was a fixture.
--   2. a routine lifecycle event is filtered.
--   3. a founder decision is NEVER filtered.
--   4. a security or release event is NEVER filtered.
--   5. filtering is reversible — nothing is deleted.

/**
 * Tier 1. Runs every runner cycle. Pure SQL.
 *
 * Two rules, in order of confidence:
 *
 *   FIXTURES — anything whose subject is a falsification artefact. These refs
 *   are generated by the _falsify scripts and match no real entity.
 *
 *   ROUTINE LIFECYCLE — a task moving between its own states, a dispatch being
 *   claimed or requeued, a lab job progressing. These are how work moves, not
 *   things learned from it. The work ORDER completing is kept; the six status
 *   changes it passed through on the way are not.
 *
 * Everything else stays pending. When in doubt the event survives, because the
 * cost of keeping a boring event is a row, and the cost of dropping an
 * important one is a lesson nobody learns.
 */
create or replace function public.command_events_tier1()
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_fixture int := 0; v_routine int := 0;
begin
  -- 1. Falsification fixtures. WO-F122-48210, PROP-F116-3245, REL-F103-…,
  --    f117_rule_… — all generated with a tag, none referring to real work.
  update command_events
     set status = 'no_impact',
         classification = 'tier1: falsification fixture — a test artefact, not organisational history',
         processed_at = now()
   where status = 'pending'
     and (
          payload->>'entity_ref' ~ '^(WO|PROP|REL|EXP|ARENA|PRED)-F[0-9]'
       or payload->>'entity_ref' like 'falsify%'
       or payload->>'entity_ref' ~ '^f1[0-9]{2}_'
       -- NO SUMMARY-TEXT MATCHING. The first version also matched summaries
       -- containing "falsif" or "fixture", and falsification caught what that
       -- costs: a real council approval reading "replace the test fixture
       -- generator" was filtered as a test artefact. The reference patterns are
       -- generated by the _falsify scripts and match no real entity, so they are
       -- precise; prose is not. Some fixture events will now survive the filter,
       -- which is the safe direction — a boring event costs a row.
     );
  get diagnostics v_fixture = row_count;

  -- 2. Routine lifecycle. How work moves, not what was learned from it.
  update command_events
     set status = 'no_impact',
         classification = 'tier1: routine lifecycle — a state change, not a durable lesson',
         processed_at = now()
   where status = 'pending'
     and (
          event_type like 'audit.task\_%'
       or event_type in (
            'audit.dispatch_claimed','audit.dispatch_done','audit.dispatch_requeued',
            'audit.dispatch_reclaimed','audit.dispatch_swept','audit.runner_desired_set',
            'audit.lab_desired_set','audit.criteria_progress','audit.step_toggled',
            -- The filter logs its own run, which emits an event, which the next
            -- run would filter, which logs again. Left out, Tier 1 feeds itself
            -- one row per cycle forever.
            'audit.events_filtered','audit.events_unfiltered')
       or event_type like 'audit.lab\_job%'
     );
  get diagnostics v_routine = row_count;

  if v_fixture + v_routine > 0 then
    perform command_log('events_filtered', 'settings', null, 'tier1',
      format('Tier 1 filtered %s fixture and %s routine event(s) — nothing deleted, all marked no_impact with the reason',
             v_fixture, v_routine),
      jsonb_build_object('fixtures', v_fixture, 'routine', v_routine),
      'system', 'tier1');
  end if;

  return jsonb_build_object('ok', true, 'fixtures', v_fixture, 'routine', v_routine,
                            'still_pending', (select count(*) from command_events where status = 'pending'));
end $$;

/**
 * Undo a Tier 1 decision.
 *
 * The filter is deterministic and therefore wrong in exactly the ways its rules
 * are wrong. A founder can put a class of events back in the queue, which is
 * the property that makes filtering safe rather than lossy.
 */
create or replace function public.command_events_unfilter(p_event_type text, p_reason text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_rows int := 0;
begin
  if not is_founder() then raise exception 'command: founders only'; end if;
  if coalesce(trim(p_reason),'') = '' then
    raise exception 'command: say why these matter — otherwise the filter rule should change, not this one batch';
  end if;

  update command_events
     set status = 'pending', classification = null, processed_at = null
   where status = 'no_impact' and event_type = p_event_type
     and classification like 'tier1:%';
  get diagnostics v_rows = row_count;

  perform command_log('events_unfiltered', 'settings', null, p_event_type,
    format('%s %s event(s) returned to the queue — %s', v_rows, p_event_type, p_reason),
    jsonb_build_object('rows', v_rows, 'reason', p_reason));

  return jsonb_build_object('ok', true, 'restored', v_rows);
end $$;
revoke all on function public.command_events_unfilter(text, text) from public, anon;
grant execute on function public.command_events_unfilter(text, text) to authenticated;

insert into public.command_integrations (key,label,category,status,detail,setup_required) values
  ('knowledge_tier1','Event filter (Tier 1)','knowledge','live',
   'A deterministic SQL pass that marks falsification fixtures and routine lifecycle events as no_impact, with the reason recorded. No model, no cost, no judgement — it decides only what not to think about, and anything it cannot rule out stays pending. Nothing is deleted and a founder can reverse any class.',
   'Runs every runner cycle. It is a filter, not a learner — Tier 2 and Professor are still Phase 3.')
on conflict (key) do update set status=excluded.status, label=excluded.label,
  detail=excluded.detail, setup_required=excluded.setup_required, updated_at=now();

select public.command_events_tier1();
