/**
 * Initial card set: 10 Fighters, 6 Techniques, 4 Equipment (20 total).
 * Data-driven — the engine and UI interpret these definitions; no card has
 * its own component or hardcoded logic.
 */
import { secondsToTicks } from './balance';
import type { CardDefinition } from './types';

const noUpgrade = { enabled: false, statMultPerLevel: 1.1 };

export const CARDS: CardDefinition[] = [
  // ── Fighters ────────────────────────────────────────────────────────────
  {
    id: 'forge-recruit',
    name: 'Forge Recruit',
    description: 'Two cheap melee trainees. Expendable, enthusiastic.',
    category: 'fighter',
    energyCost: 2,
    target: 'deploy-lane',
    tags: ['brawler'],
    unit: {
      deployCount: 2,
      stats: {
        maxHealth: 160,
        attackDamage: 28,
        attackIntervalTicks: secondsToTicks(1.1),
        attackRange: 3,
        moveSpeedPerTick: 0.28,
        isRanged: false,
      },
    },
    balanceTags: ['cycle', 'defense'],
    upgrade: noUpgrade,
    art: 'recruit',
  },
  {
    id: 'titan-guard',
    name: 'Titan Guard',
    description: 'Slow armoured frontline that soaks hits for the squad.',
    category: 'fighter',
    energyCost: 4,
    target: 'deploy-lane',
    tags: ['titan', 'brawler'],
    unit: {
      deployCount: 1,
      stats: {
        maxHealth: 650,
        attackDamage: 42,
        attackIntervalTicks: secondsToTicks(1.6),
        attackRange: 3,
        moveSpeedPerTick: 0.18,
        isRanged: false,
      },
    },
    balanceTags: ['tank', 'defense'],
    upgrade: noUpgrade,
    art: 'titan-guard',
  },
  {
    id: 'neon-boxer',
    name: 'Cardio Boxer',
    description: 'Fast combinations, endless conditioning. Wears an opponent down on volume.',
    category: 'fighter',
    energyCost: 3,
    target: 'deploy-lane',
    tags: ['cardio', 'brawler'],
    unit: {
      deployCount: 1,
      stats: {
        maxHealth: 300,
        attackDamage: 34,
        attackIntervalTicks: secondsToTicks(0.7),
        attackRange: 3,
        moveSpeedPerTick: 0.3,
        isRanged: false,
      },
    },
    balanceTags: ['dps'],
    upgrade: noUpgrade,
    art: 'neon-boxer',
  },
  {
    id: 'cardio-runner',
    name: 'Cardio Runner',
    description: 'Sprints down the lane, ignoring units to pressure the core.',
    category: 'fighter',
    energyCost: 3,
    target: 'deploy-lane',
    tags: ['cardio'],
    unit: {
      deployCount: 1,
      behavior: 'core-only',
      stats: {
        maxHealth: 220,
        attackDamage: 50,
        attackIntervalTicks: secondsToTicks(1.2),
        attackRange: 3,
        moveSpeedPerTick: 0.42,
        isRanged: false,
      },
    },
    balanceTags: ['win-condition', 'core-pressure'],
    upgrade: noUpgrade,
    art: 'cardio-runner',
  },
  {
    id: 'shadow-striker',
    name: 'The Cutter',
    description:
      'Explosive, lean, and built to fold before it slows down. High burst damage, fragile frame — hunts the closest threat.',
    category: 'fighter',
    energyCost: 4,
    target: 'deploy-lane',
    tags: ['shredder'],
    unit: {
      deployCount: 1,
      stats: {
        maxHealth: 240,
        attackDamage: 95,
        attackIntervalTicks: secondsToTicks(1.4),
        attackRange: 3.5,
        moveSpeedPerTick: 0.26,
        isRanged: false,
      },
    },
    balanceTags: ['burst', 'dps'],
    upgrade: noUpgrade,
    art: 'shadow-striker',
  },
  {
    id: 'drone-archer',
    name: 'Javelin Marksman',
    description: 'Throws javelins from deep in the lane, chipping targets down from range.',
    category: 'fighter',
    energyCost: 3,
    target: 'deploy-lane',
    tags: ['tech', 'ranged'],
    unit: {
      deployCount: 1,
      stats: {
        maxHealth: 190,
        attackDamage: 38,
        attackIntervalTicks: secondsToTicks(1.0),
        attackRange: 16,
        moveSpeedPerTick: 0.22,
        isRanged: true,
      },
    },
    balanceTags: ['ranged', 'support-dps'],
    upgrade: noUpgrade,
    art: 'drone-archer',
  },
  {
    id: 'cyber-medic',
    name: 'Recovery Coach',
    description: 'Heals the most damaged nearby ally instead of attacking.',
    category: 'fighter',
    energyCost: 4,
    target: 'deploy-lane',
    // Dual identity: a dedicated healer directly amplifies Aesthetics' Flow
    // State (+10% team healing) while still filling the generic support
    // slot (like heavy-tank's titan/mass split).
    tags: ['support', 'tech', 'ranged', 'aesthetic'],
    unit: {
      deployCount: 1,
      behavior: 'healer',
      stats: {
        maxHealth: 260,
        // Medic "attack" is a heal beam — the engine interprets support units.
        attackDamage: 30,
        attackIntervalTicks: secondsToTicks(1.2),
        attackRange: 12,
        moveSpeedPerTick: 0.2,
        isRanged: true,
      },
    },
    balanceTags: ['healer', 'support'],
    upgrade: noUpgrade,
    art: 'cyber-medic',
  },
  {
    id: 'heavy-tank',
    name: 'Heavy Tank',
    description: 'Enormous health pool. Wins lanes by refusing to die.',
    category: 'fighter',
    energyCost: 6,
    target: 'deploy-lane',
    // Dual identity: a heavy frontliner counts for both the titan wall and
    // the mass line's presence (like blade-runner's shredder/cardio split).
    tags: ['titan', 'mass'],
    unit: {
      deployCount: 1,
      stats: {
        maxHealth: 1100,
        attackDamage: 55,
        attackIntervalTicks: secondsToTicks(1.8),
        attackRange: 3,
        moveSpeedPerTick: 0.14,
        isRanged: false,
      },
    },
    balanceTags: ['tank', 'win-condition'],
    upgrade: noUpgrade,
    art: 'heavy-tank',
  },
  {
    id: 'support-drone',
    name: 'Spotter',
    description: 'Keeps watch on the frontline, throwing up a shield before the hit lands.',
    category: 'fighter',
    energyCost: 2,
    target: 'deploy-lane',
    tags: ['support', 'tech', 'ranged'],
    unit: {
      deployCount: 1,
      behavior: 'shielder',
      stats: {
        maxHealth: 140,
        attackDamage: 18,
        attackIntervalTicks: secondsToTicks(1.5),
        attackRange: 10,
        moveSpeedPerTick: 0.24,
        isRanged: true,
      },
    },
    balanceTags: ['support', 'cycle'],
    upgrade: noUpgrade,
    art: 'support-drone',
  },
  {
    id: 'blade-runner',
    name: 'Tempo Cutter',
    description: 'Twin-blade skirmisher balancing tempo and cut damage.',
    category: 'fighter',
    energyCost: 5,
    target: 'deploy-lane',
    tags: ['shredder', 'cardio'],
    unit: {
      deployCount: 1,
      stats: {
        maxHealth: 380,
        attackDamage: 60,
        attackIntervalTicks: secondsToTicks(0.9),
        attackRange: 3,
        moveSpeedPerTick: 0.32,
        isRanged: false,
      },
    },
    balanceTags: ['dps', 'duelist'],
    upgrade: noUpgrade,
    art: 'blade-runner',
  },

  // ── Techniques ──────────────────────────────────────────────────────────
  {
    id: 'adrenaline-surge',
    name: 'Adrenaline Surge',
    description: 'Target ally attacks 40% faster and hits 30% harder for 6s.',
    category: 'technique',
    energyCost: 3,
    target: 'friendly-unit',
    tags: [],
    effects: {
      durationTicks: secondsToTicks(6),
      attackDamageMult: 1.3,
      attackIntervalMult: 0.6,
    },
    balanceTags: ['buff', 'tempo'],
    upgrade: noUpgrade,
    art: 'adrenaline-surge',
  },
  {
    id: 'recovery-pulse',
    name: 'Recovery Pulse',
    description: 'Heal all allies in a small area for 180.',
    category: 'technique',
    energyCost: 3,
    target: 'friendly-unit',
    tags: [],
    effects: { heal: 180, radius: 10 },
    balanceTags: ['heal', 'defense'],
    upgrade: noUpgrade,
    art: 'recovery-pulse',
  },
  {
    id: 'overload',
    name: 'Overload',
    description: 'Zap an area for 140 damage and a brief stun.',
    category: 'technique',
    energyCost: 4,
    target: 'enemy-unit',
    tags: ['tech'],
    effects: { damage: 140, radius: 8, stunTicks: secondsToTicks(1) },
    balanceTags: ['aoe', 'control'],
    upgrade: noUpgrade,
    art: 'overload',
  },
  {
    id: 'second-wind',
    name: 'Second Wind',
    description: 'Heal your Champion for 220 and refund 1 energy.',
    category: 'technique',
    energyCost: 2,
    target: 'friendly-champion',
    tags: [],
    effects: { heal: 220, energyRefund: 1 },
    balanceTags: ['heal', 'champion'],
    upgrade: noUpgrade,
    art: 'second-wind',
  },
  {
    id: 'shockwave',
    name: 'Shockwave',
    description: 'Wide blast dealing 90 damage and slowing enemies for 4s.',
    category: 'technique',
    energyCost: 3,
    target: 'enemy-unit',
    tags: [],
    effects: {
      damage: 90,
      radius: 12,
      durationTicks: secondsToTicks(4),
      moveSpeedMult: 0.6,
    },
    balanceTags: ['aoe', 'control', 'defense'],
    upgrade: noUpgrade,
    art: 'shockwave',
  },
  {
    id: 'emergency-shield',
    name: 'Emergency Shield',
    description: 'Grant a 250-point shield to a target ally.',
    category: 'technique',
    energyCost: 2,
    target: 'friendly-unit',
    tags: ['tech'],
    effects: { shield: 250 },
    balanceTags: ['shield', 'defense'],
    upgrade: noUpgrade,
    art: 'emergency-shield',
  },

  // ── Equipment ───────────────────────────────────────────────────────────
  {
    id: 'power-belt',
    name: 'Power Belt',
    description: 'Target ally deals 35% more damage for 15s.',
    category: 'equipment',
    energyCost: 2,
    target: 'friendly-unit',
    // Raw power buff — the Mass Monster's identity in equipment form (a
    // lifting belt), giving the mass line a second card beyond heavy-tank.
    tags: ['mass'],
    effects: { durationTicks: secondsToTicks(15), attackDamageMult: 1.35 },
    balanceTags: ['buff'],
    upgrade: noUpgrade,
    art: 'power-belt',
  },
  {
    id: 'reinforced-armour',
    name: 'Reinforced Armour',
    description: 'Target ally gains 300 max health for 20s.',
    category: 'equipment',
    energyCost: 3,
    target: 'friendly-unit',
    tags: ['titan'],
    effects: { durationTicks: secondsToTicks(20), bonusMaxHealth: 300 },
    balanceTags: ['tank', 'buff'],
    upgrade: noUpgrade,
    art: 'reinforced-armour',
  },
  {
    id: 'neon-blades',
    name: 'Cutting Program',
    description: 'A punishing training tempo — target ally attacks 30% faster for 12s.',
    category: 'equipment',
    energyCost: 2,
    target: 'friendly-unit',
    tags: ['shredder'],
    effects: { durationTicks: secondsToTicks(12), attackIntervalMult: 0.7 },
    balanceTags: ['buff', 'dps'],
    upgrade: noUpgrade,
    art: 'neon-blades',
  },
  {
    id: 'carbon-boots',
    name: 'Carbon Boots',
    description: 'Target ally moves 50% faster for 10s.',
    category: 'equipment',
    energyCost: 1,
    target: 'friendly-unit',
    tags: ['cardio'],
    effects: { durationTicks: secondsToTicks(10), moveSpeedMult: 1.5 },
    balanceTags: ['buff', 'tempo'],
    upgrade: noUpgrade,
    art: 'carbon-boots',
  },
];

export function getCardById(id: string): CardDefinition | undefined {
  return CARDS.find((c) => c.id === id);
}
