/**
 * GENERATED — do not hand-edit. Regenerate with the scratchpad script
 * (gen_library.py) over the public-domain exercise dataset
 * (github.com/yuhonas/free-exercise-db, Unlicense).
 *
 * 848 exercises the hand-curated core (exercise-library.ts) did not
 * already carry. EXACT-NAME DUPLICATES ARE EXCLUDED, case-insensitively: the
 * core's names win, because they are the ones DAY_PRESETS seeds and the ones
 * whose wording the substitution engine was tuned against.
 *
 * The dataset's muscle labels are mapped onto THIS APP'S tag vocabulary (the
 * 17 tags LIBRARY_SECTIONS collapses into six sections). A tag outside that
 * vocabulary would render in no section and be unpickable, so the generator
 * asserts every tag is legal and a test re-asserts it here.
 *
 * "shoulders" and "chest" are split by NAME because the dataset does not
 * distinguish what the app does: a lateral raise is not an overhead press,
 * and an incline press is not a flat one.
 */

/** Structurally a LibraryExercise — declared inline so the generated file
 *  imports nothing and cannot form a cycle with exercise-library.ts. */
export const IMPORTED_EXERCISES: readonly { name: string; muscle: string }[] = [
  { name: '3/4 Sit-Up', muscle: 'Abs' },
  { name: 'Ab Crunch Machine', muscle: 'Abs' },
  { name: 'Ab Roller', muscle: 'Abs' },
  { name: 'Advanced Kettlebell Windmill', muscle: 'Abs' },
  { name: 'Air Bike', muscle: 'Abs' },
  { name: 'Alternate Heel Touchers', muscle: 'Abs' },
  { name: 'Barbell Ab Rollout', muscle: 'Abs' },
  { name: 'Barbell Ab Rollout - On Knees', muscle: 'Abs' },
  { name: 'Barbell Rollout from Bench', muscle: 'Abs' },
  { name: 'Barbell Side Bend', muscle: 'Abs' },
  { name: 'Bent Press', muscle: 'Abs' },
  { name: 'Bent-Knee Hip Raise', muscle: 'Abs' },
  { name: 'Bosu Ball Cable Crunch With Side Bends', muscle: 'Abs' },
  { name: 'Bottoms Up', muscle: 'Abs' },
  { name: 'Butt-Ups', muscle: 'Abs' },
  { name: 'Cable Judo Flip', muscle: 'Abs' },
  { name: 'Cable Reverse Crunch', muscle: 'Abs' },
  { name: 'Cable Russian Twists', muscle: 'Abs' },
  { name: 'Cable Seated Crunch', muscle: 'Abs' },
  { name: 'Cocoons', muscle: 'Abs' },
  { name: 'Cross-Body Crunch', muscle: 'Abs' },
  { name: 'Crunch - Hands Overhead', muscle: 'Abs' },
  { name: 'Crunch - Legs On Exercise Ball', muscle: 'Abs' },
  { name: 'Crunches', muscle: 'Abs' },
  { name: 'Dead Bug', muscle: 'Abs' },
  { name: 'Decline Crunch', muscle: 'Abs' },
  { name: 'Decline Oblique Crunch', muscle: 'Abs' },
  { name: 'Decline Reverse Crunch', muscle: 'Abs' },
  { name: 'Double Kettlebell Windmill', muscle: 'Abs' },
  { name: 'Dumbbell Side Bend', muscle: 'Abs' },
  { name: 'Elbow to Knee', muscle: 'Abs' },
  { name: 'Exercise Ball Crunch', muscle: 'Abs' },
  { name: 'Exercise Ball Pull-In', muscle: 'Abs' },
  { name: 'Flat Bench Leg Pull-In', muscle: 'Abs' },
  { name: 'Flat Bench Lying Leg Raise', muscle: 'Abs' },
  { name: 'Frog Sit-Ups', muscle: 'Abs' },
  { name: 'Gorilla Chin/Crunch', muscle: 'Abs' },
  { name: 'Hanging Pike', muscle: 'Abs' },
  { name: 'Jackknife Sit-Up', muscle: 'Abs' },
  { name: 'Janda Sit-Up', muscle: 'Abs' },
  { name: 'Kettlebell Figure 8', muscle: 'Abs' },
  { name: 'Kettlebell Pass Between The Legs', muscle: 'Abs' },
  { name: 'Kettlebell Windmill', muscle: 'Abs' },
  { name: 'Knee/Hip Raise On Parallel Bars', muscle: 'Abs' },
  { name: 'Kneeling Cable Crunch With Alternating Oblique Twists', muscle: 'Abs' },
  { name: 'Landmine 180’s', muscle: 'Abs' },
  { name: 'Leg Pull-In', muscle: 'Abs' },
  { name: 'Lower Back Curl', muscle: 'Abs' },
  { name: 'Medicine Ball Full Twist', muscle: 'Abs' },
  { name: 'Oblique Crunches', muscle: 'Abs' },
  { name: 'Oblique Crunches - On The Floor', muscle: 'Abs' },
  { name: 'One-Arm High-Pulley Cable Side Bends', muscle: 'Abs' },
  { name: 'One-Arm Medicine Ball Slam', muscle: 'Abs' },
  { name: 'Otis-Up', muscle: 'Abs' },
  { name: 'Overhead Stretch', muscle: 'Abs' },
  { name: 'Pallof Press', muscle: 'Abs' },
  { name: 'Pallof Press With Rotation', muscle: 'Abs' },
  { name: 'Plank', muscle: 'Abs' },
  { name: 'Plate Twist', muscle: 'Abs' },
  { name: 'Press Sit-Up', muscle: 'Abs' },
  { name: 'Reverse Crunch', muscle: 'Abs' },
  { name: 'Rope Crunch', muscle: 'Abs' },
  { name: 'Russian Twist', muscle: 'Abs' },
  { name: 'Scissor Kick', muscle: 'Abs' },
  { name: 'Seated Barbell Twist', muscle: 'Abs' },
  { name: 'Seated Flat Bench Leg Pull-In', muscle: 'Abs' },
  { name: 'Seated Leg Tucks', muscle: 'Abs' },
  { name: 'Seated Overhead Stretch', muscle: 'Abs' },
  { name: 'Side Bridge', muscle: 'Abs' },
  { name: 'Side Jackknife', muscle: 'Abs' },
  { name: 'Sit-Up', muscle: 'Abs' },
  { name: 'Sledgehammer Swings', muscle: 'Abs' },
  { name: 'Smith Machine Hip Raise', muscle: 'Abs' },
  { name: 'Spell Caster', muscle: 'Abs' },
  { name: 'Spider Crawl', muscle: 'Abs' },
  { name: 'Standing Cable Lift', muscle: 'Abs' },
  { name: 'Standing Cable Wood Chop', muscle: 'Abs' },
  { name: 'Standing Lateral Stretch', muscle: 'Abs' },
  { name: 'Standing Rope Crunch', muscle: 'Abs' },
  { name: 'Stomach Vacuum', muscle: 'Abs' },
  { name: 'Supine One-Arm Overhead Throw', muscle: 'Abs' },
  { name: 'Supine Two-Arm Overhead Throw', muscle: 'Abs' },
  { name: 'Suspended Fallout', muscle: 'Abs' },
  { name: 'Suspended Reverse Crunch', muscle: 'Abs' },
  { name: 'Toe Touchers', muscle: 'Abs' },
  { name: 'Torso Rotation', muscle: 'Abs' },
  { name: 'Tuck Crunch', muscle: 'Abs' },
  { name: 'Weighted Ball Side Bend', muscle: 'Abs' },
  { name: 'Weighted Crunches', muscle: 'Abs' },
  { name: 'Weighted Sit-Ups - With Bands', muscle: 'Abs' },
  { name: 'Wind Sprints', muscle: 'Abs' },
  { name: 'Adductor', muscle: 'Adductors' },
  { name: 'Adductor/Groin', muscle: 'Adductors' },
  { name: 'Band Hip Adductions', muscle: 'Adductors' },
  { name: 'Carioca Quick Step', muscle: 'Adductors' },
  { name: 'Groin and Back Stretch', muscle: 'Adductors' },
  { name: 'Groiners', muscle: 'Adductors' },
  { name: 'Hip Circles (prone)', muscle: 'Adductors' },
  { name: 'IT Band and Glute Stretch', muscle: 'Adductors' },
  { name: 'Iliotibial Tract-SMR', muscle: 'Adductors' },
  { name: 'Lateral Bound', muscle: 'Adductors' },
  { name: 'Lateral Box Jump', muscle: 'Adductors' },
  { name: 'Lateral Cone Hops', muscle: 'Adductors' },
  { name: 'Lying Bent Leg Groin', muscle: 'Adductors' },
  { name: 'Lying Crossover', muscle: 'Adductors' },
  { name: 'Monster Walk', muscle: 'Adductors' },
  { name: 'Side Leg Raises', muscle: 'Adductors' },
  { name: 'Side Lying Groin Stretch', muscle: 'Adductors' },
  { name: 'Standing Hip Circles', muscle: 'Adductors' },
  { name: 'Thigh Abductor', muscle: 'Adductors' },
  { name: 'Thigh Adductor', muscle: 'Adductors' },
  { name: 'Windmills', muscle: 'Adductors' },
  { name: 'Alternating Kettlebell Row', muscle: 'Back Thickness' },
  { name: 'Alternating Renegade Row', muscle: 'Back Thickness' },
  { name: 'Atlas Stone Trainer', muscle: 'Back Thickness' },
  { name: 'Atlas Stones', muscle: 'Back Thickness' },
  { name: 'Axle Deadlift', muscle: 'Back Thickness' },
  { name: 'Bent Over Barbell Row', muscle: 'Back Thickness' },
  { name: 'Bent Over One-Arm Long Bar Row', muscle: 'Back Thickness' },
  { name: 'Bent Over Two-Arm Long Bar Row', muscle: 'Back Thickness' },
  { name: 'Bent Over Two-Dumbbell Row', muscle: 'Back Thickness' },
  { name: 'Bent Over Two-Dumbbell Row With Palms In', muscle: 'Back Thickness' },
  { name: 'Bodyweight Mid Row', muscle: 'Back Thickness' },
  { name: 'Cat Stretch', muscle: 'Back Thickness' },
  { name: 'Child’s Pose', muscle: 'Back Thickness' },
  { name: 'Crossover Reverse Lunge', muscle: 'Back Thickness' },
  { name: 'Dancer’s Stretch', muscle: 'Back Thickness' },
  { name: 'Deadlift with Bands', muscle: 'Back Thickness' },
  { name: 'Deadlift with Chains', muscle: 'Back Thickness' },
  { name: 'Deficit Deadlift', muscle: 'Back Thickness' },
  { name: 'Dumbbell Incline Row', muscle: 'Back Thickness' },
  { name: 'Hug A Ball', muscle: 'Back Thickness' },
  { name: 'Hug Knees To Chest', muscle: 'Back Thickness' },
  { name: 'Hyperextensions (Back Extensions)', muscle: 'Back Thickness' },
  { name: 'Hyperextensions With No Hyperextension Bench', muscle: 'Back Thickness' },
  { name: 'Incline Bench Pull', muscle: 'Back Thickness' },
  { name: 'Inverted Row', muscle: 'Back Thickness' },
  { name: 'Inverted Row with Straps', muscle: 'Back Thickness' },
  { name: 'Keg Load', muscle: 'Back Thickness' },
  { name: 'Leverage High Row', muscle: 'Back Thickness' },
  { name: 'Lower Back-SMR', muscle: 'Back Thickness' },
  { name: 'Lying Cambered Barbell Row', muscle: 'Back Thickness' },
  { name: 'Lying T-Bar Row', muscle: 'Back Thickness' },
  { name: 'Middle Back Shrug', muscle: 'Back Thickness' },
  { name: 'Middle Back Stretch', muscle: 'Back Thickness' },
  { name: 'Mixed Grip Chin', muscle: 'Back Thickness' },
  { name: 'One Arm Chin-Up', muscle: 'Back Thickness' },
  { name: 'One-Arm Dumbbell Row', muscle: 'Back Thickness' },
  { name: 'One-Arm Kettlebell Row', muscle: 'Back Thickness' },
  { name: 'One-Arm Long Bar Row', muscle: 'Back Thickness' },
  { name: 'Pelvic Tilt Into Bridge', muscle: 'Back Thickness' },
  { name: 'Pyramid', muscle: 'Back Thickness' },
  { name: 'Rack Pull with Bands', muscle: 'Back Thickness' },
  { name: 'Rack Pulls', muscle: 'Back Thickness' },
  { name: 'Reverse Band Deadlift', muscle: 'Back Thickness' },
  { name: 'Reverse Grip Bent-Over Rows', muscle: 'Back Thickness' },
  { name: 'Rhomboids-SMR', muscle: 'Back Thickness' },
  { name: 'Seated Cable Rows', muscle: 'Back Thickness' },
  { name: 'Seated Good Mornings', muscle: 'Back Thickness' },
  { name: 'Seated One-arm Cable Pulley Rows', muscle: 'Back Thickness' },
  { name: 'Sled Row', muscle: 'Back Thickness' },
  { name: 'Smith Machine Bent Over Row', muscle: 'Back Thickness' },
  { name: 'Spinal Stretch', muscle: 'Back Thickness' },
  { name: 'Standing Pelvic Tilt', muscle: 'Back Thickness' },
  { name: 'Stiff Leg Barbell Good Morning', muscle: 'Back Thickness' },
  { name: 'Straight Bar Bench Mid Rows', muscle: 'Back Thickness' },
  { name: 'Superman', muscle: 'Back Thickness' },
  { name: 'Suspended Row', muscle: 'Back Thickness' },
  { name: 'T-Bar Row with Handle', muscle: 'Back Thickness' },
  { name: 'Two-Arm Kettlebell Row', muscle: 'Back Thickness' },
  { name: 'Upper Back Stretch', muscle: 'Back Thickness' },
  { name: 'Weighted Ball Hyperextension', muscle: 'Back Thickness' },
  { name: 'Band Assisted Pull-Up', muscle: 'Back Width' },
  { name: 'Bent-Arm Barbell Pullover', muscle: 'Back Width' },
  { name: 'Cable Incline Pushdown', muscle: 'Back Width' },
  { name: 'Catch and Overhead Throw', muscle: 'Back Width' },
  { name: 'Chair Lower Back Stretch', muscle: 'Back Width' },
  { name: 'Chin-Up', muscle: 'Back Width' },
  { name: 'Close-Grip Front Lat Pulldown', muscle: 'Back Width' },
  { name: 'Dynamic Back Stretch', muscle: 'Back Width' },
  { name: 'Elevated Cable Rows', muscle: 'Back Width' },
  { name: 'Full Range-Of-Motion Lat Pulldown', muscle: 'Back Width' },
  { name: 'Gironda Sternum Chins', muscle: 'Back Width' },
  { name: 'Kipping Muscle Up', muscle: 'Back Width' },
  { name: 'Kneeling High Pulley Row', muscle: 'Back Width' },
  { name: 'Kneeling Single-Arm High Pulley Row', muscle: 'Back Width' },
  { name: 'Latissimus Dorsi-SMR', muscle: 'Back Width' },
  { name: 'Leverage Iso Row', muscle: 'Back Width' },
  { name: 'London Bridges', muscle: 'Back Width' },
  { name: 'Muscle Up', muscle: 'Back Width' },
  { name: 'One Arm Against Wall', muscle: 'Back Width' },
  { name: 'One Arm Lat Pulldown', muscle: 'Back Width' },
  { name: 'One Handed Hang', muscle: 'Back Width' },
  { name: 'Overhead Lat', muscle: 'Back Width' },
  { name: 'Overhead Slam', muscle: 'Back Width' },
  { name: 'Pullups', muscle: 'Back Width' },
  { name: 'Rocky Pull-Ups/Pulldowns', muscle: 'Back Width' },
  { name: 'Rope Climb', muscle: 'Back Width' },
  { name: 'Rope Straight-Arm Pulldown', muscle: 'Back Width' },
  { name: 'Shotgun Row', muscle: 'Back Width' },
  { name: 'Side To Side Chins', muscle: 'Back Width' },
  { name: 'Side-Lying Floor Stretch', muscle: 'Back Width' },
  { name: 'Straight-Arm Pulldown', muscle: 'Back Width' },
  { name: 'Underhand Cable Pulldowns', muscle: 'Back Width' },
  { name: 'V-Bar Pulldown', muscle: 'Back Width' },
  { name: 'V-Bar Pullup', muscle: 'Back Width' },
  { name: 'Weighted Pull Ups', muscle: 'Back Width' },
  { name: 'Wide-Grip Lat Pulldown', muscle: 'Back Width' },
  { name: 'Wide-Grip Pulldown Behind The Neck', muscle: 'Back Width' },
  { name: 'Wide-Grip Rear Pull-Up', muscle: 'Back Width' },
  { name: 'Alternate Hammer Curl', muscle: 'Biceps' },
  { name: 'Alternate Incline Dumbbell Curl', muscle: 'Biceps' },
  { name: 'Barbell Curls Lying Against An Incline', muscle: 'Biceps' },
  { name: 'Brachialis-SMR', muscle: 'Biceps' },
  { name: 'Cable Hammer Curls - Rope Attachment', muscle: 'Biceps' },
  { name: 'Cable Preacher Curl', muscle: 'Biceps' },
  { name: 'Close-Grip EZ Bar Curl', muscle: 'Biceps' },
  { name: 'Close-Grip EZ-Bar Curl with Band', muscle: 'Biceps' },
  { name: 'Close-Grip Standing Barbell Curl', muscle: 'Biceps' },
  { name: 'Concentration Curls', muscle: 'Biceps' },
  { name: 'Cross Body Hammer Curl', muscle: 'Biceps' },
  { name: 'Drag Curl', muscle: 'Biceps' },
  { name: 'Dumbbell Alternate Bicep Curl', muscle: 'Biceps' },
  { name: 'Dumbbell Bicep Curl', muscle: 'Biceps' },
  { name: 'Dumbbell Prone Incline Curl', muscle: 'Biceps' },
  { name: 'Flexor Incline Dumbbell Curls', muscle: 'Biceps' },
  { name: 'Hammer Curls', muscle: 'Biceps' },
  { name: 'High Cable Curls', muscle: 'Biceps' },
  { name: 'Incline Hammer Curls', muscle: 'Biceps' },
  { name: 'Incline Inner Biceps Curl', muscle: 'Biceps' },
  { name: 'Lying Cable Curl', muscle: 'Biceps' },
  { name: 'Lying Close-Grip Bar Curl On High Pulley', muscle: 'Biceps' },
  { name: 'Lying High Bench Barbell Curl', muscle: 'Biceps' },
  { name: 'Lying Supine Dumbbell Curl', muscle: 'Biceps' },
  { name: 'Machine Bicep Curl', muscle: 'Biceps' },
  { name: 'Machine Preacher Curls', muscle: 'Biceps' },
  { name: 'One Arm Dumbbell Preacher Curl', muscle: 'Biceps' },
  { name: 'Overhead Cable Curl', muscle: 'Biceps' },
  { name: 'Preacher Hammer Dumbbell Curl', muscle: 'Biceps' },
  { name: 'Reverse Barbell Curl', muscle: 'Biceps' },
  { name: 'Reverse Barbell Preacher Curls', muscle: 'Biceps' },
  { name: 'Reverse Cable Curl', muscle: 'Biceps' },
  { name: 'Reverse Plate Curls', muscle: 'Biceps' },
  { name: 'Seated Biceps', muscle: 'Biceps' },
  { name: 'Seated Close-Grip Concentration Barbell Curl', muscle: 'Biceps' },
  { name: 'Seated Dumbbell Curl', muscle: 'Biceps' },
  { name: 'Seated Dumbbell Inner Biceps Curl', muscle: 'Biceps' },
  { name: 'Standing Biceps Cable Curl', muscle: 'Biceps' },
  { name: 'Standing Biceps Stretch', muscle: 'Biceps' },
  { name: 'Standing Concentration Curl', muscle: 'Biceps' },
  { name: 'Standing Dumbbell Reverse Curl', muscle: 'Biceps' },
  { name: 'Standing Inner-Biceps Curl', muscle: 'Biceps' },
  { name: 'Standing One-Arm Cable Curl', muscle: 'Biceps' },
  { name: 'Standing One-Arm Dumbbell Curl Over Incline Bench', muscle: 'Biceps' },
  { name: 'Two-Arm Dumbbell Preacher Curl', muscle: 'Biceps' },
  { name: 'Wide-Grip Standing Barbell Curl', muscle: 'Biceps' },
  { name: 'Zottman Curl', muscle: 'Biceps' },
  { name: 'Zottman Preacher Curl', muscle: 'Biceps' },
  { name: 'Ankle Circles', muscle: 'Calves' },
  { name: 'Anterior Tibialis-SMR', muscle: 'Calves' },
  { name: 'Balance Board', muscle: 'Calves' },
  { name: 'Barbell Seated Calf Raise', muscle: 'Calves' },
  { name: 'Calf Press', muscle: 'Calves' },
  { name: 'Calf Press On The Leg Press Machine', muscle: 'Calves' },
  { name: 'Calf Raise On A Dumbbell', muscle: 'Calves' },
  { name: 'Calf Raises - With Bands', muscle: 'Calves' },
  { name: 'Calf Stretch Elbows Against Wall', muscle: 'Calves' },
  { name: 'Calf Stretch Hands Against Wall', muscle: 'Calves' },
  { name: 'Calves-SMR', muscle: 'Calves' },
  { name: 'Donkey Calf Raises', muscle: 'Calves' },
  { name: 'Dumbbell Seated One-Leg Calf Raise', muscle: 'Calves' },
  { name: 'Foot-SMR', muscle: 'Calves' },
  { name: 'Knee Circles', muscle: 'Calves' },
  { name: 'Peroneals Stretch', muscle: 'Calves' },
  { name: 'Peroneals-SMR', muscle: 'Calves' },
  { name: 'Posterior Tibialis Stretch', muscle: 'Calves' },
  { name: 'Rocking Standing Calf Raise', muscle: 'Calves' },
  { name: 'Seated Calf Stretch', muscle: 'Calves' },
  { name: 'Smith Machine Reverse Calf Raises', muscle: 'Calves' },
  { name: 'Standing Barbell Calf Raise', muscle: 'Calves' },
  { name: 'Standing Calf Raises', muscle: 'Calves' },
  { name: 'Standing Dumbbell Calf Raise', muscle: 'Calves' },
  { name: 'Standing Gastrocnemius Calf Stretch', muscle: 'Calves' },
  { name: 'Standing Soleus And Achilles Stretch', muscle: 'Calves' },
  { name: 'Alternating Floor Press', muscle: 'Chest' },
  { name: 'Around The Worlds', muscle: 'Chest' },
  { name: 'Barbell Bench Press - Medium Grip', muscle: 'Chest' },
  { name: 'Barbell Guillotine Bench Press', muscle: 'Chest' },
  { name: 'Behind Head Chest Stretch', muscle: 'Chest' },
  { name: 'Bench Press - With Bands', muscle: 'Chest' },
  { name: 'Bent-Arm Dumbbell Pullover', muscle: 'Chest' },
  { name: 'Bodyweight Flyes', muscle: 'Chest' },
  { name: 'Butterfly', muscle: 'Chest' },
  { name: 'Cable Chest Press', muscle: 'Chest' },
  { name: 'Cable Crossover', muscle: 'Chest' },
  { name: 'Cable Iron Cross', muscle: 'Chest' },
  { name: 'Chain Press', muscle: 'Chest' },
  { name: 'Chest And Front Of Shoulder Stretch', muscle: 'Chest' },
  { name: 'Chest Push (multiple response)', muscle: 'Chest' },
  { name: 'Chest Push (single response)', muscle: 'Chest' },
  { name: 'Chest Push from 3 point stance', muscle: 'Chest' },
  { name: 'Chest Push with Run Release', muscle: 'Chest' },
  { name: 'Chest Stretch on Stability Ball', muscle: 'Chest' },
  { name: 'Clock Push-Up', muscle: 'Chest' },
  { name: 'Cross Over - With Bands', muscle: 'Chest' },
  { name: 'Decline Dumbbell Bench Press', muscle: 'Chest' },
  { name: 'Decline Dumbbell Flyes', muscle: 'Chest' },
  { name: 'Decline Smith Press', muscle: 'Chest' },
  { name: 'Dips - Chest Version', muscle: 'Chest' },
  { name: 'Drop Push', muscle: 'Chest' },
  { name: 'Dumbbell Bench Press', muscle: 'Chest' },
  { name: 'Dumbbell Bench Press with Neutral Grip', muscle: 'Chest' },
  { name: 'Dumbbell Flyes', muscle: 'Chest' },
  { name: 'Dynamic Chest Stretch', muscle: 'Chest' },
  { name: 'Elbows Back', muscle: 'Chest' },
  { name: 'Extended Range One-Arm Kettlebell Floor Press', muscle: 'Chest' },
  { name: 'Flat Bench Cable Flyes', muscle: 'Chest' },
  { name: 'Forward Drag with Press', muscle: 'Chest' },
  { name: 'Front Raise And Pullover', muscle: 'Chest' },
  { name: 'Heavy Bag Thrust', muscle: 'Chest' },
  { name: 'Isometric Chest Squeezes', muscle: 'Chest' },
  { name: 'Isometric Wipers', muscle: 'Chest' },
  { name: 'Leg-Over Floor Press', muscle: 'Chest' },
  { name: 'Leverage Chest Press', muscle: 'Chest' },
  { name: 'Leverage Decline Chest Press', muscle: 'Chest' },
  { name: 'Low Cable Crossover', muscle: 'Chest' },
  { name: 'Machine Bench Press', muscle: 'Chest' },
  { name: 'Medicine Ball Chest Pass', muscle: 'Chest' },
  { name: 'Neck Press', muscle: 'Chest' },
  { name: 'One Arm Dumbbell Bench Press', muscle: 'Chest' },
  { name: 'One-Arm Flat Bench Dumbbell Flye', muscle: 'Chest' },
  { name: 'One-Arm Kettlebell Floor Press', muscle: 'Chest' },
  { name: 'Plyo Kettlebell Pushups', muscle: 'Chest' },
  { name: 'Plyo Push-up', muscle: 'Chest' },
  { name: 'Push Up to Side Plank', muscle: 'Chest' },
  { name: 'Push-Up Wide', muscle: 'Chest' },
  { name: 'Push-Ups With Feet Elevated', muscle: 'Chest' },
  { name: 'Push-Ups With Feet On An Exercise Ball', muscle: 'Chest' },
  { name: 'Pushups', muscle: 'Chest' },
  { name: 'Pushups (Close and Wide Hand Positions)', muscle: 'Chest' },
  { name: 'Single-Arm Cable Crossover', muscle: 'Chest' },
  { name: 'Single-Arm Push-Up', muscle: 'Chest' },
  { name: 'Smith Machine Decline Press', muscle: 'Chest' },
  { name: 'Standing Cable Chest Press', muscle: 'Chest' },
  { name: 'Straight-Arm Dumbbell Pullover', muscle: 'Chest' },
  { name: 'Suspended Push-Up', muscle: 'Chest' },
  { name: 'Svend Press', muscle: 'Chest' },
  { name: 'Wide-Grip Barbell Bench Press', muscle: 'Chest' },
  { name: 'Wide-Grip Decline Barbell Bench Press', muscle: 'Chest' },
  { name: 'Wide-Grip Decline Barbell Pullover', muscle: 'Chest' },
  { name: 'Bottoms-Up Clean From The Hang Position', muscle: 'Forearms' },
  { name: 'Cable Wrist Curl', muscle: 'Forearms' },
  { name: 'Dumbbell Lying Pronation', muscle: 'Forearms' },
  { name: 'Dumbbell Lying Supination', muscle: 'Forearms' },
  { name: 'Farmer’s Walk', muscle: 'Forearms' },
  { name: 'Finger Curls', muscle: 'Forearms' },
  { name: 'Kneeling Forearm Stretch', muscle: 'Forearms' },
  { name: 'Palms-Down Dumbbell Wrist Curl Over A Bench', muscle: 'Forearms' },
  { name: 'Palms-Down Wrist Curl Over A Bench', muscle: 'Forearms' },
  { name: 'Palms-Up Barbell Wrist Curl Over A Bench', muscle: 'Forearms' },
  { name: 'Palms-Up Dumbbell Wrist Curl Over A Bench', muscle: 'Forearms' },
  { name: 'Plate Pinch', muscle: 'Forearms' },
  { name: 'Rickshaw Carry', muscle: 'Forearms' },
  { name: 'Seated Dumbbell Palms-Down Wrist Curl', muscle: 'Forearms' },
  { name: 'Seated Dumbbell Palms-Up Wrist Curl', muscle: 'Forearms' },
  { name: 'Seated One-Arm Dumbbell Palms-Down Wrist Curl', muscle: 'Forearms' },
  { name: 'Seated One-Arm Dumbbell Palms-Up Wrist Curl', muscle: 'Forearms' },
  { name: 'Seated Palm-Up Barbell Wrist Curl', muscle: 'Forearms' },
  { name: 'Seated Palms-Down Barbell Wrist Curl', muscle: 'Forearms' },
  { name: 'Seated Two-Arm Palms-Up Low-Pulley Wrist Curl', muscle: 'Forearms' },
  { name: 'Standing Olympic Plate Hand Squeeze', muscle: 'Forearms' },
  { name: 'Standing Palms-Up Barbell Behind The Back Wrist Curl', muscle: 'Forearms' },
  { name: 'Wrist Circles', muscle: 'Forearms' },
  { name: 'Wrist Roller', muscle: 'Forearms' },
  { name: 'Wrist Rotations with Straight Bar', muscle: 'Forearms' },
  { name: 'Alternating Cable Shoulder Press', muscle: 'Front Delts' },
  { name: 'Alternating Deltoid Raise', muscle: 'Front Delts' },
  { name: 'Alternating Kettlebell Press', muscle: 'Front Delts' },
  { name: 'Anti-Gravity Press', muscle: 'Front Delts' },
  { name: 'Arm Circles', muscle: 'Front Delts' },
  { name: 'Arnold Dumbbell Press', muscle: 'Front Delts' },
  { name: 'Back Flyes - With Bands', muscle: 'Front Delts' },
  { name: 'Backward Medicine Ball Throw', muscle: 'Front Delts' },
  { name: 'Band Pull Apart', muscle: 'Front Delts' },
  { name: 'Barbell Incline Shoulder Raise', muscle: 'Front Delts' },
  { name: 'Barbell Shoulder Press', muscle: 'Front Delts' },
  { name: 'Battling Ropes', muscle: 'Front Delts' },
  { name: 'Bradford/Rocky Presses', muscle: 'Front Delts' },
  { name: 'Cable Internal Rotation', muscle: 'Front Delts' },
  { name: 'Cable Shoulder Press', muscle: 'Front Delts' },
  { name: 'Car Drivers', muscle: 'Front Delts' },
  { name: 'Chair Upper Body Stretch', muscle: 'Front Delts' },
  { name: 'Circus Bell', muscle: 'Front Delts' },
  { name: 'Clean and Jerk', muscle: 'Front Delts' },
  { name: 'Clean and Press', muscle: 'Front Delts' },
  { name: 'Crucifix', muscle: 'Front Delts' },
  { name: 'Cuban Press', muscle: 'Front Delts' },
  { name: 'Double Kettlebell Jerk', muscle: 'Front Delts' },
  { name: 'Double Kettlebell Push Press', muscle: 'Front Delts' },
  { name: 'Double Kettlebell Snatch', muscle: 'Front Delts' },
  { name: 'Dumbbell Incline Shoulder Raise', muscle: 'Front Delts' },
  { name: 'Dumbbell One-Arm Shoulder Press', muscle: 'Front Delts' },
  { name: 'Dumbbell Raise', muscle: 'Front Delts' },
  { name: 'Dumbbell Scaption', muscle: 'Front Delts' },
  { name: 'Dumbbell Shoulder Press', muscle: 'Front Delts' },
  { name: 'Elbow Circles', muscle: 'Front Delts' },
  { name: 'External Rotation', muscle: 'Front Delts' },
  { name: 'External Rotation with Band', muscle: 'Front Delts' },
  { name: 'External Rotation with Cable', muscle: 'Front Delts' },
  { name: 'Front Cable Raise', muscle: 'Front Delts' },
  { name: 'Front Dumbbell Raise', muscle: 'Front Delts' },
  { name: 'Front Incline Dumbbell Raise', muscle: 'Front Delts' },
  { name: 'Front Plate Raise', muscle: 'Front Delts' },
  { name: 'Front Two-Dumbbell Raise', muscle: 'Front Delts' },
  { name: 'Handstand Push-Ups', muscle: 'Front Delts' },
  { name: 'Internal Rotation with Band', muscle: 'Front Delts' },
  { name: 'Iron Cross', muscle: 'Front Delts' },
  { name: 'Jerk Balance', muscle: 'Front Delts' },
  { name: 'Kettlebell Arnold Press', muscle: 'Front Delts' },
  { name: 'Kettlebell Pirate Ships', muscle: 'Front Delts' },
  { name: 'Kettlebell Seated Press', muscle: 'Front Delts' },
  { name: 'Kettlebell Seesaw Press', muscle: 'Front Delts' },
  { name: 'Kettlebell Thruster', muscle: 'Front Delts' },
  { name: 'Kettlebell Turkish Get-Up (Lunge style)', muscle: 'Front Delts' },
  { name: 'Kettlebell Turkish Get-Up (Squat style)', muscle: 'Front Delts' },
  { name: 'Kneeling Arm Drill', muscle: 'Front Delts' },
  { name: 'Landmine Linear Jammer', muscle: 'Front Delts' },
  { name: 'Leverage Shoulder Press', muscle: 'Front Delts' },
  { name: 'Log Lift', muscle: 'Front Delts' },
  { name: 'Low Pulley Row To Neck', muscle: 'Front Delts' },
  { name: 'Machine Shoulder (Military) Press', muscle: 'Front Delts' },
  { name: 'Medicine Ball Scoop Throw', muscle: 'Front Delts' },
  { name: 'One-Arm Kettlebell Clean and Jerk', muscle: 'Front Delts' },
  { name: 'One-Arm Kettlebell Jerk', muscle: 'Front Delts' },
  { name: 'One-Arm Kettlebell Para Press', muscle: 'Front Delts' },
  { name: 'One-Arm Kettlebell Push Press', muscle: 'Front Delts' },
  { name: 'One-Arm Kettlebell Snatch', muscle: 'Front Delts' },
  { name: 'One-Arm Kettlebell Split Jerk', muscle: 'Front Delts' },
  { name: 'One-Arm Kettlebell Split Snatch', muscle: 'Front Delts' },
  { name: 'Power Partials', muscle: 'Front Delts' },
  { name: 'Push Press', muscle: 'Front Delts' },
  { name: 'Push Press - Behind the Neck', muscle: 'Front Delts' },
  { name: 'Rack Delivery', muscle: 'Front Delts' },
  { name: 'Return Push from Stance', muscle: 'Front Delts' },
  { name: 'Round The World Shoulder Stretch', muscle: 'Front Delts' },
  { name: 'Seated Barbell Military Press', muscle: 'Front Delts' },
  { name: 'Seated Cable Shoulder Press', muscle: 'Front Delts' },
  { name: 'Seated Dumbbell Press', muscle: 'Front Delts' },
  { name: 'Seated Front Deltoid', muscle: 'Front Delts' },
  { name: 'Shoulder Circles', muscle: 'Front Delts' },
  { name: 'Shoulder Press - With Bands', muscle: 'Front Delts' },
  { name: 'Shoulder Raise', muscle: 'Front Delts' },
  { name: 'Shoulder Stretch', muscle: 'Front Delts' },
  { name: 'Single Dumbbell Raise', muscle: 'Front Delts' },
  { name: 'Single-Arm Linear Jammer', muscle: 'Front Delts' },
  { name: 'Sled Overhead Backward Walk', muscle: 'Front Delts' },
  { name: 'Smith Incline Shoulder Raise', muscle: 'Front Delts' },
  { name: 'Smith Machine Overhead Shoulder Press', muscle: 'Front Delts' },
  { name: 'Standing Alternating Dumbbell Press', muscle: 'Front Delts' },
  { name: 'Standing Barbell Press Behind Neck', muscle: 'Front Delts' },
  { name: 'Standing Bradford Press', muscle: 'Front Delts' },
  { name: 'Standing Dumbbell Press', muscle: 'Front Delts' },
  { name: 'Standing Dumbbell Straight-Arm Front Delt Raise Above Head', muscle: 'Front Delts' },
  { name: 'Standing Front Barbell Raise Over Head', muscle: 'Front Delts' },
  { name: 'Standing Low-Pulley Deltoid Raise', muscle: 'Front Delts' },
  { name: 'Standing Military Press', muscle: 'Front Delts' },
  { name: 'Standing Palm-In One-Arm Dumbbell Press', muscle: 'Front Delts' },
  { name: 'Standing Palms-In Dumbbell Press', muscle: 'Front Delts' },
  { name: 'Standing Two-Arm Overhead Throw', muscle: 'Front Delts' },
  { name: 'Straight Raises on Incline Bench', muscle: 'Front Delts' },
  { name: 'Two-Arm Kettlebell Clean', muscle: 'Front Delts' },
  { name: 'Two-Arm Kettlebell Jerk', muscle: 'Front Delts' },
  { name: 'Two-Arm Kettlebell Military Press', muscle: 'Front Delts' },
  { name: 'Upright Barbell Row', muscle: 'Front Delts' },
  { name: 'Upward Stretch', muscle: 'Front Delts' },
  { name: 'Ankle On The Knee', muscle: 'Glutes' },
  { name: 'Barbell Glute Bridge', muscle: 'Glutes' },
  { name: 'Butt Lift (Bridge)', muscle: 'Glutes' },
  { name: 'Downward Facing Balance', muscle: 'Glutes' },
  { name: 'Flutter Kicks', muscle: 'Glutes' },
  { name: 'Glute Kickback', muscle: 'Glutes' },
  { name: 'Hip Extension with Bands', muscle: 'Glutes' },
  { name: 'Hip Lift with Band', muscle: 'Glutes' },
  { name: 'Knee Across The Body', muscle: 'Glutes' },
  { name: 'Kneeling Jump Squat', muscle: 'Glutes' },
  { name: 'Kneeling Squat', muscle: 'Glutes' },
  { name: 'Leg Lift', muscle: 'Glutes' },
  { name: 'Lying Glute', muscle: 'Glutes' },
  { name: 'One Knee To Chest', muscle: 'Glutes' },
  { name: 'One-Legged Cable Kickback', muscle: 'Glutes' },
  { name: 'Physioball Hip Bridge', muscle: 'Glutes' },
  { name: 'Piriformis-SMR', muscle: 'Glutes' },
  { name: 'Pull Through', muscle: 'Glutes' },
  { name: 'Seated Glute', muscle: 'Glutes' },
  { name: 'Single Leg Glute Bridge', muscle: 'Glutes' },
  { name: 'Step-up with Knee Raise', muscle: 'Glutes' },
  { name: '90/90 Hamstring', muscle: 'Hamstrings' },
  { name: 'Alternating Hang Clean', muscle: 'Hamstrings' },
  { name: 'Ball Leg Curl', muscle: 'Hamstrings' },
  { name: 'Band Good Morning', muscle: 'Hamstrings' },
  { name: 'Band Good Morning (Pull Through)', muscle: 'Hamstrings' },
  { name: 'Box Jump (Multiple Response)', muscle: 'Hamstrings' },
  { name: 'Box Skip', muscle: 'Hamstrings' },
  { name: 'Chair Leg Extended Stretch', muscle: 'Hamstrings' },
  { name: 'Clean', muscle: 'Hamstrings' },
  { name: 'Clean Deadlift', muscle: 'Hamstrings' },
  { name: 'Double Kettlebell Alternating Hang Clean', muscle: 'Hamstrings' },
  { name: 'Dumbbell Clean', muscle: 'Hamstrings' },
  { name: 'Floor Glute-Ham Raise', muscle: 'Hamstrings' },
  { name: 'Front Box Jump', muscle: 'Hamstrings' },
  { name: 'Front Leg Raises', muscle: 'Hamstrings' },
  { name: 'Glute Ham Raise', muscle: 'Hamstrings' },
  { name: 'Good Morning off Pins', muscle: 'Hamstrings' },
  { name: 'Hamstring Stretch', muscle: 'Hamstrings' },
  { name: 'Hamstring-SMR', muscle: 'Hamstrings' },
  { name: 'Hang Snatch', muscle: 'Hamstrings' },
  { name: 'Hang Snatch - Below Knees', muscle: 'Hamstrings' },
  { name: 'Hanging Bar Good Morning', muscle: 'Hamstrings' },
  { name: 'Hurdle Hops', muscle: 'Hamstrings' },
  { name: 'Inchworm', muscle: 'Hamstrings' },
  { name: 'Intermediate Groin Stretch', muscle: 'Hamstrings' },
  { name: 'Kettlebell Dead Clean', muscle: 'Hamstrings' },
  { name: 'Kettlebell Hang Clean', muscle: 'Hamstrings' },
  { name: 'Kettlebell One-Legged Deadlift', muscle: 'Hamstrings' },
  { name: 'Knee Tuck Jump', muscle: 'Hamstrings' },
  { name: 'Leg-Up Hamstring Stretch', muscle: 'Hamstrings' },
  { name: 'Linear 3-Part Start Technique', muscle: 'Hamstrings' },
  { name: 'Linear Acceleration Wall Drill', muscle: 'Hamstrings' },
  { name: 'Lunge Pass Through', muscle: 'Hamstrings' },
  { name: 'Lying Hamstring', muscle: 'Hamstrings' },
  { name: 'Lying Leg Curls', muscle: 'Hamstrings' },
  { name: 'Moving Claw Series', muscle: 'Hamstrings' },
  { name: 'Muscle Snatch', muscle: 'Hamstrings' },
  { name: 'Natural Glute Ham Raise', muscle: 'Hamstrings' },
  { name: 'One-Arm Kettlebell Clean', muscle: 'Hamstrings' },
  { name: 'One-Arm Kettlebell Swings', muscle: 'Hamstrings' },
  { name: 'One-Arm Open Palm Kettlebell Clean', muscle: 'Hamstrings' },
  { name: 'Open Palm Kettlebell Clean', muscle: 'Hamstrings' },
  { name: 'Platform Hamstring Slides', muscle: 'Hamstrings' },
  { name: 'Power Clean', muscle: 'Hamstrings' },
  { name: 'Power Clean from Blocks', muscle: 'Hamstrings' },
  { name: 'Power Snatch', muscle: 'Hamstrings' },
  { name: 'Power Stairs', muscle: 'Hamstrings' },
  { name: 'Prone Manual Hamstring', muscle: 'Hamstrings' },
  { name: 'Prowler Sprint', muscle: 'Hamstrings' },
  { name: 'Reverse Band Sumo Deadlift', muscle: 'Hamstrings' },
  { name: 'Reverse Hyperextension', muscle: 'Hamstrings' },
  { name: 'Romanian Deadlift from Deficit', muscle: 'Hamstrings' },
  { name: 'Runner’s Stretch', muscle: 'Hamstrings' },
  { name: 'Seated Band Hamstring Curl', muscle: 'Hamstrings' },
  { name: 'Seated Floor Hamstring Stretch', muscle: 'Hamstrings' },
  { name: 'Seated Hamstring', muscle: 'Hamstrings' },
  { name: 'Seated Hamstring and Calf Stretch', muscle: 'Hamstrings' },
  { name: 'Smith Machine Hang Power Clean', muscle: 'Hamstrings' },
  { name: 'Smith Machine Stiff-Legged Deadlift', muscle: 'Hamstrings' },
  { name: 'Snatch Deadlift', muscle: 'Hamstrings' },
  { name: 'Snatch Pull', muscle: 'Hamstrings' },
  { name: 'Split Snatch', muscle: 'Hamstrings' },
  { name: 'Split Squats', muscle: 'Hamstrings' },
  { name: 'Standing Hamstring and Calf Stretch', muscle: 'Hamstrings' },
  { name: 'Standing Leg Curl', muscle: 'Hamstrings' },
  { name: 'Standing Toe Touches', muscle: 'Hamstrings' },
  { name: 'Stiff-Legged Barbell Deadlift', muscle: 'Hamstrings' },
  { name: 'Stiff-Legged Dumbbell Deadlift', muscle: 'Hamstrings' },
  { name: 'Sumo Deadlift', muscle: 'Hamstrings' },
  { name: 'Sumo Deadlift with Bands', muscle: 'Hamstrings' },
  { name: 'Sumo Deadlift with Chains', muscle: 'Hamstrings' },
  { name: 'The Straddle', muscle: 'Hamstrings' },
  { name: 'Upper Back-Leg Grab', muscle: 'Hamstrings' },
  { name: 'Vertical Swing', muscle: 'Hamstrings' },
  { name: 'Wide Stance Stiff Legs', muscle: 'Hamstrings' },
  { name: 'World’s Greatest Stretch', muscle: 'Hamstrings' },
  { name: 'All Fours Quad Stretch', muscle: 'Quads' },
  { name: 'Alternate Leg Diagonal Bound', muscle: 'Quads' },
  { name: 'Backward Drag', muscle: 'Quads' },
  { name: 'Barbell Full Squat', muscle: 'Quads' },
  { name: 'Barbell Hack Squat', muscle: 'Quads' },
  { name: 'Barbell Lunge', muscle: 'Quads' },
  { name: 'Barbell Side Split Squat', muscle: 'Quads' },
  { name: 'Barbell Squat', muscle: 'Quads' },
  { name: 'Barbell Squat To A Bench', muscle: 'Quads' },
  { name: 'Barbell Step Ups', muscle: 'Quads' },
  { name: 'Barbell Walking Lunge', muscle: 'Quads' },
  { name: 'Bear Crawl Sled Drags', muscle: 'Quads' },
  { name: 'Bench Jump', muscle: 'Quads' },
  { name: 'Bench Sprint', muscle: 'Quads' },
  { name: 'Bicycling', muscle: 'Quads' },
  { name: 'Bicycling, Stationary', muscle: 'Quads' },
  { name: 'Bodyweight Squat', muscle: 'Quads' },
  { name: 'Bodyweight Walking Lunge', muscle: 'Quads' },
  { name: 'Box Squat', muscle: 'Quads' },
  { name: 'Box Squat with Bands', muscle: 'Quads' },
  { name: 'Box Squat with Chains', muscle: 'Quads' },
  { name: 'Cable Deadlifts', muscle: 'Quads' },
  { name: 'Cable Hip Adduction', muscle: 'Quads' },
  { name: 'Car Deadlift', muscle: 'Quads' },
  { name: 'Chair Squat', muscle: 'Quads' },
  { name: 'Clean Pull', muscle: 'Quads' },
  { name: 'Clean from Blocks', muscle: 'Quads' },
  { name: 'Conan’s Wheel', muscle: 'Quads' },
  { name: 'Depth Jump Leap', muscle: 'Quads' },
  { name: 'Double Leg Butt Kick', muscle: 'Quads' },
  { name: 'Dumbbell Lunges', muscle: 'Quads' },
  { name: 'Dumbbell Rear Lunge', muscle: 'Quads' },
  { name: 'Dumbbell Seated Box Jump', muscle: 'Quads' },
  { name: 'Dumbbell Squat', muscle: 'Quads' },
  { name: 'Dumbbell Squat To A Bench', muscle: 'Quads' },
  { name: 'Dumbbell Step Ups', muscle: 'Quads' },
  { name: 'Elevated Back Lunge', muscle: 'Quads' },
  { name: 'Elliptical Trainer', muscle: 'Quads' },
  { name: 'Fast Skipping', muscle: 'Quads' },
  { name: 'Frankenstein Squat', muscle: 'Quads' },
  { name: 'Freehand Jump Squat', muscle: 'Quads' },
  { name: 'Frog Hops', muscle: 'Quads' },
  { name: 'Front Barbell Squat', muscle: 'Quads' },
  { name: 'Front Barbell Squat To A Bench', muscle: 'Quads' },
  { name: 'Front Cone Hops (or hurdle hops)', muscle: 'Quads' },
  { name: 'Front Squat (Clean Grip)', muscle: 'Quads' },
  { name: 'Front Squats With Two Kettlebells', muscle: 'Quads' },
  { name: 'Hack Squat', muscle: 'Quads' },
  { name: 'Hang Clean', muscle: 'Quads' },
  { name: 'Hang Clean - Below the Knees', muscle: 'Quads' },
  { name: 'Heaving Snatch Balance', muscle: 'Quads' },
  { name: 'Hip Flexion with Band', muscle: 'Quads' },
  { name: 'Intermediate Hip Flexor and Quad Stretch', muscle: 'Quads' },
  { name: 'Iron Crosses (stretch)', muscle: 'Quads' },
  { name: 'Jefferson Squats', muscle: 'Quads' },
  { name: 'Jerk Dip Squat', muscle: 'Quads' },
  { name: 'Jogging, Treadmill', muscle: 'Quads' },
  { name: 'Kettlebell Pistol Squat', muscle: 'Quads' },
  { name: 'Kneeling Hip Flexor', muscle: 'Quads' },
  { name: 'Leg Extensions', muscle: 'Quads' },
  { name: 'Leverage Deadlift', muscle: 'Quads' },
  { name: 'Linear Depth Jump', muscle: 'Quads' },
  { name: 'Looking At Ceiling', muscle: 'Quads' },
  { name: 'Lunge Sprint', muscle: 'Quads' },
  { name: 'Lying Machine Squat', muscle: 'Quads' },
  { name: 'Lying Prone Quadriceps', muscle: 'Quads' },
  { name: 'Mountain Climbers', muscle: 'Quads' },
  { name: 'Narrow Stance Hack Squats', muscle: 'Quads' },
  { name: 'Narrow Stance Leg Press', muscle: 'Quads' },
  { name: 'Narrow Stance Squats', muscle: 'Quads' },
  { name: 'Olympic Squat', muscle: 'Quads' },
  { name: 'On Your Side Quad Stretch', muscle: 'Quads' },
  { name: 'On-Your-Back Quad Stretch', muscle: 'Quads' },
  { name: 'One Half Locust', muscle: 'Quads' },
  { name: 'One Leg Barbell Squat', muscle: 'Quads' },
  { name: 'One-Arm Overhead Kettlebell Squats', muscle: 'Quads' },
  { name: 'One-Arm Side Deadlift', muscle: 'Quads' },
  { name: 'Overhead Squat', muscle: 'Quads' },
  { name: 'Plie Dumbbell Squat', muscle: 'Quads' },
  { name: 'Power Jerk', muscle: 'Quads' },
  { name: 'Power Snatch from Blocks', muscle: 'Quads' },
  { name: 'Quad Stretch', muscle: 'Quads' },
  { name: 'Quadriceps-SMR', muscle: 'Quads' },
  { name: 'Quick Leap', muscle: 'Quads' },
  { name: 'Rear Leg Raises', muscle: 'Quads' },
  { name: 'Recumbent Bike', muscle: 'Quads' },
  { name: 'Reverse Band Box Squat', muscle: 'Quads' },
  { name: 'Reverse Band Power Squat', muscle: 'Quads' },
  { name: 'Rickshaw Deadlift', muscle: 'Quads' },
  { name: 'Rocket Jump', muscle: 'Quads' },
  { name: 'Rope Jumping', muscle: 'Quads' },
  { name: 'Rowing, Stationary', muscle: 'Quads' },
  { name: 'Running, Treadmill', muscle: 'Quads' },
  { name: 'Sandbag Load', muscle: 'Quads' },
  { name: 'Scissors Jump', muscle: 'Quads' },
  { name: 'Side Hop-Sprint', muscle: 'Quads' },
  { name: 'Side Standing Long Jump', muscle: 'Quads' },
  { name: 'Side to Side Box Shuffle', muscle: 'Quads' },
  { name: 'Single Leg Butt Kick', muscle: 'Quads' },
  { name: 'Single Leg Push-off', muscle: 'Quads' },
  { name: 'Single-Cone Sprint Drill', muscle: 'Quads' },
  { name: 'Single-Leg High Box Squat', muscle: 'Quads' },
  { name: 'Single-Leg Hop Progression', muscle: 'Quads' },
  { name: 'Single-Leg Lateral Hop', muscle: 'Quads' },
  { name: 'Single-Leg Leg Extension', muscle: 'Quads' },
  { name: 'Single-Leg Stride Jump', muscle: 'Quads' },
  { name: 'Sit Squats', muscle: 'Quads' },
  { name: 'Skating', muscle: 'Quads' },
  { name: 'Sled Drag - Harness', muscle: 'Quads' },
  { name: 'Sled Push', muscle: 'Quads' },
  { name: 'Smith Machine Leg Press', muscle: 'Quads' },
  { name: 'Smith Machine Pistol Squat', muscle: 'Quads' },
  { name: 'Smith Single-Leg Split Squat', muscle: 'Quads' },
  { name: 'Snatch', muscle: 'Quads' },
  { name: 'Snatch Balance', muscle: 'Quads' },
  { name: 'Snatch from Blocks', muscle: 'Quads' },
  { name: 'Speed Box Squat', muscle: 'Quads' },
  { name: 'Speed Squats', muscle: 'Quads' },
  { name: 'Split Clean', muscle: 'Quads' },
  { name: 'Split Jerk', muscle: 'Quads' },
  { name: 'Split Jump', muscle: 'Quads' },
  { name: 'Split Squat with Dumbbells', muscle: 'Quads' },
  { name: 'Squat Jerk', muscle: 'Quads' },
  { name: 'Squat with Bands', muscle: 'Quads' },
  { name: 'Squat with Chains', muscle: 'Quads' },
  { name: 'Squat with Plate Movers', muscle: 'Quads' },
  { name: 'Squats - With Bands', muscle: 'Quads' },
  { name: 'Stairmaster', muscle: 'Quads' },
  { name: 'Standing Elevated Quad Stretch', muscle: 'Quads' },
  { name: 'Standing Hip Flexors', muscle: 'Quads' },
  { name: 'Standing Long Jump', muscle: 'Quads' },
  { name: 'Star Jump', muscle: 'Quads' },
  { name: 'Step Mill', muscle: 'Quads' },
  { name: 'Stride Jump Crossover', muscle: 'Quads' },
  { name: 'Suspended Split Squat', muscle: 'Quads' },
  { name: 'Tire Flip', muscle: 'Quads' },
  { name: 'Trail Running/Walking', muscle: 'Quads' },
  { name: 'Trap Bar Deadlift', muscle: 'Quads' },
  { name: 'Walking, Treadmill', muscle: 'Quads' },
  { name: 'Weighted Jump Squat', muscle: 'Quads' },
  { name: 'Weighted Sissy Squat', muscle: 'Quads' },
  { name: 'Weighted Squat', muscle: 'Quads' },
  { name: 'Wide Stance Barbell Squat', muscle: 'Quads' },
  { name: 'Yoke Walk', muscle: 'Quads' },
  { name: 'Zercher Squats', muscle: 'Quads' },
  { name: 'Barbell Rear Delt Row', muscle: 'Rear Delts' },
  { name: 'Bent Over Dumbbell Rear Delt Raise With Head On Bench', muscle: 'Rear Delts' },
  { name: 'Cable Rope Rear-Delt Rows', muscle: 'Rear Delts' },
  { name: 'Dumbbell Lying One-Arm Rear Lateral Raise', muscle: 'Rear Delts' },
  { name: 'Dumbbell Lying Rear Lateral Raise', muscle: 'Rear Delts' },
  { name: 'Lying Rear Delt Raise', muscle: 'Rear Delts' },
  { name: 'Reverse Flyes', muscle: 'Rear Delts' },
  { name: 'Reverse Flyes With External Rotation', muscle: 'Rear Delts' },
  { name: 'Reverse Machine Flyes', muscle: 'Rear Delts' },
  { name: 'Seated Bent-Over Rear Delt Raise', muscle: 'Rear Delts' },
  { name: 'Sled Reverse Flye', muscle: 'Rear Delts' },
  { name: 'Bent Over Low-Pulley Side Lateral', muscle: 'Side Delts' },
  { name: 'Cable Seated Lateral Raise', muscle: 'Side Delts' },
  { name: 'Dumbbell One-Arm Upright Row', muscle: 'Side Delts' },
  { name: 'Lateral Raise - With Bands', muscle: 'Side Delts' },
  { name: 'Lying One-Arm Lateral Raise', muscle: 'Side Delts' },
  { name: 'One-Arm Incline Lateral Raise', muscle: 'Side Delts' },
  { name: 'One-Arm Kettlebell Military Press To The Side', muscle: 'Side Delts' },
  { name: 'One-Arm Side Laterals', muscle: 'Side Delts' },
  { name: 'Seated Side Lateral Raise', muscle: 'Side Delts' },
  { name: 'See-Saw Press (Alternating Side Press)', muscle: 'Side Delts' },
  { name: 'Side Lateral Raise', muscle: 'Side Delts' },
  { name: 'Side Laterals to Front Raise', muscle: 'Side Delts' },
  { name: 'Side Wrist Pull', muscle: 'Side Delts' },
  { name: 'Smith Machine One-Arm Upright Row', muscle: 'Side Delts' },
  { name: 'Barbell Shrug Behind The Back', muscle: 'Traps' },
  { name: 'Cable Shrugs', muscle: 'Traps' },
  { name: 'Calf-Machine Shoulder Shrug', muscle: 'Traps' },
  { name: 'Chin To Chest Stretch', muscle: 'Traps' },
  { name: 'Clean Shrug', muscle: 'Traps' },
  { name: 'Isometric Neck Exercise - Front And Back', muscle: 'Traps' },
  { name: 'Isometric Neck Exercise - Sides', muscle: 'Traps' },
  { name: 'Kettlebell Sumo High Pull', muscle: 'Traps' },
  { name: 'Leverage Shrug', muscle: 'Traps' },
  { name: 'Lying Face Down Plate Neck Resistance', muscle: 'Traps' },
  { name: 'Lying Face Up Plate Neck Resistance', muscle: 'Traps' },
  { name: 'Neck-SMR', muscle: 'Traps' },
  { name: 'Scapular Pull-Up', muscle: 'Traps' },
  { name: 'Seated Head Harness Neck Resistance', muscle: 'Traps' },
  { name: 'Side Neck Stretch', muscle: 'Traps' },
  { name: 'Smith Machine Behind the Back Shrug', muscle: 'Traps' },
  { name: 'Smith Machine Upright Row', muscle: 'Traps' },
  { name: 'Snatch Shrug', muscle: 'Traps' },
  { name: 'Standing Dumbbell Upright Row', muscle: 'Traps' },
  { name: 'Upright Cable Row', muscle: 'Traps' },
  { name: 'Upright Row - With Bands', muscle: 'Traps' },
  { name: 'Band Skull Crusher', muscle: 'Triceps' },
  { name: 'Bench Dips', muscle: 'Triceps' },
  { name: 'Bench Press - Powerlifting', muscle: 'Triceps' },
  { name: 'Bench Press with Chains', muscle: 'Triceps' },
  { name: 'Board Press', muscle: 'Triceps' },
  { name: 'Body Tricep Press', muscle: 'Triceps' },
  { name: 'Body-Up', muscle: 'Triceps' },
  { name: 'Cable Incline Triceps Extension', muscle: 'Triceps' },
  { name: 'Cable Lying Triceps Extension', muscle: 'Triceps' },
  { name: 'Cable One Arm Tricep Extension', muscle: 'Triceps' },
  { name: 'Cable Rope Overhead Triceps Extension', muscle: 'Triceps' },
  { name: 'Chain Handle Extension', muscle: 'Triceps' },
  { name: 'Close-Grip Barbell Bench Press', muscle: 'Triceps' },
  { name: 'Close-Grip Dumbbell Press', muscle: 'Triceps' },
  { name: 'Close-Grip EZ-Bar Press', muscle: 'Triceps' },
  { name: 'Close-Grip Push-Up off of a Dumbbell', muscle: 'Triceps' },
  { name: 'Decline Close-Grip Bench To Skull Crusher', muscle: 'Triceps' },
  { name: 'Decline Dumbbell Triceps Extension', muscle: 'Triceps' },
  { name: 'Decline EZ Bar Triceps Extension', muscle: 'Triceps' },
  { name: 'Dip Machine', muscle: 'Triceps' },
  { name: 'Dips - Triceps Version', muscle: 'Triceps' },
  { name: 'Dumbbell Floor Press', muscle: 'Triceps' },
  { name: 'Dumbbell One-Arm Triceps Extension', muscle: 'Triceps' },
  { name: 'Dumbbell Tricep Extension -Pronated Grip', muscle: 'Triceps' },
  { name: 'EZ-Bar Skullcrusher', muscle: 'Triceps' },
  { name: 'Floor Press', muscle: 'Triceps' },
  { name: 'Floor Press with Chains', muscle: 'Triceps' },
  { name: 'Incline Barbell Triceps Extension', muscle: 'Triceps' },
  { name: 'Incline Push-Up Close-Grip', muscle: 'Triceps' },
  { name: 'JM Press', muscle: 'Triceps' },
  { name: 'Kneeling Cable Triceps Extension', muscle: 'Triceps' },
  { name: 'Low Cable Triceps Extension', muscle: 'Triceps' },
  { name: 'Lying Close-Grip Barbell Triceps Extension Behind The Head', muscle: 'Triceps' },
  { name: 'Lying Close-Grip Barbell Triceps Press To Chin', muscle: 'Triceps' },
  { name: 'Lying Dumbbell Tricep Extension', muscle: 'Triceps' },
  { name: 'Lying Triceps Press', muscle: 'Triceps' },
  { name: 'One Arm Floor Press', muscle: 'Triceps' },
  { name: 'One Arm Pronated Dumbbell Triceps Extension', muscle: 'Triceps' },
  { name: 'One Arm Supinated Dumbbell Triceps Extension', muscle: 'Triceps' },
  { name: 'Overhead Triceps', muscle: 'Triceps' },
  { name: 'Parallel Bar Dip', muscle: 'Triceps' },
  { name: 'Pin Presses', muscle: 'Triceps' },
  { name: 'Push-Ups - Close Triceps Position', muscle: 'Triceps' },
  { name: 'Reverse Band Bench Press', muscle: 'Triceps' },
  { name: 'Reverse Grip Triceps Pushdown', muscle: 'Triceps' },
  { name: 'Reverse Triceps Bench Press', muscle: 'Triceps' },
  { name: 'Ring Dips', muscle: 'Triceps' },
  { name: 'Seated Bent-Over One-Arm Dumbbell Triceps Extension', muscle: 'Triceps' },
  { name: 'Seated Bent-Over Two-Arm Dumbbell Triceps Extension', muscle: 'Triceps' },
  { name: 'Seated Triceps Press', muscle: 'Triceps' },
  { name: 'Sled Overhead Triceps Extension', muscle: 'Triceps' },
  { name: 'Smith Machine Close-Grip Bench Press', muscle: 'Triceps' },
  { name: 'Speed Band Overhead Triceps', muscle: 'Triceps' },
  { name: 'Standing Bent-Over One-Arm Dumbbell Triceps Extension', muscle: 'Triceps' },
  { name: 'Standing Bent-Over Two-Arm Dumbbell Triceps Extension', muscle: 'Triceps' },
  { name: 'Standing Dumbbell Triceps Extension', muscle: 'Triceps' },
  { name: 'Standing Low-Pulley One-Arm Triceps Extension', muscle: 'Triceps' },
  { name: 'Standing One-Arm Dumbbell Triceps Extension', muscle: 'Triceps' },
  { name: 'Standing Overhead Barbell Triceps Extension', muscle: 'Triceps' },
  { name: 'Standing Towel Triceps Extension', muscle: 'Triceps' },
  { name: 'Supine Chest Throw', muscle: 'Triceps' },
  { name: 'Tate Press', muscle: 'Triceps' },
  { name: 'Tricep Dumbbell Kickback', muscle: 'Triceps' },
  { name: 'Tricep Side Stretch', muscle: 'Triceps' },
  { name: 'Triceps Overhead Extension with Rope', muscle: 'Triceps' },
  { name: 'Triceps Pushdown', muscle: 'Triceps' },
  { name: 'Triceps Pushdown - Rope Attachment', muscle: 'Triceps' },
  { name: 'Triceps Pushdown - V-Bar Attachment', muscle: 'Triceps' },
  { name: 'Triceps Stretch', muscle: 'Triceps' },
  { name: 'Weighted Bench Dip', muscle: 'Triceps' },
  { name: 'Barbell Incline Bench Press - Medium Grip', muscle: 'Upper Chest' },
  { name: 'Hammer Grip Incline DB Bench Press', muscle: 'Upper Chest' },
  { name: 'Incline Cable Chest Press', muscle: 'Upper Chest' },
  { name: 'Incline Cable Flye', muscle: 'Upper Chest' },
  { name: 'Incline Dumbbell Bench With Palms Facing In', muscle: 'Upper Chest' },
  { name: 'Incline Dumbbell Flyes', muscle: 'Upper Chest' },
  { name: 'Incline Dumbbell Flyes - With A Twist', muscle: 'Upper Chest' },
  { name: 'Incline Dumbbell Press', muscle: 'Upper Chest' },
  { name: 'Incline Push-Up', muscle: 'Upper Chest' },
  { name: 'Incline Push-Up Depth Jump', muscle: 'Upper Chest' },
  { name: 'Incline Push-Up Medium', muscle: 'Upper Chest' },
  { name: 'Incline Push-Up Reverse Grip', muscle: 'Upper Chest' },
  { name: 'Incline Push-Up Wide', muscle: 'Upper Chest' },
  { name: 'Leverage Incline Chest Press', muscle: 'Upper Chest' },
  { name: 'Smith Machine Incline Bench Press', muscle: 'Upper Chest' },
];
