/**
 * GENERATED — do not hand-edit. Regenerate: node scripts/gen-muscle-by-name.mjs
 *
 * The compact name -> muscle projection of EXERCISE_LIBRARY, for the hot
 * paths (set save, Home/Train cards) that must not drag the full ~210KB
 * library into the shared boot chunk. Keys are trim().toLowerCase() names,
 * last duplicate wins — byte-for-byte the old exercise-library BY_NAME
 * semantics. Pinned by src/domain/__tests__/muscle-by-name.test.ts.
 */

export const MUSCLE_BY_NAME: Readonly<Record<string, string>> = {
  'barbell bench press': 'Chest',
  'paused barbell bench press': 'Chest',
  'dumbbell flat bench press': 'Chest',
  'machine chest press': 'Chest',
  'smith machine bench press': 'Chest',
  'pec deck machine fly': 'Chest',
  'cable chest fly': 'Chest',
  'dumbbell chest fly': 'Chest',
  'weighted chest dip': 'Chest',
  'decline push-up': 'Chest',
  'decline barbell bench press': 'Chest',
  'incline barbell bench press': 'Upper Chest',
  'incline dumbbell bench press': 'Upper Chest',
  'incline machine chest press': 'Upper Chest',
  'low-to-high incline cable fly': 'Upper Chest',
  'incline smith machine bench press': 'Upper Chest',
  'lat pulldown': 'Back Width',
  'close-grip lat pulldown': 'Back Width',
  'weighted pull-up': 'Back Width',
  'assisted pull-up': 'Back Width',
  'cable lat pullover (straight-arm pulldown)': 'Back Width',
  'machine lat pulldown': 'Back Width',
  'neutral-grip pulldown': 'Back Width',
  'chest-supported machine row': 'Back Thickness',
  'chest-supported dumbbell row': 'Back Thickness',
  'barbell bent-over row': 'Back Thickness',
  't-bar row': 'Back Thickness',
  'seated cable row': 'Back Thickness',
  'single-arm dumbbell row': 'Back Thickness',
  'machine high row': 'Back Thickness',
  'pendlay row': 'Back Thickness',
  'rack pull': 'Back Thickness',
  'cable lateral raise': 'Side Delts',
  'dumbbell lateral raise': 'Side Delts',
  'machine lateral raise': 'Side Delts',
  'seated dumbbell lateral raise': 'Side Delts',
  'leaning cable lateral raise': 'Side Delts',
  'reverse pec deck (rear delt fly)': 'Rear Delts',
  'face pull': 'Rear Delts',
  'bent-over rear delt fly': 'Rear Delts',
  'cable rear delt fly': 'Rear Delts',
  'overhead barbell press': 'Front Delts',
  'seated dumbbell shoulder press': 'Front Delts',
  'machine shoulder press': 'Front Delts',
  'arnold press': 'Front Delts',
  'smith machine shoulder press': 'Front Delts',
  'ez-bar curl': 'Biceps',
  'dumbbell biceps curl': 'Biceps',
  'incline dumbbell curl': 'Biceps',
  'hammer curl': 'Biceps',
  'preacher curl': 'Biceps',
  'cable biceps curl': 'Biceps',
  'machine biceps curl': 'Biceps',
  'barbell curl': 'Biceps',
  'spider curl': 'Biceps',
  'cable triceps pushdown': 'Triceps',
  'rope triceps pushdown': 'Triceps',
  'overhead cable triceps extension': 'Triceps',
  'skull crusher (lying triceps extension)': 'Triceps',
  'close-grip bench press': 'Triceps',
  'weighted triceps dip': 'Triceps',
  'machine triceps extension': 'Triceps',
  'dumbbell triceps kickback': 'Triceps',
  'barbell back squat': 'Quads',
  'front squat': 'Quads',
  'hack squat machine': 'Quads',
  'leg press': 'Quads',
  'bulgarian split squat': 'Quads',
  'leg extension': 'Quads',
  'smith machine squat': 'Quads',
  'walking lunge': 'Quads',
  'goblet squat': 'Quads',
  'pendulum squat': 'Quads',
  'romanian deadlift': 'Hamstrings',
  'barbell deadlift': 'Erectors',
  'seated/lying leg curl': 'Hamstrings',
  'seated leg curl': 'Hamstrings',
  'lying leg curl': 'Hamstrings',
  'stiff-leg deadlift': 'Hamstrings',
  'nordic ham curl': 'Hamstrings',
  'good morning': 'Hamstrings',
  'barbell hip thrust': 'Glutes',
  'machine hip thrust': 'Glutes',
  'cable glute kickback': 'Glutes',
  'glute bridge': 'Glutes',
  'machine glute kickback': 'Glutes',
  'seated calf raise': 'Calves',
  'standing calf raise': 'Calves',
  'leg press calf raise': 'Calves',
  'smith machine calf raise': 'Calves',
  'hip adduction machine': 'Adductors',
  'hip abduction machine': 'Abductors',
  'machine ab crunch': 'Abs',
  'cable crunch': 'Abs',
  'lying leg raise': 'Abs',
  'hanging leg raise': 'Abs',
  'weighted sit-up': 'Abs',
  'ab wheel rollout': 'Abs',
  'weighted plank': 'Abs',
  'decline sit-up': 'Abs',
  'barbell wrist curl': 'Forearms',
  'reverse barbell wrist curl': 'Forearms',
  'farmer carry': 'Forearms',
  'reverse curl': 'Forearms',
  'barbell shrug': 'Traps',
  'dumbbell shrug': 'Traps',
  'cable shrug': 'Traps',
  'single-arm cable triceps pushdown': 'Triceps',
  'v-bar cable triceps pushdown': 'Triceps',
  'straight-bar cable triceps pushdown': 'Triceps',
  'reverse-grip cable triceps pushdown': 'Triceps',
  'rope overhead cable triceps extension': 'Triceps',
  'ez-bar overhead triceps extension': 'Triceps',
  'dumbbell overhead triceps extension': 'Triceps',
  'single-arm dumbbell overhead triceps extension': 'Triceps',
  'cable triceps kickback': 'Triceps',
  'dumbbell skull crusher': 'Triceps',
  'bench dip': 'Triceps',
  'cross-body cable triceps extension': 'Triceps',
  'seated dumbbell concentration curl': 'Biceps',
  'cable rope hammer curl': 'Biceps',
  'single-arm cable biceps curl': 'Biceps',
  'wide-grip barbell curl': 'Biceps',
  'close-grip barbell curl': 'Biceps',
  'machine preacher curl': 'Biceps',
  'dumbbell preacher curl': 'Biceps',
  'seated dumbbell hammer curl': 'Biceps',
  'cross-body hammer curl': 'Biceps',
  'behind-the-back cable lateral raise': 'Side Delts',
  'single-arm dumbbell lateral raise': 'Side Delts',
  'lying dumbbell lateral raise': 'Side Delts',
  'cable upright row': 'Side Delts',
  'barbell upright row': 'Side Delts',
  'dumbbell upright row': 'Side Delts',
  'single-arm cable rear delt fly': 'Rear Delts',
  'seated bent-over dumbbell rear delt fly': 'Rear Delts',
  'prone incline dumbbell rear delt raise': 'Rear Delts',
  'dumbbell front raise': 'Front Delts',
  'barbell front raise': 'Front Delts',
  'plate front raise': 'Front Delts',
  'seated barbell overhead press': 'Front Delts',
  'standing dumbbell shoulder press': 'Front Delts',
  'single-arm landmine press': 'Front Delts',
  'single-arm dumbbell shoulder press': 'Front Delts',
  'high-to-low cable chest fly': 'Chest',
  'single-arm cable chest fly': 'Chest',
  'standing low-to-high cable chest fly': 'Chest',
  'barbell floor press': 'Chest',
  'deficit push-up': 'Chest',
  'close-grip dumbbell bench press': 'Chest',
  'neutral-grip dumbbell bench press': 'Chest',
  'incline cable press': 'Upper Chest',
  'reverse-grip barbell bench press': 'Upper Chest',
  'low-incline dumbbell bench press': 'Upper Chest',
  'single-arm lat pulldown': 'Back Width',
  'behind-the-neck lat pulldown': 'Back Width',
  'reverse-grip lat pulldown': 'Back Width',
  'kneeling cable pulldown': 'Back Width',
  'machine-assisted chin-up': 'Back Width',
  'meadows-style landmine row': 'Back Thickness',
  'seal row': 'Back Thickness',
  'chest-supported t-bar row': 'Back Thickness',
  'single-arm cable row': 'Back Thickness',
  'barbell landmine row': 'Back Thickness',
  'yates row': 'Back Thickness',
  'sissy squat': 'Quads',
  'single-leg leg press': 'Quads',
  'reverse lunge': 'Quads',
  'dumbbell step-up': 'Quads',
  'pause back squat': 'Quads',
  'zercher squat': 'Quads',
  'single-leg romanian deadlift': 'Hamstrings',
  'dumbbell romanian deadlift': 'Hamstrings',
  'glute-ham raise': 'Hamstrings',
  'single-leg lying leg curl': 'Hamstrings',
  'single-leg hip thrust': 'Glutes',
  'dumbbell hip thrust': 'Glutes',
  'b-stance hip thrust': 'Glutes',
  'curtsy lunge': 'Glutes',
  'banded glute kickback': 'Glutes',
  'donkey calf raise': 'Calves',
  'single-leg standing calf raise': 'Calves',
  'dumbbell standing calf raise': 'Calves',
  'hanging knee raise': 'Abs',
  'captain\'s chair leg raise': 'Abs',
  'weighted bicycle crunch': 'Abs',
  'toes-to-bar': 'Abs',
  'cable pallof press': 'Abs',
  'weighted decline crunch': 'Abs',
  'behind-the-back barbell wrist curl': 'Forearms',
  'dumbbell wrist curl': 'Forearms',
  'reverse ez-bar curl': 'Forearms',
  'smith machine shrug': 'Traps',
  'trap bar shrug': 'Traps',
  'snatch-grip barbell shrug': 'Traps',
  '3/4 sit-up': 'Abs',
  'ab crunch machine': 'Abs',
  'ab roller': 'Abs',
  'advanced kettlebell windmill': 'Abs',
  'air bike': 'Abs',
  'alternate heel touchers': 'Abs',
  'barbell ab rollout': 'Abs',
  'barbell ab rollout - on knees': 'Abs',
  'barbell rollout from bench': 'Abs',
  'barbell side bend': 'Abs',
  'bent press': 'Abs',
  'bent-knee hip raise': 'Abs',
  'bosu ball cable crunch with side bends': 'Abs',
  'bottoms up': 'Abs',
  'butt-ups': 'Abs',
  'cable judo flip': 'Abs',
  'cable reverse crunch': 'Abs',
  'cable russian twists': 'Abs',
  'cable seated crunch': 'Abs',
  'cocoons': 'Abs',
  'cross-body crunch': 'Abs',
  'crunch - hands overhead': 'Abs',
  'crunch - legs on exercise ball': 'Abs',
  'crunches': 'Abs',
  'dead bug': 'Abs',
  'decline crunch': 'Abs',
  'decline oblique crunch': 'Abs',
  'decline reverse crunch': 'Abs',
  'double kettlebell windmill': 'Abs',
  'dumbbell side bend': 'Abs',
  'elbow to knee': 'Abs',
  'exercise ball crunch': 'Abs',
  'exercise ball pull-in': 'Abs',
  'flat bench leg pull-in': 'Abs',
  'flat bench lying leg raise': 'Abs',
  'frog sit-ups': 'Abs',
  'gorilla chin/crunch': 'Abs',
  'hanging pike': 'Abs',
  'jackknife sit-up': 'Abs',
  'janda sit-up': 'Abs',
  'kettlebell figure 8': 'Abs',
  'kettlebell pass between the legs': 'Abs',
  'kettlebell windmill': 'Abs',
  'knee/hip raise on parallel bars': 'Abs',
  'kneeling cable crunch with alternating oblique twists': 'Abs',
  'landmine 180’s': 'Abs',
  'leg pull-in': 'Abs',
  'lower back curl': 'Abs',
  'medicine ball full twist': 'Abs',
  'oblique crunches': 'Abs',
  'oblique crunches - on the floor': 'Abs',
  'one-arm high-pulley cable side bends': 'Abs',
  'one-arm medicine ball slam': 'Abs',
  'otis-up': 'Abs',
  'overhead stretch': 'Abs',
  'pallof press': 'Abs',
  'pallof press with rotation': 'Abs',
  'plank': 'Abs',
  'plate twist': 'Abs',
  'press sit-up': 'Abs',
  'reverse crunch': 'Abs',
  'rope crunch': 'Abs',
  'russian twist': 'Abs',
  'scissor kick': 'Abs',
  'seated barbell twist': 'Abs',
  'seated flat bench leg pull-in': 'Abs',
  'seated leg tucks': 'Abs',
  'seated overhead stretch': 'Abs',
  'side bridge': 'Abs',
  'side jackknife': 'Abs',
  'sit-up': 'Abs',
  'sledgehammer swings': 'Abs',
  'smith machine hip raise': 'Abs',
  'spell caster': 'Abs',
  'spider crawl': 'Abs',
  'standing cable lift': 'Abs',
  'standing cable wood chop': 'Abs',
  'standing lateral stretch': 'Abs',
  'standing rope crunch': 'Abs',
  'stomach vacuum': 'Abs',
  'supine one-arm overhead throw': 'Abs',
  'supine two-arm overhead throw': 'Abs',
  'suspended fallout': 'Abs',
  'suspended reverse crunch': 'Abs',
  'toe touchers': 'Abs',
  'torso rotation': 'Abs',
  'tuck crunch': 'Abs',
  'weighted ball side bend': 'Abs',
  'weighted crunches': 'Abs',
  'weighted sit-ups - with bands': 'Abs',
  'wind sprints': 'Abs',
  'adductor': 'Adductors',
  'adductor/groin': 'Adductors',
  'band hip adductions': 'Adductors',
  'carioca quick step': 'Adductors',
  'groin and back stretch': 'Adductors',
  'groiners': 'Adductors',
  'hip circles (prone)': 'Adductors',
  'it band and glute stretch': 'Adductors',
  'iliotibial tract-smr': 'Adductors',
  'lateral bound': 'Adductors',
  'lateral box jump': 'Adductors',
  'lateral cone hops': 'Adductors',
  'lying bent leg groin': 'Adductors',
  'lying crossover': 'Adductors',
  'monster walk': 'Abductors',
  'side leg raises': 'Abductors',
  'side lying groin stretch': 'Adductors',
  'standing hip circles': 'Adductors',
  'thigh abductor': 'Abductors',
  'thigh adductor': 'Adductors',
  'windmills': 'Adductors',
  'alternating kettlebell row': 'Back Thickness',
  'alternating renegade row': 'Back Thickness',
  'atlas stone trainer': 'Back Thickness',
  'atlas stones': 'Back Thickness',
  'axle deadlift': 'Back Thickness',
  'bent over barbell row': 'Back Thickness',
  'bent over one-arm long bar row': 'Back Thickness',
  'bent over two-arm long bar row': 'Back Thickness',
  'bent over two-dumbbell row': 'Back Thickness',
  'bent over two-dumbbell row with palms in': 'Back Thickness',
  'bodyweight mid row': 'Back Thickness',
  'cat stretch': 'Back Thickness',
  'child’s pose': 'Back Thickness',
  'crossover reverse lunge': 'Back Thickness',
  'dancer’s stretch': 'Back Thickness',
  'deadlift with bands': 'Erectors',
  'deadlift with chains': 'Erectors',
  'deficit deadlift': 'Erectors',
  'dumbbell incline row': 'Back Thickness',
  'hug a ball': 'Back Thickness',
  'hug knees to chest': 'Back Thickness',
  'hyperextensions (back extensions)': 'Erectors',
  'hyperextensions with no hyperextension bench': 'Erectors',
  'incline bench pull': 'Back Thickness',
  'inverted row': 'Back Thickness',
  'inverted row with straps': 'Back Thickness',
  'keg load': 'Back Thickness',
  'leverage high row': 'Back Thickness',
  'lower back-smr': 'Back Thickness',
  'lying cambered barbell row': 'Back Thickness',
  'lying t-bar row': 'Back Thickness',
  'middle back shrug': 'Back Thickness',
  'middle back stretch': 'Back Thickness',
  'mixed grip chin': 'Back Thickness',
  'one arm chin-up': 'Back Thickness',
  'one-arm dumbbell row': 'Back Thickness',
  'one-arm kettlebell row': 'Back Thickness',
  'one-arm long bar row': 'Back Thickness',
  'pelvic tilt into bridge': 'Back Thickness',
  'pyramid': 'Back Thickness',
  'rack pull with bands': 'Back Thickness',
  'rack pulls': 'Back Thickness',
  'reverse band deadlift': 'Erectors',
  'reverse grip bent-over rows': 'Back Thickness',
  'rhomboids-smr': 'Back Thickness',
  'seated cable rows': 'Back Thickness',
  'seated good mornings': 'Back Thickness',
  'seated one-arm cable pulley rows': 'Back Thickness',
  'sled row': 'Back Thickness',
  'smith machine bent over row': 'Back Thickness',
  'spinal stretch': 'Back Thickness',
  'standing pelvic tilt': 'Back Thickness',
  'stiff leg barbell good morning': 'Back Thickness',
  'straight bar bench mid rows': 'Back Thickness',
  'superman': 'Erectors',
  'suspended row': 'Back Thickness',
  't-bar row with handle': 'Back Thickness',
  'two-arm kettlebell row': 'Back Thickness',
  'upper back stretch': 'Back Thickness',
  'weighted ball hyperextension': 'Erectors',
  'band assisted pull-up': 'Back Width',
  'bent-arm barbell pullover': 'Back Width',
  'cable incline pushdown': 'Back Width',
  'catch and overhead throw': 'Back Width',
  'chair lower back stretch': 'Back Width',
  'chin-up': 'Back Width',
  'close-grip front lat pulldown': 'Back Width',
  'dynamic back stretch': 'Back Width',
  'elevated cable rows': 'Back Width',
  'full range-of-motion lat pulldown': 'Back Width',
  'gironda sternum chins': 'Back Width',
  'kipping muscle up': 'Back Width',
  'kneeling high pulley row': 'Back Width',
  'kneeling single-arm high pulley row': 'Back Width',
  'latissimus dorsi-smr': 'Back Width',
  'leverage iso row': 'Back Width',
  'london bridges': 'Back Width',
  'muscle up': 'Back Width',
  'one arm against wall': 'Back Width',
  'one arm lat pulldown': 'Back Width',
  'one handed hang': 'Back Width',
  'overhead lat': 'Back Width',
  'overhead slam': 'Back Width',
  'pullups': 'Back Width',
  'rocky pull-ups/pulldowns': 'Back Width',
  'rope climb': 'Back Width',
  'rope straight-arm pulldown': 'Back Width',
  'shotgun row': 'Back Width',
  'side to side chins': 'Back Width',
  'side-lying floor stretch': 'Back Width',
  'straight-arm pulldown': 'Back Width',
  'underhand cable pulldowns': 'Back Width',
  'v-bar pulldown': 'Back Width',
  'v-bar pullup': 'Back Width',
  'weighted pull ups': 'Back Width',
  'wide-grip lat pulldown': 'Back Width',
  'wide-grip pulldown behind the neck': 'Back Width',
  'wide-grip rear pull-up': 'Back Width',
  'alternate hammer curl': 'Biceps',
  'alternate incline dumbbell curl': 'Biceps',
  'barbell curls lying against an incline': 'Biceps',
  'brachialis-smr': 'Biceps',
  'cable hammer curls - rope attachment': 'Biceps',
  'cable preacher curl': 'Biceps',
  'close-grip ez bar curl': 'Biceps',
  'close-grip ez-bar curl with band': 'Biceps',
  'close-grip standing barbell curl': 'Biceps',
  'concentration curls': 'Biceps',
  'cross body hammer curl': 'Biceps',
  'drag curl': 'Biceps',
  'dumbbell alternate bicep curl': 'Biceps',
  'dumbbell bicep curl': 'Biceps',
  'dumbbell prone incline curl': 'Biceps',
  'flexor incline dumbbell curls': 'Biceps',
  'hammer curls': 'Biceps',
  'high cable curls': 'Biceps',
  'incline hammer curls': 'Biceps',
  'incline inner biceps curl': 'Biceps',
  'lying cable curl': 'Biceps',
  'lying close-grip bar curl on high pulley': 'Biceps',
  'lying high bench barbell curl': 'Biceps',
  'lying supine dumbbell curl': 'Biceps',
  'machine bicep curl': 'Biceps',
  'machine preacher curls': 'Biceps',
  'one arm dumbbell preacher curl': 'Biceps',
  'overhead cable curl': 'Biceps',
  'preacher hammer dumbbell curl': 'Biceps',
  'reverse barbell curl': 'Biceps',
  'reverse barbell preacher curls': 'Biceps',
  'reverse cable curl': 'Biceps',
  'reverse plate curls': 'Biceps',
  'seated biceps': 'Biceps',
  'seated close-grip concentration barbell curl': 'Biceps',
  'seated dumbbell curl': 'Biceps',
  'seated dumbbell inner biceps curl': 'Biceps',
  'standing biceps cable curl': 'Biceps',
  'standing biceps stretch': 'Biceps',
  'standing concentration curl': 'Biceps',
  'standing dumbbell reverse curl': 'Biceps',
  'standing inner-biceps curl': 'Biceps',
  'standing one-arm cable curl': 'Biceps',
  'standing one-arm dumbbell curl over incline bench': 'Biceps',
  'two-arm dumbbell preacher curl': 'Biceps',
  'wide-grip standing barbell curl': 'Biceps',
  'zottman curl': 'Biceps',
  'zottman preacher curl': 'Biceps',
  'ankle circles': 'Calves',
  'anterior tibialis-smr': 'Calves',
  'balance board': 'Calves',
  'barbell seated calf raise': 'Calves',
  'calf press': 'Calves',
  'calf press on the leg press machine': 'Calves',
  'calf raise on a dumbbell': 'Calves',
  'calf raises - with bands': 'Calves',
  'calf stretch elbows against wall': 'Calves',
  'calf stretch hands against wall': 'Calves',
  'calves-smr': 'Calves',
  'donkey calf raises': 'Calves',
  'dumbbell seated one-leg calf raise': 'Calves',
  'foot-smr': 'Calves',
  'knee circles': 'Calves',
  'peroneals stretch': 'Calves',
  'peroneals-smr': 'Calves',
  'posterior tibialis stretch': 'Calves',
  'rocking standing calf raise': 'Calves',
  'seated calf stretch': 'Calves',
  'smith machine reverse calf raises': 'Calves',
  'standing barbell calf raise': 'Calves',
  'standing calf raises': 'Calves',
  'standing dumbbell calf raise': 'Calves',
  'standing gastrocnemius calf stretch': 'Calves',
  'standing soleus and achilles stretch': 'Calves',
  'alternating floor press': 'Chest',
  'around the worlds': 'Chest',
  'barbell bench press - medium grip': 'Chest',
  'barbell guillotine bench press': 'Chest',
  'behind head chest stretch': 'Chest',
  'bench press - with bands': 'Chest',
  'bent-arm dumbbell pullover': 'Chest',
  'bodyweight flyes': 'Chest',
  'butterfly': 'Chest',
  'cable chest press': 'Chest',
  'cable crossover': 'Chest',
  'cable iron cross': 'Chest',
  'chain press': 'Chest',
  'chest and front of shoulder stretch': 'Chest',
  'chest push (multiple response)': 'Chest',
  'chest push (single response)': 'Chest',
  'chest push from 3 point stance': 'Chest',
  'chest push with run release': 'Chest',
  'chest stretch on stability ball': 'Chest',
  'clock push-up': 'Chest',
  'cross over - with bands': 'Chest',
  'decline dumbbell bench press': 'Chest',
  'decline dumbbell flyes': 'Chest',
  'decline smith press': 'Chest',
  'dips - chest version': 'Chest',
  'drop push': 'Chest',
  'dumbbell bench press': 'Chest',
  'dumbbell bench press with neutral grip': 'Chest',
  'dumbbell flyes': 'Chest',
  'dynamic chest stretch': 'Chest',
  'elbows back': 'Chest',
  'extended range one-arm kettlebell floor press': 'Chest',
  'flat bench cable flyes': 'Chest',
  'forward drag with press': 'Chest',
  'front raise and pullover': 'Chest',
  'heavy bag thrust': 'Chest',
  'isometric chest squeezes': 'Chest',
  'isometric wipers': 'Chest',
  'leg-over floor press': 'Chest',
  'leverage chest press': 'Chest',
  'leverage decline chest press': 'Chest',
  'low cable crossover': 'Chest',
  'machine bench press': 'Chest',
  'medicine ball chest pass': 'Chest',
  'neck press': 'Chest',
  'one arm dumbbell bench press': 'Chest',
  'one-arm flat bench dumbbell flye': 'Chest',
  'one-arm kettlebell floor press': 'Chest',
  'plyo kettlebell pushups': 'Chest',
  'plyo push-up': 'Chest',
  'push up to side plank': 'Chest',
  'push-up wide': 'Chest',
  'push-ups with feet elevated': 'Chest',
  'push-ups with feet on an exercise ball': 'Chest',
  'pushups': 'Chest',
  'pushups (close and wide hand positions)': 'Chest',
  'single-arm cable crossover': 'Chest',
  'single-arm push-up': 'Chest',
  'smith machine decline press': 'Chest',
  'standing cable chest press': 'Chest',
  'straight-arm dumbbell pullover': 'Chest',
  'suspended push-up': 'Chest',
  'svend press': 'Chest',
  'wide-grip barbell bench press': 'Chest',
  'wide-grip decline barbell bench press': 'Chest',
  'wide-grip decline barbell pullover': 'Chest',
  'bottoms-up clean from the hang position': 'Forearms',
  'cable wrist curl': 'Forearms',
  'dumbbell lying pronation': 'Forearms',
  'dumbbell lying supination': 'Forearms',
  'farmer’s walk': 'Forearms',
  'finger curls': 'Forearms',
  'kneeling forearm stretch': 'Forearms',
  'palms-down dumbbell wrist curl over a bench': 'Forearms',
  'palms-down wrist curl over a bench': 'Forearms',
  'palms-up barbell wrist curl over a bench': 'Forearms',
  'palms-up dumbbell wrist curl over a bench': 'Forearms',
  'plate pinch': 'Forearms',
  'rickshaw carry': 'Forearms',
  'seated dumbbell palms-down wrist curl': 'Forearms',
  'seated dumbbell palms-up wrist curl': 'Forearms',
  'seated one-arm dumbbell palms-down wrist curl': 'Forearms',
  'seated one-arm dumbbell palms-up wrist curl': 'Forearms',
  'seated palm-up barbell wrist curl': 'Forearms',
  'seated palms-down barbell wrist curl': 'Forearms',
  'seated two-arm palms-up low-pulley wrist curl': 'Forearms',
  'standing olympic plate hand squeeze': 'Forearms',
  'standing palms-up barbell behind the back wrist curl': 'Forearms',
  'wrist circles': 'Forearms',
  'wrist roller': 'Forearms',
  'wrist rotations with straight bar': 'Forearms',
  'alternating cable shoulder press': 'Front Delts',
  'alternating deltoid raise': 'Front Delts',
  'alternating kettlebell press': 'Front Delts',
  'anti-gravity press': 'Front Delts',
  'arm circles': 'Front Delts',
  'arnold dumbbell press': 'Front Delts',
  'back flyes - with bands': 'Front Delts',
  'backward medicine ball throw': 'Front Delts',
  'band pull apart': 'Front Delts',
  'barbell incline shoulder raise': 'Front Delts',
  'barbell shoulder press': 'Front Delts',
  'battling ropes': 'Front Delts',
  'bradford/rocky presses': 'Front Delts',
  'cable internal rotation': 'Front Delts',
  'cable shoulder press': 'Front Delts',
  'car drivers': 'Front Delts',
  'chair upper body stretch': 'Front Delts',
  'circus bell': 'Front Delts',
  'clean and jerk': 'Front Delts',
  'clean and press': 'Front Delts',
  'crucifix': 'Front Delts',
  'cuban press': 'Front Delts',
  'double kettlebell jerk': 'Front Delts',
  'double kettlebell push press': 'Front Delts',
  'double kettlebell snatch': 'Front Delts',
  'dumbbell incline shoulder raise': 'Front Delts',
  'dumbbell one-arm shoulder press': 'Front Delts',
  'dumbbell raise': 'Front Delts',
  'dumbbell scaption': 'Front Delts',
  'dumbbell shoulder press': 'Front Delts',
  'elbow circles': 'Front Delts',
  'external rotation': 'Front Delts',
  'external rotation with band': 'Front Delts',
  'external rotation with cable': 'Front Delts',
  'front cable raise': 'Front Delts',
  'front dumbbell raise': 'Front Delts',
  'front incline dumbbell raise': 'Front Delts',
  'front plate raise': 'Front Delts',
  'front two-dumbbell raise': 'Front Delts',
  'handstand push-ups': 'Front Delts',
  'internal rotation with band': 'Front Delts',
  'iron cross': 'Front Delts',
  'jerk balance': 'Front Delts',
  'kettlebell arnold press': 'Front Delts',
  'kettlebell pirate ships': 'Front Delts',
  'kettlebell seated press': 'Front Delts',
  'kettlebell seesaw press': 'Front Delts',
  'kettlebell thruster': 'Front Delts',
  'kettlebell turkish get-up (lunge style)': 'Front Delts',
  'kettlebell turkish get-up (squat style)': 'Front Delts',
  'kneeling arm drill': 'Front Delts',
  'landmine linear jammer': 'Front Delts',
  'leverage shoulder press': 'Front Delts',
  'log lift': 'Front Delts',
  'low pulley row to neck': 'Front Delts',
  'machine shoulder (military) press': 'Front Delts',
  'medicine ball scoop throw': 'Front Delts',
  'one-arm kettlebell clean and jerk': 'Front Delts',
  'one-arm kettlebell jerk': 'Front Delts',
  'one-arm kettlebell para press': 'Front Delts',
  'one-arm kettlebell push press': 'Front Delts',
  'one-arm kettlebell snatch': 'Front Delts',
  'one-arm kettlebell split jerk': 'Front Delts',
  'one-arm kettlebell split snatch': 'Front Delts',
  'power partials': 'Front Delts',
  'push press': 'Front Delts',
  'push press - behind the neck': 'Front Delts',
  'rack delivery': 'Front Delts',
  'return push from stance': 'Front Delts',
  'round the world shoulder stretch': 'Front Delts',
  'seated barbell military press': 'Front Delts',
  'seated cable shoulder press': 'Front Delts',
  'seated dumbbell press': 'Front Delts',
  'seated front deltoid': 'Front Delts',
  'shoulder circles': 'Front Delts',
  'shoulder press - with bands': 'Front Delts',
  'shoulder raise': 'Front Delts',
  'shoulder stretch': 'Front Delts',
  'single dumbbell raise': 'Front Delts',
  'single-arm linear jammer': 'Front Delts',
  'sled overhead backward walk': 'Front Delts',
  'smith incline shoulder raise': 'Front Delts',
  'smith machine overhead shoulder press': 'Front Delts',
  'standing alternating dumbbell press': 'Front Delts',
  'standing barbell press behind neck': 'Front Delts',
  'standing bradford press': 'Front Delts',
  'standing dumbbell press': 'Front Delts',
  'standing dumbbell straight-arm front delt raise above head': 'Front Delts',
  'standing front barbell raise over head': 'Front Delts',
  'standing low-pulley deltoid raise': 'Front Delts',
  'standing military press': 'Front Delts',
  'standing palm-in one-arm dumbbell press': 'Front Delts',
  'standing palms-in dumbbell press': 'Front Delts',
  'standing two-arm overhead throw': 'Front Delts',
  'straight raises on incline bench': 'Front Delts',
  'two-arm kettlebell clean': 'Front Delts',
  'two-arm kettlebell jerk': 'Front Delts',
  'two-arm kettlebell military press': 'Front Delts',
  'upright barbell row': 'Front Delts',
  'upward stretch': 'Front Delts',
  'ankle on the knee': 'Glutes',
  'barbell glute bridge': 'Glutes',
  'butt lift (bridge)': 'Glutes',
  'downward facing balance': 'Glutes',
  'flutter kicks': 'Glutes',
  'glute kickback': 'Glutes',
  'hip extension with bands': 'Glutes',
  'hip lift with band': 'Glutes',
  'knee across the body': 'Glutes',
  'kneeling jump squat': 'Glutes',
  'kneeling squat': 'Glutes',
  'leg lift': 'Glutes',
  'lying glute': 'Glutes',
  'one knee to chest': 'Glutes',
  'one-legged cable kickback': 'Glutes',
  'physioball hip bridge': 'Glutes',
  'piriformis-smr': 'Glutes',
  'pull through': 'Glutes',
  'seated glute': 'Glutes',
  'single leg glute bridge': 'Glutes',
  'step-up with knee raise': 'Glutes',
  '90/90 hamstring': 'Hamstrings',
  'alternating hang clean': 'Hamstrings',
  'ball leg curl': 'Hamstrings',
  'band good morning': 'Hamstrings',
  'band good morning (pull through)': 'Hamstrings',
  'box jump (multiple response)': 'Hamstrings',
  'box skip': 'Hamstrings',
  'chair leg extended stretch': 'Hamstrings',
  'clean': 'Hamstrings',
  'clean deadlift': 'Hamstrings',
  'double kettlebell alternating hang clean': 'Hamstrings',
  'dumbbell clean': 'Hamstrings',
  'floor glute-ham raise': 'Hamstrings',
  'front box jump': 'Hamstrings',
  'front leg raises': 'Hamstrings',
  'glute ham raise': 'Hamstrings',
  'good morning off pins': 'Hamstrings',
  'hamstring stretch': 'Hamstrings',
  'hamstring-smr': 'Hamstrings',
  'hang snatch': 'Hamstrings',
  'hang snatch - below knees': 'Hamstrings',
  'hanging bar good morning': 'Hamstrings',
  'hurdle hops': 'Hamstrings',
  'inchworm': 'Hamstrings',
  'intermediate groin stretch': 'Hamstrings',
  'kettlebell dead clean': 'Hamstrings',
  'kettlebell hang clean': 'Hamstrings',
  'kettlebell one-legged deadlift': 'Hamstrings',
  'knee tuck jump': 'Hamstrings',
  'leg-up hamstring stretch': 'Hamstrings',
  'linear 3-part start technique': 'Hamstrings',
  'linear acceleration wall drill': 'Hamstrings',
  'lunge pass through': 'Hamstrings',
  'lying hamstring': 'Hamstrings',
  'lying leg curls': 'Hamstrings',
  'moving claw series': 'Hamstrings',
  'muscle snatch': 'Hamstrings',
  'natural glute ham raise': 'Hamstrings',
  'one-arm kettlebell clean': 'Hamstrings',
  'one-arm kettlebell swings': 'Hamstrings',
  'one-arm open palm kettlebell clean': 'Hamstrings',
  'open palm kettlebell clean': 'Hamstrings',
  'platform hamstring slides': 'Hamstrings',
  'power clean': 'Hamstrings',
  'power clean from blocks': 'Hamstrings',
  'power snatch': 'Hamstrings',
  'power stairs': 'Hamstrings',
  'prone manual hamstring': 'Hamstrings',
  'prowler sprint': 'Hamstrings',
  'reverse band sumo deadlift': 'Hamstrings',
  'reverse hyperextension': 'Hamstrings',
  'romanian deadlift from deficit': 'Hamstrings',
  'runner’s stretch': 'Hamstrings',
  'seated band hamstring curl': 'Hamstrings',
  'seated floor hamstring stretch': 'Hamstrings',
  'seated hamstring': 'Hamstrings',
  'seated hamstring and calf stretch': 'Hamstrings',
  'smith machine hang power clean': 'Hamstrings',
  'smith machine stiff-legged deadlift': 'Hamstrings',
  'snatch deadlift': 'Hamstrings',
  'snatch pull': 'Hamstrings',
  'split snatch': 'Hamstrings',
  'split squats': 'Hamstrings',
  'standing hamstring and calf stretch': 'Hamstrings',
  'standing leg curl': 'Hamstrings',
  'standing toe touches': 'Hamstrings',
  'stiff-legged barbell deadlift': 'Hamstrings',
  'stiff-legged dumbbell deadlift': 'Hamstrings',
  'sumo deadlift': 'Hamstrings',
  'sumo deadlift with bands': 'Hamstrings',
  'sumo deadlift with chains': 'Hamstrings',
  'the straddle': 'Hamstrings',
  'upper back-leg grab': 'Hamstrings',
  'vertical swing': 'Hamstrings',
  'wide stance stiff legs': 'Hamstrings',
  'world’s greatest stretch': 'Hamstrings',
  'all fours quad stretch': 'Quads',
  'alternate leg diagonal bound': 'Quads',
  'backward drag': 'Quads',
  'barbell full squat': 'Quads',
  'barbell hack squat': 'Quads',
  'barbell lunge': 'Quads',
  'barbell side split squat': 'Quads',
  'barbell squat': 'Quads',
  'barbell squat to a bench': 'Quads',
  'barbell step ups': 'Quads',
  'barbell walking lunge': 'Quads',
  'bear crawl sled drags': 'Quads',
  'bench jump': 'Quads',
  'bench sprint': 'Quads',
  'bicycling': 'Quads',
  'bicycling, stationary': 'Quads',
  'bodyweight squat': 'Quads',
  'bodyweight walking lunge': 'Quads',
  'box squat': 'Quads',
  'box squat with bands': 'Quads',
  'box squat with chains': 'Quads',
  'cable deadlifts': 'Quads',
  'cable hip adduction': 'Quads',
  'car deadlift': 'Quads',
  'chair squat': 'Quads',
  'clean pull': 'Quads',
  'clean from blocks': 'Quads',
  'conan’s wheel': 'Quads',
  'depth jump leap': 'Quads',
  'double leg butt kick': 'Quads',
  'dumbbell lunges': 'Quads',
  'dumbbell rear lunge': 'Quads',
  'dumbbell seated box jump': 'Quads',
  'dumbbell squat': 'Quads',
  'dumbbell squat to a bench': 'Quads',
  'dumbbell step ups': 'Quads',
  'elevated back lunge': 'Quads',
  'elliptical trainer': 'Quads',
  'fast skipping': 'Quads',
  'frankenstein squat': 'Quads',
  'freehand jump squat': 'Quads',
  'frog hops': 'Quads',
  'front barbell squat': 'Quads',
  'front barbell squat to a bench': 'Quads',
  'front cone hops (or hurdle hops)': 'Quads',
  'front squat (clean grip)': 'Quads',
  'front squats with two kettlebells': 'Quads',
  'hack squat': 'Quads',
  'hang clean': 'Quads',
  'hang clean - below the knees': 'Quads',
  'heaving snatch balance': 'Quads',
  'hip flexion with band': 'Quads',
  'intermediate hip flexor and quad stretch': 'Quads',
  'iron crosses (stretch)': 'Quads',
  'jefferson squats': 'Quads',
  'jerk dip squat': 'Quads',
  'jogging, treadmill': 'Quads',
  'kettlebell pistol squat': 'Quads',
  'kneeling hip flexor': 'Quads',
  'leg extensions': 'Quads',
  'leverage deadlift': 'Quads',
  'linear depth jump': 'Quads',
  'looking at ceiling': 'Quads',
  'lunge sprint': 'Quads',
  'lying machine squat': 'Quads',
  'lying prone quadriceps': 'Quads',
  'mountain climbers': 'Quads',
  'narrow stance hack squats': 'Quads',
  'narrow stance leg press': 'Quads',
  'narrow stance squats': 'Quads',
  'olympic squat': 'Quads',
  'on your side quad stretch': 'Quads',
  'on-your-back quad stretch': 'Quads',
  'one half locust': 'Quads',
  'one leg barbell squat': 'Quads',
  'one-arm overhead kettlebell squats': 'Quads',
  'one-arm side deadlift': 'Quads',
  'overhead squat': 'Quads',
  'plie dumbbell squat': 'Quads',
  'power jerk': 'Quads',
  'power snatch from blocks': 'Quads',
  'quad stretch': 'Quads',
  'quadriceps-smr': 'Quads',
  'quick leap': 'Quads',
  'rear leg raises': 'Quads',
  'recumbent bike': 'Quads',
  'reverse band box squat': 'Quads',
  'reverse band power squat': 'Quads',
  'rickshaw deadlift': 'Quads',
  'rocket jump': 'Quads',
  'rope jumping': 'Quads',
  'rowing, stationary': 'Quads',
  'running, treadmill': 'Quads',
  'sandbag load': 'Quads',
  'scissors jump': 'Quads',
  'side hop-sprint': 'Quads',
  'side standing long jump': 'Quads',
  'side to side box shuffle': 'Quads',
  'single leg butt kick': 'Quads',
  'single leg push-off': 'Quads',
  'single-cone sprint drill': 'Quads',
  'single-leg high box squat': 'Quads',
  'single-leg hop progression': 'Quads',
  'single-leg lateral hop': 'Quads',
  'single-leg leg extension': 'Quads',
  'single-leg stride jump': 'Quads',
  'sit squats': 'Quads',
  'skating': 'Quads',
  'sled drag - harness': 'Quads',
  'sled push': 'Quads',
  'smith machine leg press': 'Quads',
  'smith machine pistol squat': 'Quads',
  'smith single-leg split squat': 'Quads',
  'snatch': 'Quads',
  'snatch balance': 'Quads',
  'snatch from blocks': 'Quads',
  'speed box squat': 'Quads',
  'speed squats': 'Quads',
  'split clean': 'Quads',
  'split jerk': 'Quads',
  'split jump': 'Quads',
  'split squat with dumbbells': 'Quads',
  'squat jerk': 'Quads',
  'squat with bands': 'Quads',
  'squat with chains': 'Quads',
  'squat with plate movers': 'Quads',
  'squats - with bands': 'Quads',
  'stairmaster': 'Quads',
  'standing elevated quad stretch': 'Quads',
  'standing hip flexors': 'Quads',
  'standing long jump': 'Quads',
  'star jump': 'Quads',
  'step mill': 'Quads',
  'stride jump crossover': 'Quads',
  'suspended split squat': 'Quads',
  'tire flip': 'Quads',
  'trail running/walking': 'Quads',
  'trap bar deadlift': 'Quads',
  'walking, treadmill': 'Quads',
  'weighted jump squat': 'Quads',
  'weighted sissy squat': 'Quads',
  'weighted squat': 'Quads',
  'wide stance barbell squat': 'Quads',
  'yoke walk': 'Quads',
  'zercher squats': 'Quads',
  'barbell rear delt row': 'Rear Delts',
  'bent over dumbbell rear delt raise with head on bench': 'Rear Delts',
  'cable rope rear-delt rows': 'Rear Delts',
  'dumbbell lying one-arm rear lateral raise': 'Rear Delts',
  'dumbbell lying rear lateral raise': 'Rear Delts',
  'lying rear delt raise': 'Rear Delts',
  'reverse flyes': 'Rear Delts',
  'reverse flyes with external rotation': 'Rear Delts',
  'reverse machine flyes': 'Rear Delts',
  'seated bent-over rear delt raise': 'Rear Delts',
  'sled reverse flye': 'Rear Delts',
  'bent over low-pulley side lateral': 'Side Delts',
  'cable seated lateral raise': 'Side Delts',
  'dumbbell one-arm upright row': 'Side Delts',
  'lateral raise - with bands': 'Side Delts',
  'lying one-arm lateral raise': 'Side Delts',
  'one-arm incline lateral raise': 'Side Delts',
  'one-arm kettlebell military press to the side': 'Side Delts',
  'one-arm side laterals': 'Side Delts',
  'seated side lateral raise': 'Side Delts',
  'see-saw press (alternating side press)': 'Side Delts',
  'side lateral raise': 'Side Delts',
  'side laterals to front raise': 'Side Delts',
  'side wrist pull': 'Side Delts',
  'smith machine one-arm upright row': 'Side Delts',
  'barbell shrug behind the back': 'Traps',
  'cable shrugs': 'Traps',
  'calf-machine shoulder shrug': 'Traps',
  'chin to chest stretch': 'Traps',
  'clean shrug': 'Traps',
  'isometric neck exercise - front and back': 'Traps',
  'isometric neck exercise - sides': 'Traps',
  'kettlebell sumo high pull': 'Traps',
  'leverage shrug': 'Traps',
  'lying face down plate neck resistance': 'Traps',
  'lying face up plate neck resistance': 'Traps',
  'neck-smr': 'Traps',
  'scapular pull-up': 'Traps',
  'seated head harness neck resistance': 'Traps',
  'side neck stretch': 'Traps',
  'smith machine behind the back shrug': 'Traps',
  'smith machine upright row': 'Traps',
  'snatch shrug': 'Traps',
  'standing dumbbell upright row': 'Traps',
  'upright cable row': 'Traps',
  'upright row - with bands': 'Traps',
  'band skull crusher': 'Triceps',
  'bench dips': 'Triceps',
  'bench press - powerlifting': 'Triceps',
  'bench press with chains': 'Triceps',
  'board press': 'Triceps',
  'body tricep press': 'Triceps',
  'body-up': 'Triceps',
  'cable incline triceps extension': 'Triceps',
  'cable lying triceps extension': 'Triceps',
  'cable one arm tricep extension': 'Triceps',
  'cable rope overhead triceps extension': 'Triceps',
  'chain handle extension': 'Triceps',
  'close-grip barbell bench press': 'Triceps',
  'close-grip dumbbell press': 'Triceps',
  'close-grip ez-bar press': 'Triceps',
  'close-grip push-up off of a dumbbell': 'Triceps',
  'decline close-grip bench to skull crusher': 'Triceps',
  'decline dumbbell triceps extension': 'Triceps',
  'decline ez bar triceps extension': 'Triceps',
  'dip machine': 'Triceps',
  'dips - triceps version': 'Triceps',
  'dumbbell floor press': 'Triceps',
  'dumbbell one-arm triceps extension': 'Triceps',
  'dumbbell tricep extension -pronated grip': 'Triceps',
  'ez-bar skullcrusher': 'Triceps',
  'floor press': 'Triceps',
  'floor press with chains': 'Triceps',
  'incline barbell triceps extension': 'Triceps',
  'incline push-up close-grip': 'Triceps',
  'jm press': 'Triceps',
  'kneeling cable triceps extension': 'Triceps',
  'low cable triceps extension': 'Triceps',
  'lying close-grip barbell triceps extension behind the head': 'Triceps',
  'lying close-grip barbell triceps press to chin': 'Triceps',
  'lying dumbbell tricep extension': 'Triceps',
  'lying triceps press': 'Triceps',
  'one arm floor press': 'Triceps',
  'one arm pronated dumbbell triceps extension': 'Triceps',
  'one arm supinated dumbbell triceps extension': 'Triceps',
  'overhead triceps': 'Triceps',
  'parallel bar dip': 'Triceps',
  'pin presses': 'Triceps',
  'push-ups - close triceps position': 'Triceps',
  'reverse band bench press': 'Triceps',
  'reverse grip triceps pushdown': 'Triceps',
  'reverse triceps bench press': 'Triceps',
  'ring dips': 'Triceps',
  'seated bent-over one-arm dumbbell triceps extension': 'Triceps',
  'seated bent-over two-arm dumbbell triceps extension': 'Triceps',
  'seated triceps press': 'Triceps',
  'sled overhead triceps extension': 'Triceps',
  'smith machine close-grip bench press': 'Triceps',
  'speed band overhead triceps': 'Triceps',
  'standing bent-over one-arm dumbbell triceps extension': 'Triceps',
  'standing bent-over two-arm dumbbell triceps extension': 'Triceps',
  'standing dumbbell triceps extension': 'Triceps',
  'standing low-pulley one-arm triceps extension': 'Triceps',
  'standing one-arm dumbbell triceps extension': 'Triceps',
  'standing overhead barbell triceps extension': 'Triceps',
  'standing towel triceps extension': 'Triceps',
  'supine chest throw': 'Triceps',
  'tate press': 'Triceps',
  'tricep dumbbell kickback': 'Triceps',
  'tricep side stretch': 'Triceps',
  'triceps overhead extension with rope': 'Triceps',
  'triceps pushdown': 'Triceps',
  'triceps pushdown - rope attachment': 'Triceps',
  'triceps pushdown - v-bar attachment': 'Triceps',
  'triceps stretch': 'Triceps',
  'weighted bench dip': 'Triceps',
  'barbell incline bench press - medium grip': 'Upper Chest',
  'hammer grip incline db bench press': 'Upper Chest',
  'incline cable chest press': 'Upper Chest',
  'incline cable flye': 'Upper Chest',
  'incline dumbbell bench with palms facing in': 'Upper Chest',
  'incline dumbbell flyes': 'Upper Chest',
  'incline dumbbell flyes - with a twist': 'Upper Chest',
  'incline dumbbell press': 'Upper Chest',
  'incline push-up': 'Upper Chest',
  'incline push-up depth jump': 'Upper Chest',
  'incline push-up medium': 'Upper Chest',
  'incline push-up reverse grip': 'Upper Chest',
  'incline push-up wide': 'Upper Chest',
  'leverage incline chest press': 'Upper Chest',
  'smith machine incline bench press': 'Upper Chest',
  'smith machine incline press': 'Upper Chest',
  'decline dumbbell press': 'Chest',
  'single-arm cable fly': 'Chest',
  'plate squeeze press': 'Chest',
  'ring push-up': 'Chest',
  'banded push-up': 'Chest',
  'meadows row': 'Back Thickness',
  'smith machine row': 'Back Thickness',
  'straight-arm rope pulldown': 'Back Width',
  'machine pullover': 'Back Width',
  'wide-grip seated cable row': 'Back Thickness',
  'archer pull-up': 'Back Width',
  'kettlebell row': 'Back Thickness',
  'cable y-raise': 'Side Delts',
  'machine rear delt row': 'Rear Delts',
  'kettlebell overhead press': 'Front Delts',
  'z press': 'Front Delts',
  'band pull-apart': 'Rear Delts',
  'cable front raise': 'Front Delts',
  'handstand push-up': 'Front Delts',
  'bayesian cable curl': 'Biceps',
  'waiter curl': 'Biceps',
  'cable overhead triceps extension': 'Triceps',
  'diamond push-up': 'Triceps',
  'reverse-grip cable curl': 'Forearms',
  'plate pinch hold': 'Forearms',
  'towel pull-up hold': 'Forearms',
  'landmine squat': 'Quads',
  'belt squat': 'Quads',
  'kettlebell goblet lunge': 'Quads',
  'cyclist squat': 'Quads',
  'nordic hamstring curl': 'Hamstrings',
  'kettlebell single-leg rdl': 'Hamstrings',
  'cable pull-through': 'Glutes',
  'smith machine hip thrust': 'Glutes',
  'frog pump': 'Glutes',
  'step-through lunge': 'Glutes',
  'banded lateral walk': 'Abductors',
  'copenhagen plank': 'Adductors',
  'machine standing calf raise': 'Calves',
  'single-leg seated calf raise': 'Calves',
  'tibialis raise': 'Calves',
  'cable woodchopper': 'Abs',
  'dragon flag': 'Abs',
  'jefferson curl': 'Erectors',
  'suitcase carry': 'Abs',
  'kettlebell high pull': 'Traps',
  'snatch-grip high pull': 'Traps',
  'landmine press': 'Front Delts',
  'landmine row': 'Back Thickness',
  'landmine rotation': 'Abs',
  'kettlebell swing': 'Glutes',
  'kettlebell clean and press': 'Front Delts',
  'kettlebell turkish get-up': 'Abs',
  'sled pull': 'Back Thickness',
  'farmer\'s walk': 'Forearms',
  'bear crawl': 'Abs',
  'wall sit': 'Quads',
  'box jump': 'Quads',
  'broad jump': 'Glutes',
};
