/**
 * THE PALETTE SHOP — the six purchasable whole-app colour palettes plus the
 * free 'standard' identity (2026-07-17).
 *
 * Each palette is a FULL record of tokens.colors' keys: the 15 chrome tokens
 * (bg, bg-deep, surface×3, border×3, text×3, accent×4) are re-hued; the five
 * rarity tokens and success/warn/danger are ALWAYS standard — rarity is a
 * cross-app vocabulary and semantic colours encode meaning (a theme that
 * turns "danger" green is a correctness bug). Pinned by
 * __tests__/palettes.test.ts.
 *
 * Generated by the scratchpad gen_palettes.py (HSL hue rotation preserving
 * each token's lightness/saturation relationships; contrast-checked
 * text/surface >= 4.5:1, text-mute/surface >= 3:1), then hand-tuned:
 * accent-ink stays near-black in every palette (it is the text ON accent
 * fills) and void's accent family is lifted to white ("white accent" is the
 * product spec for Void Mono).
 *
 * Colours live HERE; ids and prices live in domain/customise.ts
 * (PALETTE_IDS / PALETTE_PRICES — the server's palette_price() is the
 * authority, the domain table is its display twin). The vitest pins the two
 * id sets equal in both directions.
 */
// Relative on purpose: this module is imported by vitest (no @/ alias there).
import tokens from './tokens';

export type PaletteColours = typeof tokens.colors;

/** rarity + semantic: identical in every palette, by product decision. */
const STABLE = {
  common: tokens.colors.common,
  rare: tokens.colors.rare,
  epic: tokens.colors.epic,
  legendary: tokens.colors.legendary,
  mythic: tokens.colors.mythic,
  success: tokens.colors.success,
  warn: tokens.colors.warn,
  danger: tokens.colors.danger,
};

export const PALETTE_COLOURS = {
  standard: tokens.colors,
  emerald: {
    bg: '#07140e',
    'bg-deep': '#040e09',
    surface: '#0d2419',
    'surface-2': '#133122',
    'surface-3': '#1a402d',
    border: '#224f39',
    'border-soft': 'rgba(120, 220, 155, 0.12)',
    'border-strong': 'rgba(34, 238, 102, 0.34)',
    text: '#e8fbee',
    'text-dim': '#93c4aa',
    'text-mute': '#648f77',
    accent: '#22ee66',
    'accent-strong': '#67f995',
    'accent-deep': '#08b24b',
    'accent-ink': '#041a10',
    ...STABLE,
  },
  crimson: {
    bg: '#140708',
    'bg-deep': '#0e0405',
    surface: '#240d10',
    'surface-2': '#311317',
    'surface-3': '#401a1f',
    border: '#4f2227',
    'border-soft': 'rgba(220, 120, 149, 0.12)',
    'border-strong': 'rgba(238, 48, 34, 0.34)',
    text: '#fbe8ee',
    'text-dim': '#c4939b',
    'text-mute': '#8f646c',
    accent: '#ee3022',
    'accent-strong': '#f96e67',
    'accent-deep': '#b21e08',
    'accent-ink': '#1a0b04',
    ...STABLE,
  },
  synthwave: {
    bg: '#0f0615',
    'bg-deep': '#0a040e',
    surface: '#190c25',
    'surface-2': '#241133',
    'surface-3': '#2f1842',
    border: '#3b2051',
    'border-soft': 'rgba(157, 115, 225, 0.12)',
    'border-strong': 'rgba(238, 34, 170, 0.34)',
    text: '#eee7fc',
    'text-dim': '#ab91c6',
    'text-mute': '#796291',
    accent: '#ee22aa',
    'accent-strong': '#f967cb',
    'accent-deep': '#b2086f',
    'accent-ink': '#1a040e',
    ...STABLE,
  },
  solar: {
    bg: '#130e08',
    'bg-deep': '#0e0904',
    surface: '#23180e',
    'surface-2': '#2f2115',
    'surface-3': '#3e2c1c',
    border: '#4d3824',
    'border-soft': 'rgba(215, 153, 125, 0.12)',
    'border-strong': 'rgba(238, 177, 34, 0.34)',
    text: '#faeee9',
    'text-dim': '#c2a895',
    'text-mute': '#8d7666',
    accent: '#eeb122',
    'accent-strong': '#f9cb67',
    'accent-deep': '#b28908',
    'accent-ink': '#1a1804',
    ...STABLE,
  },
  arctic: {
    bg: '#0a0e11',
    'bg-deep': '#06090c',
    surface: '#121a1f',
    'surface-2': '#1a232a',
    'surface-3': '#232f37',
    border: '#2c3a45',
    'border-soft': 'rgba(142, 183, 198, 0.12)',
    'border-strong': 'rgba(140, 188, 204, 0.34)',
    text: '#ecf4f7',
    'text-dim': '#9eafb9',
    'text-mute': '#6e7d85',
    accent: '#8cbccc',
    'accent-strong': '#c2dde6',
    'accent-deep': '#4d94b5',
    'accent-ink': '#0a161d',
    ...STABLE,
  },
  void: {
    bg: '#0d0d0e',
    'bg-deep': '#090909',
    surface: '#181819',
    'surface-2': '#212223',
    'surface-3': '#2b2c2f',
    border: '#37383a',
    'border-soft': 'rgba(166, 170, 174, 0.12)',
    'border-strong': 'rgba(220, 220, 220, 0.34)',
    text: '#f1f2f2',
    'text-dim': '#aaabad',
    'text-mute': '#78797b',
    accent: '#dcdcdc',
    'accent-strong': '#f5f5f5',
    'accent-deep': '#9e9e9e',
    'accent-ink': '#101010',
    ...STABLE,
  },
} satisfies Record<string, PaletteColours>;

export type ThemePaletteId = keyof typeof PALETTE_COLOURS;

export const THEME_PALETTE_IDS = Object.keys(PALETTE_COLOURS) as ThemePaletteId[];

/** Store-card metadata: display name + four swatches (bg, surface-2, accent, text). */
export const PALETTE_META: Record<ThemePaletteId, { name: string; swatch: [string, string, string, string] }> =
  Object.fromEntries(
    (
      [
        ['standard', 'STANDARD ISSUE'],
        ['emerald', 'EMERALD CIRCUIT'],
        ['crimson', 'CRIMSON EMBER'],
        ['synthwave', 'SYNTHWAVE'],
        ['solar', 'SOLAR FLARE'],
        ['arctic', 'ARCTIC GHOST'],
        ['void', 'VOID MONO'],
      ] as const
    ).map(([id, name]) => {
      const c = PALETTE_COLOURS[id];
      return [id, { name, swatch: [c.bg, c['surface-2'], c.accent, c.text] }];
    })
  ) as Record<ThemePaletteId, { name: string; swatch: [string, string, string, string] }>;

export function isThemePaletteId(id: string | null | undefined): id is ThemePaletteId {
  return id != null && Object.prototype.hasOwnProperty.call(PALETTE_COLOURS, id);
}

/**
 * The CSS custom properties ThemeRoot applies. 'standard' returns {} —
 * unset vars mean every `var(--c-k, fallback)` in the compiled CSS resolves
 * to its fallback, which IS the standard value (provably identical, and the
 * cheapest possible default).
 */
export function varsFor(id: ThemePaletteId): Record<string, string> {
  if (id === 'standard') return {};
  const record = PALETTE_COLOURS[id];
  return Object.fromEntries(Object.entries(record).map(([k, v]) => [`--c-${k}`, v]));
}
