import type { BattleMove, ChampionId } from './types';

/**
 * THE MOVE CATALOG — exactly four moves per champion (beta). Powers/costs are
 * tuned so a standard battle lasts ~6–12 turns (see damage.ts): base HP ~110,
 * a reliable attack ~14–20 damage after defence, heavies ~28–36, finishers
 * more under their condition. RECOVER (below) is the universal fallback.
 */

export const RECOVER_MOVE: BattleMove = {
  id: 'recover',
  name: 'Recover',
  description: 'Catch your breath — restore a chunk of stamina. Always available, deals no damage.',
  category: 'recovery',
  requiredChampion: 'aesthetic', // unused for the shared fallback
  staminaCost: 0,
  basePower: 0,
  accuracy: 1,
  priority: 0,
  cooldown: 0,
  effects: [{ kind: 'restore_stamina', target: 'self', amount: 35 }],
  animationType: 'recovery',
  target: 'self',
  theme: 'success',
};

const AESTHETIC: BattleMove[] = [
  {
    id: 'precision_strike',
    name: 'Flash Jab',
    description: 'A picture-perfect jab thrown mid-pose — lands almost every time, with a raised crit chance.',
    category: 'attack',
    requiredChampion: 'aesthetic',
    staminaCost: 12,
    basePower: 23,
    accuracy: 0.98,
    priority: 0,
    cooldown: 0,
    effects: [{ kind: 'buff_self', status: 'perfect_form', target: 'self', duration: 1, amount: 0.12, chance: 0.5 }],
    animationType: 'technique',
    target: 'opponent',
    theme: 'accent',
  },
  {
    id: 'perfect_form',
    name: 'Golden Hour',
    description: 'Strike a pose in the spotlight — precision and evasion up for two turns. No damage.',
    category: 'buff',
    requiredChampion: 'aesthetic',
    staminaCost: 14,
    basePower: 0,
    accuracy: 1,
    priority: 1,
    cooldown: 3,
    effects: [{ kind: 'apply_status', status: 'perfect_form', target: 'self', duration: 2, amount: 0.22 }],
    animationType: 'buff',
    target: 'self',
    theme: 'epic',
  },
  {
    id: 'counter_pose',
    name: 'Front Double Bi',
    description: 'Hit the pose and HOLD — halve incoming damage this turn and reflect part of it back.',
    category: 'defence',
    requiredChampion: 'aesthetic',
    staminaCost: 10,
    basePower: 0,
    accuracy: 1,
    priority: 2,
    cooldown: 1,
    effects: [], // the guard stance is applied by the engine (counter_pose)
    animationType: 'defence',
    target: 'self',
    theme: 'rare',
  },
  {
    id: 'apex_execution',
    name: 'Grand Posedown',
    description: 'The final callout — a devastating finisher against opponents below 40% health.',
    category: 'ultimate',
    requiredChampion: 'aesthetic',
    staminaCost: 30,
    basePower: 30,
    accuracy: 0.92,
    priority: 0,
    cooldown: 2,
    effects: [],
    animationType: 'ultimate',
    target: 'opponent',
    theme: 'legendary',
    conditional: { kind: 'execute_below', threshold: 0.4, multiplier: 1.8 },
    // COVERAGE (Phase C rebalance): the finisher flows — Aesthetic's line
    // into Titan's FORCE wall. Trade: it no longer supers Apex.
    style: 'flow',
  },
];

const TITAN: BattleMove[] = [
  {
    id: 'forge_smash',
    name: 'Plate Toss',
    description: 'Hurl loaded iron downrange — a heavy blow with a chance to stagger.',
    category: 'heavy',
    requiredChampion: 'titan',
    staminaCost: 18,
    basePower: 25,
    accuracy: 0.9,
    priority: 0,
    cooldown: 0,
    effects: [{ kind: 'apply_status', status: 'stagger', target: 'opponent', duration: 2, amount: 0.25, chance: 0.4 }],
    animationType: 'heavy',
    target: 'opponent',
    theme: 'legendary',
  },
  {
    id: 'iron_guard',
    name: 'Rack Lockout',
    description: 'Brace in the rack — massive defence for a turn, and recover some stamina.',
    category: 'defence',
    requiredChampion: 'titan',
    staminaCost: 8,
    basePower: 0,
    accuracy: 1,
    priority: 2,
    cooldown: 1,
    effects: [{ kind: 'restore_stamina', target: 'self', amount: 12 }], // the guard stance is applied by the engine (iron_guard)
    animationType: 'defence',
    target: 'self',
    theme: 'rare',
  },
  {
    id: 'colossal_pressure',
    name: 'Lunk Alarm',
    description: 'Drop the weights, trip the alarm — damage that shatters the opponent’s guard.',
    category: 'debuff',
    requiredChampion: 'titan',
    staminaCost: 14,
    basePower: 18,
    accuracy: 0.95,
    priority: 0,
    cooldown: 0,
    effects: [{ kind: 'apply_status', status: 'guard_break', target: 'opponent', duration: 2, amount: 0.25 }],
    animationType: 'technique',
    target: 'opponent',
    theme: 'epic',
    // COVERAGE: pressure is technique — Titan's line into Apex's FLOW.
    style: 'form',
  },
  {
    id: 'titan_breaker',
    name: 'PR or ER',
    description: 'Load the bar past sanity — a colossal slam that hits harder the more damage you’ve taken.',
    category: 'ultimate',
    requiredChampion: 'titan',
    staminaCost: 32,
    basePower: 34,
    accuracy: 0.88,
    priority: -1,
    cooldown: 2,
    effects: [],
    animationType: 'ultimate',
    target: 'opponent',
    theme: 'legendary',
    conditional: { kind: 'stronger_if_damaged', multiplier: 1.6 },
  },
];

const APEX: BattleMove[] = [
  {
    id: 'rapid_strike',
    name: 'Double Time',
    description: 'A snapping jab at double pace — cheap, and may land twice.',
    category: 'attack',
    requiredChampion: 'apex',
    staminaCost: 8,
    basePower: 14,
    accuracy: 0.96,
    priority: 1,
    cooldown: 0,
    effects: [],
    animationType: 'quick',
    target: 'opponent',
    theme: 'accent',
    multiHit: { times: 2, chance: 0.65 },
  },
  {
    id: 'overclock',
    name: 'Zone Five',
    description: 'Redline the engine — speed and stamina regen surge for two turns.',
    category: 'buff',
    requiredChampion: 'apex',
    staminaCost: 12,
    basePower: 0,
    accuracy: 1,
    priority: 1,
    cooldown: 3,
    effects: [{ kind: 'apply_status', status: 'overclocked', target: 'self', duration: 2, amount: 0.3 }],
    animationType: 'buff',
    target: 'self',
    theme: 'epic',
  },
  {
    id: 'second_wind',
    name: 'Second Wind',
    description: 'Catch your breath mid-round — restore stamina and a little health.',
    category: 'recovery',
    requiredChampion: 'apex',
    staminaCost: 0,
    basePower: 0,
    accuracy: 1,
    priority: 1,
    cooldown: 3,
    effects: [
      { kind: 'restore_stamina', target: 'self', amount: 30 },
      { kind: 'restore_health', target: 'self', amount: 14 },
    ],
    animationType: 'recovery',
    target: 'self',
    theme: 'success',
  },
  {
    id: 'velocity_crash',
    name: 'Sprint Finish',
    description: 'An all-out closing sprint — force scales with your speed. Expensive.',
    category: 'heavy',
    requiredChampion: 'apex',
    staminaCost: 22,
    basePower: 22,
    accuracy: 0.92,
    priority: 0,
    cooldown: 1,
    effects: [],
    animationType: 'ultimate',
    target: 'opponent',
    theme: 'legendary',
    // COVERAGE: a crash is raw impact — Apex's line into FORM champions.
    style: 'force',
  },
];

const SHREDDED: BattleMove[] = [
  {
    id: 'twin_slash',
    name: 'Razor Reps',
    description: 'Two razor-fast cuts with a chance to open a bleed.',
    category: 'attack',
    requiredChampion: 'shredded',
    staminaCost: 12,
    basePower: 18,
    accuracy: 0.95,
    priority: 0,
    cooldown: 0,
    effects: [{ kind: 'apply_status', status: 'bleed', target: 'opponent', duration: 3, amount: 6, chance: 0.5 }],
    animationType: 'quick',
    target: 'opponent',
    theme: 'danger',
  },
  {
    id: 'shadow_step',
    name: 'Shadow Work',
    description: 'Vanish into the shadow work — huge evasion this turn, and your next attack hits harder.',
    category: 'buff',
    requiredChampion: 'shredded',
    staminaCost: 12,
    basePower: 0,
    accuracy: 1,
    priority: 2,
    cooldown: 2,
    effects: [{ kind: 'apply_status', status: 'perfect_form', target: 'self', duration: 1, amount: 0.4 }],
    animationType: 'buff',
    target: 'self',
    theme: 'rare',
  },
  {
    id: 'cut_deep',
    name: 'Deep Cut',
    description: 'A surgical strike — far crueler against a bleeding target.',
    category: 'technique',
    requiredChampion: 'shredded',
    staminaCost: 16,
    basePower: 20,
    accuracy: 0.93,
    priority: 0,
    cooldown: 0,
    effects: [],
    animationType: 'technique',
    target: 'opponent',
    theme: 'epic',
    conditional: { kind: 'stronger_if_bleeding', multiplier: 1.7 },
    // COVERAGE: the deep cut flows — Shredded's line into Titan's FORCE wall.
    style: 'flow',
  },
  {
    id: 'final_shred',
    name: 'Peak Week',
    description: 'The last brutal week before the show — executes opponents below 30% health.',
    category: 'ultimate',
    requiredChampion: 'shredded',
    staminaCost: 30,
    basePower: 26,
    accuracy: 0.9,
    priority: 0,
    cooldown: 2,
    effects: [],
    animationType: 'ultimate',
    target: 'opponent',
    theme: 'legendary',
    conditional: { kind: 'execute_below', threshold: 0.3, multiplier: 2.0 },
  },
];

export const MOVES_BY_CHAMPION: Record<ChampionId, BattleMove[]> = {
  aesthetic: AESTHETIC,
  titan: TITAN,
  apex: APEX,
  shredded: SHREDDED,
};

/**
 * BATTLE ITEMS (Phase C) — one of each per battle (cooldown 99 outlasts any
 * real battle), costs the turn, priority +3 so an item always resolves before
 * moves (FireRed's bag rule). Shared by every champion; the AI gets them at
 * gym tier. `style: undefined` is fine — basePower 0 never reads the triangle.
 */
export const ITEM_MOVES: BattleMove[] = [
  {
    id: 'item_protein_shake',
    name: 'Protein Shake',
    description: 'Chug it — restore 35% of max health. One per battle; costs the turn.',
    category: 'recovery',
    requiredChampion: 'aesthetic', // unused for shared items
    staminaCost: 0,
    basePower: 0,
    accuracy: 1,
    priority: 3,
    cooldown: 99,
    effects: [{ kind: 'heal_percent', target: 'self', amount: 0.35 }],
    animationType: 'recovery',
    target: 'self',
    theme: 'success',
    isItem: true,
  },
  {
    id: 'item_pre_workout',
    name: 'Pre-Workout',
    description: 'The good scoop — spike speed, regen and precision for 2 turns. One per battle.',
    category: 'buff',
    requiredChampion: 'aesthetic', // unused for shared items
    staminaCost: 0,
    basePower: 0,
    accuracy: 1,
    priority: 3,
    cooldown: 99,
    effects: [
      { kind: 'apply_status', status: 'overclocked', target: 'self', duration: 2, amount: 0.25 },
      { kind: 'apply_status', status: 'perfect_form', target: 'self', duration: 2, amount: 0.15 },
    ],
    animationType: 'buff',
    target: 'self',
    theme: 'epic',
    isItem: true,
  },
];

/** Every move keyed by id, incl. the shared Recover + items. */
export const ALL_MOVES: Record<string, BattleMove> = Object.fromEntries(
  [...AESTHETIC, ...TITAN, ...APEX, ...SHREDDED, RECOVER_MOVE, ...ITEM_MOVES].map((m) => [m.id, m])
);

export function movesForChampion(id: ChampionId): BattleMove[] {
  return MOVES_BY_CHAMPION[id];
}
