import type { BattleMove, ChampionId } from './types';

/**
 * THE MOVE CATALOG — exactly four moves per champion (beta). Powers/costs are
 * tuned so a standard battle lasts ~6–12 turns (see damage.ts): base HP ~110,
 * a reliable attack ~14–20 damage after defence, heavies ~28–36, finishers
 * more under their condition. RECOVER (below) is the universal fallback.
 */

export const RECOVER_MOVE: BattleMove = {
  id: 'recover',
  name: 'Recover',
  description: 'Catch your breath — restore a chunk of stamina. Always available, deals no damage.',
  category: 'recovery',
  requiredChampion: 'aesthetic', // unused for the shared fallback
  staminaCost: 0,
  basePower: 0,
  accuracy: 1,
  priority: 0,
  cooldown: 0,
  effects: [{ kind: 'restore_stamina', target: 'self', amount: 35 }],
  animationType: 'recovery',
  target: 'self',
  theme: 'success',
};

const AESTHETIC: BattleMove[] = [
  {
    id: 'precision_strike',
    name: 'Precision Strike',
    description: 'A reliable, high-accuracy hit with a raised crit chance.',
    category: 'attack',
    requiredChampion: 'aesthetic',
    staminaCost: 12,
    basePower: 22,
    accuracy: 0.98,
    priority: 0,
    cooldown: 0,
    effects: [{ kind: 'buff_self', status: 'perfect_form', target: 'self', duration: 1, amount: 0.12, chance: 0.5 }],
    animationType: 'technique',
    target: 'opponent',
    theme: 'accent',
  },
  {
    id: 'perfect_form',
    name: 'Perfect Form',
    description: 'Raise precision and evasion for two turns. No damage.',
    category: 'buff',
    requiredChampion: 'aesthetic',
    staminaCost: 14,
    basePower: 0,
    accuracy: 1,
    priority: 1,
    cooldown: 3,
    effects: [{ kind: 'apply_status', status: 'perfect_form', target: 'self', duration: 2, amount: 0.22 }],
    animationType: 'buff',
    target: 'self',
    theme: 'epic',
  },
  {
    id: 'counter_pose',
    name: 'Counter Pose',
    description: 'A guarded stance — cut incoming damage this turn and return part of it.',
    category: 'defence',
    requiredChampion: 'aesthetic',
    staminaCost: 10,
    basePower: 0,
    accuracy: 1,
    priority: 2,
    cooldown: 1,
    effects: [], // the guard stance is applied by the engine (counter_pose)
    animationType: 'defence',
    target: 'self',
    theme: 'rare',
  },
  {
    id: 'apex_execution',
    name: 'Apex Execution',
    description: 'A strong technique — devastating if the opponent is below 40% health.',
    category: 'ultimate',
    requiredChampion: 'aesthetic',
    staminaCost: 30,
    basePower: 30,
    accuracy: 0.92,
    priority: 0,
    cooldown: 2,
    effects: [],
    animationType: 'ultimate',
    target: 'opponent',
    theme: 'legendary',
    conditional: { kind: 'execute_below', threshold: 0.4, multiplier: 1.8 },
  },
];

const TITAN: BattleMove[] = [
  {
    id: 'forge_smash',
    name: 'Forge Smash',
    description: 'A heavy blow with a chance to stagger.',
    category: 'heavy',
    requiredChampion: 'titan',
    staminaCost: 18,
    basePower: 28,
    accuracy: 0.9,
    priority: 0,
    cooldown: 0,
    effects: [{ kind: 'apply_status', status: 'stagger', target: 'opponent', duration: 2, amount: 0.25, chance: 0.4 }],
    animationType: 'heavy',
    target: 'opponent',
    theme: 'legendary',
  },
  {
    id: 'iron_guard',
    name: 'Iron Guard',
    description: 'Brace hard — greatly raise defence for a turn and recover some stamina.',
    category: 'defence',
    requiredChampion: 'titan',
    staminaCost: 8,
    basePower: 0,
    accuracy: 1,
    priority: 2,
    cooldown: 1,
    effects: [{ kind: 'restore_stamina', target: 'self', amount: 12 }], // the guard stance is applied by the engine (iron_guard)
    animationType: 'defence',
    target: 'self',
    theme: 'rare',
  },
  {
    id: 'colossal_pressure',
    name: 'Colossal Pressure',
    description: 'Moderate damage that breaks the opponent’s guard (does not stack).',
    category: 'debuff',
    requiredChampion: 'titan',
    staminaCost: 14,
    basePower: 18,
    accuracy: 0.95,
    priority: 0,
    cooldown: 0,
    effects: [{ kind: 'apply_status', status: 'guard_break', target: 'opponent', duration: 2, amount: 0.25 }],
    animationType: 'technique',
    target: 'opponent',
    theme: 'epic',
  },
  {
    id: 'titan_breaker',
    name: 'Titan Breaker',
    description: 'A colossal, slow strike — stronger the more damage Titan has taken.',
    category: 'ultimate',
    requiredChampion: 'titan',
    staminaCost: 32,
    basePower: 34,
    accuracy: 0.88,
    priority: -1,
    cooldown: 2,
    effects: [],
    animationType: 'ultimate',
    target: 'opponent',
    theme: 'legendary',
    conditional: { kind: 'stronger_if_damaged', multiplier: 1.6 },
  },
];

const APEX: BattleMove[] = [
  {
    id: 'rapid_strike',
    name: 'Rapid Strike',
    description: 'A quick jab that may land twice. Cheap.',
    category: 'attack',
    requiredChampion: 'apex',
    staminaCost: 8,
    basePower: 12,
    accuracy: 0.96,
    priority: 1,
    cooldown: 0,
    effects: [],
    animationType: 'quick',
    target: 'opponent',
    theme: 'accent',
    multiHit: { times: 2, chance: 0.55 },
  },
  {
    id: 'overclock',
    name: 'Overclock',
    description: 'Spike speed and stamina regen for two turns — at the cost of defence.',
    category: 'buff',
    requiredChampion: 'apex',
    staminaCost: 12,
    basePower: 0,
    accuracy: 1,
    priority: 1,
    cooldown: 3,
    effects: [{ kind: 'apply_status', status: 'overclocked', target: 'self', duration: 2, amount: 0.3 }],
    animationType: 'buff',
    target: 'self',
    theme: 'epic',
  },
  {
    id: 'second_wind',
    name: 'Second Wind',
    description: 'Restore stamina and a little health. Short cooldown.',
    category: 'recovery',
    requiredChampion: 'apex',
    staminaCost: 0,
    basePower: 0,
    accuracy: 1,
    priority: 1,
    cooldown: 3,
    effects: [
      { kind: 'restore_stamina', target: 'self', amount: 30 },
      { kind: 'restore_health', target: 'self', amount: 14 },
    ],
    animationType: 'recovery',
    target: 'self',
    theme: 'success',
  },
  {
    id: 'velocity_crash',
    name: 'Velocity Crash',
    description: 'A dash whose force scales with speed. Expensive.',
    category: 'heavy',
    requiredChampion: 'apex',
    staminaCost: 26,
    basePower: 20,
    accuracy: 0.92,
    priority: 0,
    cooldown: 1,
    effects: [],
    animationType: 'ultimate',
    target: 'opponent',
    theme: 'legendary',
  },
];

const SHREDDED: BattleMove[] = [
  {
    id: 'twin_slash',
    name: 'Twin Slash',
    description: 'Two quick cuts with a chance to open a bleed.',
    category: 'attack',
    requiredChampion: 'shredded',
    staminaCost: 12,
    basePower: 18,
    accuracy: 0.95,
    priority: 0,
    cooldown: 0,
    effects: [{ kind: 'apply_status', status: 'bleed', target: 'opponent', duration: 3, amount: 6, chance: 0.5 }],
    animationType: 'quick',
    target: 'opponent',
    theme: 'danger',
  },
  {
    id: 'shadow_step',
    name: 'Shadow Step',
    description: 'Vanish — huge evasion this turn, and your next attack hits harder.',
    category: 'buff',
    requiredChampion: 'shredded',
    staminaCost: 12,
    basePower: 0,
    accuracy: 1,
    priority: 2,
    cooldown: 2,
    effects: [{ kind: 'apply_status', status: 'perfect_form', target: 'self', duration: 1, amount: 0.4 }],
    animationType: 'buff',
    target: 'self',
    theme: 'rare',
  },
  {
    id: 'cut_deep',
    name: 'Cut Deep',
    description: 'A precise strike — far stronger against a bleeding target.',
    category: 'technique',
    requiredChampion: 'shredded',
    staminaCost: 16,
    basePower: 20,
    accuracy: 0.93,
    priority: 0,
    cooldown: 0,
    effects: [],
    animationType: 'technique',
    target: 'opponent',
    theme: 'epic',
    conditional: { kind: 'stronger_if_bleeding', multiplier: 1.7 },
  },
  {
    id: 'final_shred',
    name: 'Final Shred',
    description: 'A finisher — brutal below 30% enemy health.',
    category: 'ultimate',
    requiredChampion: 'shredded',
    staminaCost: 30,
    basePower: 26,
    accuracy: 0.9,
    priority: 0,
    cooldown: 2,
    effects: [],
    animationType: 'ultimate',
    target: 'opponent',
    theme: 'legendary',
    conditional: { kind: 'execute_below', threshold: 0.3, multiplier: 2.0 },
  },
];

export const MOVES_BY_CHAMPION: Record<ChampionId, BattleMove[]> = {
  aesthetic: AESTHETIC,
  titan: TITAN,
  apex: APEX,
  shredded: SHREDDED,
};

/** Every move keyed by id, incl. the shared Recover. */
export const ALL_MOVES: Record<string, BattleMove> = Object.fromEntries(
  [...AESTHETIC, ...TITAN, ...APEX, ...SHREDDED, RECOVER_MOVE].map((m) => [m.id, m])
);

export function movesForChampion(id: ChampionId): BattleMove[] {
  return MOVES_BY_CHAMPION[id];
}
